### ISSUE TITLE
After autoreconnect mongo-connector cannot get the cursor

### ISSUE THREAD

**Issue by artemryzhov** [mongodb-labs/mongo-connector#264]
After autoreconnect mongo-connector cannot get the cursor. Documents in elasticsearch dont updates and I have 100% cpu load with mongodb process.

Sorry for my english =)

![image](https://cloud.githubusercontent.com/assets/2933286/8002170/4da9cf22-0b75-11e5-838d-7522ae6aff5e.png)

**Comment by llvtt** [comment]
Just to clarify- what process has 100% cpu? A `mongod` or `mongos` process, or `mongo-connector` itself?

From the screen shot, it appears that `mongo-connector` successfully created the cursor, but nothing in the oplog is more current than the last record it processed. `mongo-connector` isn't treating this as a rollback, because the last record it processed still exists in the oplog.

Do you know what caused the `AutoReconnect`?

**Comment by llvtt** [comment]
Any update on this?

**Comment by marcinkubica** [comment]
Got similar issue here. However I'm not seeing high CPU usage. After restarting mongodb got following in the log.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 156, in run
    cursor, cursor_len = self.init_cursor()
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 605, in init_cursor
    cursor_len = retry_until_ok(cursor.count)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 72, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 768, in count
    **command)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 439, in command
    uuid_subtype, compile_re, **kwargs)[0]
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 338, in _command
    for doc in cursor:
  File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 1022, in _refresh
    self.__uuid_subtype))
  File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 933, in __send_message
    res = client._send_message_with_response(message, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 1199, in _send_message_with_response
    member = self.__ensure_member()
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 814, in __ensure_member
    member, nodes = self.__find_node()
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 905, in __find_node
    raise AutoReconnect(', '.join(errors))
AutoReconnect: [Errno -2] Name or service not known

/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py:1353: UserWarning: not connected, couldn't close cursor
  warnings.warn("not connected, couldn't close cursor")
```

However, obviously recovery is problematic after restarting mongo-connector

```
2015-10-08 00:39:06,023 [ERROR] mongo_connector.oplog_manager:162 - OplogThread: Last entry no longer in oplog cannot recover! Collection(Database(MongoClient(u'__IP__', 27017), u'local'), u'oplog.rs')
2015-10-08 00:39:06,933 [ERROR] __main__:302 - MongoConnector: OplogThread <OplogThread(Thread-3, stopped 140474622932736)> unexpectedly stopped! Shutting down
```

Interestingly I've tried to replicate this and did not observe the problem after stopping and starting mongodb.

**Comment by phber** [comment]
I am encountering the same issue on a MongoDb 3.0.6 server, as adressed in[ this thread.](https://github.com/mongodb-labs/mongo-connector/issues/329#issuecomment-182066987).

I initially managed to sync my data with elasticsearch, but when I try to run the connector my mongod process consumes 100% CPU and I am getting the same debug file as in artemryzhov.

Is there any way to solve this problem?

**Comment by aherlihy** [comment]
Hi @phber, have you updated to the most recent version of Mongo-Connector? The issue that you linked was resolved by using a more recent version of PyMongo in Mongo-Connector.

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more questions. Thanks!
