### ISSUE TITLE
Dump not succes full due to UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position

### ISSUE THREAD

**Issue by avinashacco** [mongodb-labs/mongo-connector#290]
2015-07-19 21:30:22,568 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\mongo_connector\oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "C:\Python27\lib\site-packages\mongo_connector\oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "C:\Python27\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 288, in bulk_upsert
    self.solr.add(batch, **add_kwargs)
  File "C:\Python27\lib\site-packages\pysolr.py", line 813, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "C:\Python27\lib\site-packages\pysolr.py", line 399, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "C:\Python27\lib\site-packages\pysolr.py", line 308, in _send_request
    resp = requests_method(url, data=bytes_body, headers=headers, files=files, timeout=self.timeout)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python27\lib\httplib.py", line 946, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 987, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 940, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 801, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 350: ordinal not in range(128)
2015-07-19 21:30:22,572 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient('localhost', 27017), u'local'), u'oplog.rs')
2015-07-19 21:30:23,401 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 6196)> unexpectedly stopped! Shutting down

Can you help fix this.

**Comment by llvtt** [comment]
It looks like this Exception is coming from `pysolr`, the Python driver for Solr. Can you please turn on debug-level logging for the Solr driver? This should print the headers and message body of the requests being sent, and we should hopefully be able to figure out what's causing the problem from that.

    export DEBUG_PYSOLR=true

thanks.

**Comment by aherlihy** [comment]
Hello! I'm going to close this issue due to inactivity. If you are still experiencing any problems feel free to reopen or file a new issue. Thank you!
