### ISSUE TITLE
mongo-connect

### ISSUE THREAD

**Issue by xianaiyang** [mongodb-labs/mongo-connector#291]
mongo-connector --auto-commit-interval=1 -d solr_doc_manager -t http://localhost:8983/solr/mongoData  --unique-key=id
exit without error information
and when i restart mongo-connector it will exit without error message
mongo-connector --auto-commit-interval=1 -d solr_doc_manager -t http://localhost:8983/solr/mongoData  --unique-key=id
Logging to mongo-connector.log.
[mburec@lg_3a-f3-60_ops ~]$

**Comment by llvtt** [comment]
All output goes to the log file "mongo-connector.log". Try taking a look in
there for the output. You can also increase the verbosity with "-v" and/or
send logging to the terminal instead of the log file with "--stdout".

**Comment by xianaiyang** [comment]
Thanks for your quick reply.
I checked the "mongo-connector.log". It seems that the recover point was broken for some reason.
the log as below. I restart the mongo-connector in some other new folder, it can restart, and it seems work well until now.
 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient('localhost', 27017), u'local'), u'oplog.rs')
2015-07-22 09:24:26,715 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140682942461696)> unexpectedly stopped! Shutting down

**Comment by llvtt** [comment]
Is there anything else in the log? If not, can you try increasing the
verbosity (-v flag)? This message just indicates that there was a problem
during while copying documents from MongoDB before tailing the oplog.

**Comment by aherlihy** [comment]
@xianaiyang Hello! Are you still experiencing this issue? And if so, have you upgraded to the most recent version of mongo-connector? Thank you!

**Comment by aherlihy** [comment]
Hello, I'm going to close this issue due to inactivity but please feel free to reopen or file a new one if the problem persists. Thank you!

**Comment by prashant2101** [comment]
Hi @aherlihy,

I am facing the same issue although I am using mongo-connector 2.5.1. 
Here is the output of tail -f mongo-connector.log 
2017-06-28 09:55:38,338 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector versionwewe34343434: 2.5.1
2017-06-28 09:55:38,338 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
2017-06-28 09:55:38,341 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-3.13.0-39-generic-x86_64-with-Ubuntu-14.04-trusty
2017-06-28 09:55:38,341 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.1.1
2017-06-28 09:55:38,360 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.2.5
2017-06-28 09:55:38,360 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-06-28 09:56:35,014 [CRITICAL] mongo_connector.oplog_manager:670 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 625, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 611, in upsert_all
    mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 41, in wrapped
    exc_type, exc_value, exc_tb = sys.exc_info()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 38, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 371, in bulk_upsert
    for ok, resp in responses:
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
OperationFailed: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'test_type', u'_id': u'58a2d03238eb45116d9sf277', u'error': {u'caused_by': {u'reason': u'Invalid format: ""', u'type': u'illegal_argument_exception'}, u'reason': u'failed to parse [completion_date.date]', u'type': u'mapper_parsing_exception'}, u'_index': u'index1'}}])
2017-06-28 09:56:35,015 [ERROR] mongo_connector.oplog_manager:678 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=[u'localhost:27018'], document_class=dict, tz_aware=False, connect=True, replicaset=u'rs0'), u'local'), u'oplog.rs')
2017-06-28 09:56:35,453 [ERROR] mongo_connector.connector:401 - MongoConnector: OplogThread <OplogThread(Thread-3, started 140121219262208)> unexpectedly stopped! Shutting down

Kindly suggest the possible solution, Thank you.

**Comment by ShaneHarvey** [comment]
@prashant2101 Your issue seems identical to https://github.com/mongodb-labs/elastic2-doc-manager/issues/20 and https://github.com/mongodb-labs/elastic2-doc-manager/issues/26
