### ISSUE TITLE
Failed during dump collection cannot recover!

### ISSUE THREAD

**Issue by snowaved** [mongodb-labs/mongo-connector#339]
when i sync data  from  cluter 1  to   cluster 2 ,  mongo connector runs  some time  ,it occurs some errors and exit:

2015-10-12 17:58:47,586 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/mongo_doc_manager.py", line 180, in bulk_upsert
    meta_bulk_op.execute()
  File "/usr/lib64/python2.6/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/usr/lib64/python2.6/site-packages/pymongo/bulk.py", line 433, in execute
    return self.execute_command(generator, write_concern)
  File "/usr/lib64/python2.6/site-packages/pymongo/bulk.py", line 300, in execute_command
    raise BulkWriteError(full_result)
BulkWriteError: batch op errors occurred
2015-10-12 17:58:47,599 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient([u'ip:25019', u'ip:25017']), u'local'), u'oplog.rs')
2015-10-12 17:58:47,599 [DEBUG] mongo_connector.oplog_manager:167 - OplogThread: Last entry is the one we already processed.  Up to date.  Sleeping.
2015-10-12 17:58:48,500 [ERROR] mongo_connector.connector:321 - MongoConnector: OplogThread <OplogThread(Thread-2, started 139671810971392)> unexpectedly stopped! Shutt
ing down
2015-10-12 17:58:48,501 [INFO] mongo_connector.connector:359 - MongoConnector: Stopping all OplogThreads
2015-10-12 17:58:48,501 [DEBUG] mongo_connector.oplog_manager:330 - OplogThread: exiting due to join call.
2015-10-12 17:58:48,545 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/mongo_doc_manager.py", line 180, in bulk_upsert
    meta_bulk_op.execute()
  File "/usr/lib64/python2.6/site-packages/pymongo/bulk.py", line 587, in execute
    return self.__bulk.execute(write_concern)
  File "/usr/lib64/python2.6/site-packages/pymongo/bulk.py", line 433, in execute
    return self.execute_command(generator, write_concern)
  File "/usr/lib64/python2.6/site-packages/pymongo/bulk.py", line 300, in execute_command
    raise BulkWriteError(full_result)
BulkWriteError: batch op errors occurred
2015-10-12 17:58:48,545 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient([u'ip:25019', u'ip:25017']), u'local'), u'oplog.rs')
2015-10-12 17:58:48,545 [DEBUG] mongo_connector.oplog_manager:167 - OplogThread: Last entry is the one we already processed.  Up to date.  Sleeping.
2015-10-12 17:58:49,547 [DEBUG] mongo_connector.oplog_manager:330 - OplogThread: exiting due to join call.
2015-10-12 17:58:49,547 [INFO] mongo_connector.doc_managers.mongo_doc_manager:91 - Mongo DocManager Stopped: If you will not target this system again with mongo-connect
or then you may drop the database __mongo_connector, which holds metadata for Mongo Connector.

thanks...

**Comment by Jinshui** [comment]
I am having the same issue too. It seems the timeout value is too short. Is it possible to set the timeout to a longer value? 

2015-10-20 01:48:04,992 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
    for ok, resp in responses:
  File "/usr/lib/python2.6/site-packages/elasticsearch/helpers/__init__.py", line 138, in streaming_bulk
    raise e
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'172.31.1.254', port=9200): Read timed out. (read timeout=10))

**Comment by llvtt** [comment]
You can set arbitrary options in the Elastic client's constructor using mongo-connector's config file. See https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-ElasticSearch#customizing-behavior-of-the-elastic-client

**Comment by Jinshui** [comment]
Thanks a lot, llvtt. 

So we can pass the 'timeout' option to the elatic client in the mongo-connector's config file. 

And is there a way to set the chunk_size without changing the constant.py? It's by default 1000 in the constant.py, and it is 500 by default in the  streaming_bulk function of the elastic client.  I have to change the chunk_size to a smaller value because my docs are pretty large, it may be up to 500KB/doc, so 500 docs for a bulk request may cause memory leak and the mongo-connector may exit without any log. I have seen this issue while dumping the docs from mongo to elastic search. 

The following is the code causing memory leak in the streaming_bulk function of the elasticsearch/\__init\__.py file
```
        chunk = islice(actions, chunk_size)

        # raise on exception means we might need to iterate on chunk twice
        if not raise_on_exception:
            chunk = list(chunk)

        bulk_actions = []
        for action, data in chunk:
            bulk_actions.append(action)
            if data is not None:
                bulk_actions.append(data)
```

Please comment.

**Comment by aherlihy** [comment]
Hi @Jinshui is https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#docmanagersindexbulksize what you are looking for?

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more questions. Thanks!
