### ISSUE TITLE
Field name can not contain '.'

### ISSUE THREAD

**Issue by ali-bugdayci** [mongodb-labs/mongo-connector#340]
I am getting the following error:

Field name [a.b.c] cannot contain '.'"

And mongo connector exists. Shall we replace '.' with '_' or another delimiter before parsing ?

Or at least warn the user and continue processing in mongo connector

The full exception is: 

```
2015-10-12 18:16:28,567 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
    for ok, resp in responses:
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 156, in streaming_bulk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
```

**Comment by llvtt** [comment]
MongoDB field names must not contain a '.' in the name. See https://docs.mongodb.org/manual/core/document/#field-names for details on valid MongoDB field names.
