### ISSUE TITLE
Connection error to Amazon Elasticsearch service instance

### ISSUE THREAD

**Issue by krishnasarthi** [mongodb-labs/mongo-connector#342]
Unable to connect to Elasticsearch instance as service on Amazon (Amazon ES). Adding log details. From viewing the log I can see mongo-connector is trying to post to port 9200, though the service is not accessible at that port.

2015-10-15 18:22:30,879 [INFO] mongo_connector.connector:1030 - Beginning Mongo Connector
2015-10-15 18:22:30,879 [WARNING] mongo_connector.connector:116 - MongoConnector: Can't find oplog.timestamp, attempting to create an empty progress log
2015-10-15 18:22:30,888 [ERROR] mongo_connector.util:87 - Fatal Exception
2015-10-15 18:23:14,608 [INFO] mongo_connector.connector:1030 - Beginning Mongo Connector
2015-10-15 18:23:14,618 [INFO] mongo_connector.connector:223 - MongoConnector: Empty oplog progress file.
2015-10-15 18:23:14,620 [INFO] mongo_connector.oplog_manager:86 - OplogThread: Initializing oplog thread
2015-10-15 18:23:14,621 [INFO] mongo_connector.connector:295 - MongoConnector: Starting connection thread MongoClient('localhost', 27017)
2015-10-15 18:23:14,622 [DEBUG] mongo_connector.oplog_manager:153 - OplogThread: Run thread started
2015-10-15 18:23:14,622 [DEBUG] mongo_connector.oplog_manager:155 - OplogThread: Getting cursor
2015-10-15 18:23:14,622 [DEBUG] mongo_connector.oplog_manager:661 - OplogThread: reading last checkpoint as None 
2015-10-15 18:23:14,622 [DEBUG] mongo_connector.oplog_manager:395 - OplogThread: Dumping set of collections ['releaseV3.chatmessages'] 
2015-10-15 18:23:14,901 [DEBUG] mongo_connector.oplog_manager:573 - OplogThread: Last oplog entry has timestamp 1443698800.
2015-10-15 18:23:14,901 [DEBUG] mongo_connector.oplog_manager:493 - OplogThread: Using bulk upsert function for collection dump
2015-10-15 18:23:15,119 [DEBUG] urllib3.util.retry:155 - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-10-15 18:23:15,120 [INFO] urllib3.connectionpool:205 - Starting new HTTP connection (1): search-beepssearch-bhzeiu2sqoiothwciud55exgbe.us-west-2.es.amazonaws.com
2015-10-15 18:23:25,156 [WARNING] elasticsearch:82 - POST http://search-beepssearch-bhzeiu2sqoiothwciud55exgbe.us-west-2.es.amazonaws.com:9200/_bulk [status:N/A request:10.037s]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python34\lib\site-packages\urllib3\util\connection.py", line 90, in create_connection
    raise err
  File "C:\Python34\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 607, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python34\lib\site-packages\urllib3\packages\six.py", line 310, in reraise
    raise value
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 351, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 155, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 139, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x03359310>, 'Connection to search-beepssearch-bhzeiu2sqoiothwciud55exgbe.us-west-2.es.amazonaws.com timed out. (connect timeout=10)')

**Comment by llvtt** [comment]
Explicitly specify the port number after the host: mongo-connector -t
hostname:port

**Comment by aherlihy** [comment]
@krishnasarthi has this solved your issue?

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more issues. Thanks!
