### ISSUE TITLE
Users should be able to set the timeout and the chunk_size for elastic search bulk requests.

### ISSUE THREAD

**Issue by Jinshui** [mongodb-labs/mongo-connector#343]
While dumping huge data to elasticsearch, the mongo-connector can't work normally because it often crashes due to connection timeout.  The default timeout is 10, and can't be changed. It should be an option of the mongo-connector command so that user can change it when necessary.
```
2015-10-20 01:48:04,992 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
    for ok, resp in responses:
  File "/usr/lib/python2.6/site-packages/elasticsearch/helpers/__init__.py", line 138, in streaming_bulk
    raise e
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'172.31.1.254', port=9200): Read timed out. (read timeout=10))
```
Thanks,

**Comment by Jinshui** [comment]
Please note that the line number of the python file in the log above may be incorrect because I modified the python to add more log locally.

**Comment by Jinshui** [comment]
More logs:

2015-10-20 01:48:04,713 [WARNING] elasticsearch:83 - POST http://172.31.1.254:9200/_bulk [status:N/A request:10.110s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 607, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.6/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 378, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host=u'172.31.1.254', port=9200): Read timed out. (read timeout=10)

**Comment by Jinshui** [comment]
I made the following change (line 4) in elastic_doc_manager to increase the time out to 60, it solves my issue:

1            kw = {}
2           if self.chunk_size > 0:
3               kw['chunk_size'] = self.chunk_size
4+             kw['request_timeout'] = 60
5            responses = streaming_bulk(client=self.elastic,
6                                       actions=docs_to_upsert(),
7                                       **kw)

I hope it can be a param of the mongo-connector command.

**Comment by Jinshui** [comment]
I also hope the chunk_size of the streaming_bulk request can be a param too. it is by default 500. If the size of each doc is large, then the code in elasticsearch/helpers/__init__.py below can cause memory leak. I encountered this issue today, the mongo-connector process exits without any error info. 
```
        bulk_actions = []
        for action, data in chunk:
            bulk_actions.append(action)
            if data is not None:
                bulk_actions.append(data) 
```

Thanks,

**Comment by Jinshui** [comment]
It seems both of the timeout and chunk_size can be configured by the configuration file as follows:
```
{
  "docManagers": [
    {
      "docManager": "elastic_doc_manager",
      "targetURL": "localhost:9200",
      "bulkSize": 200,
      "autoCommitInterval": 0,
      "args": {
        "clientOptions": {"timeout": 60}
      }
    }
  ]
}
```

Can anyone please confirm? I will test it later.
