### ISSUE TITLE
mongo-connector fails I am connecting to mongodb shared cluster

### ISSUE THREAD

**Issue by ynnt** [mongodb-labs/mongo-connector#345]
mongo-connector  -m mongo:27117 -t es:9200 -d elastic_doc_manager

mongo version: 3.0.4
elasticsearch: 2.0

```
Logging to mongo-connector.log.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pymongo/mongo_client.py", line 422, in __init__
    self._ensure_connected(True)
  File "/usr/local/lib/python3.4/site-packages/pymongo/mongo_client.py", line 1070, in _ensure_connected
    self.__ensure_member()
  File "/usr/local/lib/python3.4/site-packages/pymongo/mongo_client.py", line 944, in __ensure_member
    member, nodes = self.__find_node()
  File "/usr/local/lib/python3.4/site-packages/pymongo/mongo_client.py", line 1035, in __find_node
    raise AutoReconnect(', '.join(errors))
pymongo.errors.AutoReconnect: [Errno -2] Name or service not known, [Errno -2] Name or service not known
```

I can manually connect to both services.

Just for clarification:
My mongo setup:
I have a mongos, and every shard configured as a replica set.
Do I need to run mongo-connector for every shard?

**Comment by ynnt** [comment]
Sorru, that was my fault
