### ISSUE TITLE
drop collection causes a Fatal Exception in MongoConnector

### ISSUE THREAD

**Issue by hsajjad73** [mongodb-labs/mongo-connector#349]
Full error below.
The connector needs to restart to resume any replication with ElasticSearch

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 272, in run
    timestamp)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 111, in handle_command
    self.elastic.indices.delete_mapping(index=db.lower(),
AttributeError: 'IndicesClient' object has no attribute 'delete_mapping'

2015-10-25 01:19:09,366 [ERROR] mongo_connector.util:87 - Fatal Exception

**Comment by hsajjad73** [comment]
Further, Mongo Connector has an issue replicating the drop collection, but works OK if entire DB is dropped instead. Succeeds in dropping the index from ElaticSearch.
db.getSisterDB("myDbName").dropDatabase()

**Comment by llvtt** [comment]
This duplcates #348. Please see my comments there.
