### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by patrickml** [mongodb-labs/mongo-connector#363]
I am getting this error everytime the application trys to sync. But its only happening on one of my collections

```txt
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 264, in run
    ns, timestamp)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 261, in update
    self.upsert(self.apply_update(doc, update_spec), True)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/algolia_doc_manager.py", line 246, in apply_update
    doc = super(DocManager, self).apply_update(doc, update_spec)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/doc_manager_base.py", line 70, in apply_update
    wl = len(where)
TypeError: object of type 'NoneType' has no len()
```

**Comment by llvtt** [comment]
Can you also provide the logs from mongo-connector? Thanks!

**Comment by patrickml** [comment]
```txt
2015-12-02 09:57:24,367 [ERROR] mongo_connector.util:87 - Fatal Exception
```

**Comment by llvtt** [comment]
Is this the only entry in the log? If so, turning on debug-level logging would be useful here. Also, an example of the kind of update operation that's causing this failure would be helpful.

**Comment by patrickml** [comment]
I will give it a shot tonight and let you know the outcome

**Comment by behackett** [comment]
Could this be a bug in algolia_doc_manager, which we don't actually develop?

https://www.algolia.com/with/mongodb

**Comment by joshporter1** [comment]
I'm having this same issue, and I didn't notice is start happening until I upgraded my ES cluster from 1.7.1 to 2.2.0. I know you're not using the same doc manager, and support for 2.x isn't complete yet, but perhaps it's somehow related?

**Comment by behackett** [comment]
From the traceback it is clear that algolia_doc_manager is being used, not the elastic search doc manager.

**Comment by joshporter1** [comment]
Yeah, I saw that. Just a thought, perhaps it could be related to that doc manager not supporting 2.x as well, since it's the same traceback (sub the doc manager).

**Comment by aherlihy** [comment]
Hello! I'm going to close this issue due to inactivity, but if the issue persists please feel free to repopen or create a new issue.
