### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by bbonnin** [mongodb-labs/mongo-connector#366]
Hello,

My context is : 
- MongoDB 3.0.7 and Elasticsearch 1.72
- my command line : mongo-connector -m localhost:27100 -t localhost:9200 -n test.metadata --fields fileId -d elastic_doc_manager

I got the following error : 

2015-12-04 16:11:15,267 [ERROR] mongo_connector.util:77 - Call to "bound method Cursor.count of "pymongo.cursor.Cursor object at 0x7fe07076e090"
" failed too many times in retry_until_ok
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/util.py", line 72, in retry_until_ok
    return func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 831, in count
    **command)
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 535, in command
    codec_options, **kwargs)[0]
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 433, in _command
    for doc in cursor:
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 1149, in next
    if len(self.__data) or self._refresh():
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 1081, in _refresh
    self.__codec_options.uuid_representation))
  File "build/bdist.linux-x86_64/egg/pymongo/message.py", line 160, in query
    encoded = bson.BSON.encode(query, False, uuid_subtype)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 701, in encode
    return cls(_dict_to_bson(document, check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 491, in _dict_to_bson
    check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 419, in _element_to_bson
    return BSONOBJ + name + _dict_to_bson(value, check_keys, uuid_subtype, False)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 491, in _dict_to_bson
    check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 419, in _element_to_bson
    return BSONOBJ + name + _dict_to_bson(value, check_keys, uuid_subtype, False)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 491, in _dict_to_bson
    check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 421, in _element_to_bson
    as_dict = SON(zip([str(i) for i in range(len(value))], value))
  File "build/bdist.linux-x86_64/egg/bson/son.py", line 88, in __init__
    self.update(data)
  File "build/bdist.linux-x86_64/egg/bson/son.py", line 192, in update
    self[k] = v
  File "build/bdist.linux-x86_64/egg/bson/son.py", line 105, in __setitem__
    dict.__setitem__(self, key, value)
RuntimeError: maximum recursion depth exceeded while calling a Python object
2015-12-04 16:11:15,273 [ERROR] mongo_connector.util:87 - Fatal Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 156, in run
    cursor, cursor_len = self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 613, in init_cursor
    return self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 613, in init_cursor
    return self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 613, in init_cursor
    return self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 613, in init_cursor

.... [same lines as above many times]

  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 613, in init_cursor
    return self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 605, in init_cursor
    cursor_len = retry_until_ok(cursor.count)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/util.py", line 72, in retry_until_ok
    return func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 831, in count
    **command)
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 535, in command
    codec_options, **kwargs)[0]
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 433, in _command
    for doc in cursor:
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 1149, in next
    if len(self.__data) or self._refresh():
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 1081, in _refresh
    self.__codec_options.uuid_representation))
  File "build/bdist.linux-x86_64/egg/pymongo/message.py", line 160, in query
    encoded = bson.BSON.encode(query, False, uuid_subtype)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 701, in encode
    return cls(_dict_to_bson(document, check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 491, in _dict_to_bson
    check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 419, in _element_to_bson
    return BSONOBJ + name + _dict_to_bson(value, check_keys, uuid_subtype, False)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 491, in _dict_to_bson
    check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 419, in _element_to_bson
    return BSONOBJ + name + _dict_to_bson(value, check_keys, uuid_subtype, False)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 491, in _dict_to_bson
    check_keys, uuid_subtype))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 421, in _element_to_bson
    as_dict = SON(zip([str(i) for i in range(len(value))], value))
  File "build/bdist.linux-x86_64/egg/bson/son.py", line 88, in __init__
    self.update(data)
  File "build/bdist.linux-x86_64/egg/bson/son.py", line 192, in update
    self[k] = v
  File "build/bdist.linux-x86_64/egg/bson/son.py", line 105, in __setitem__
    dict.__setitem__(self, key, value)
RuntimeError: maximum recursion depth exceeded while calling a Python object

Thanks for your help !

Bruno

**Comment by behackett** [comment]
What version of python are you using? Are you using CPython or PyPy?

**Comment by bbonnin** [comment]
Python : 2.7.6
I am using CPython

**Comment by aherlihy** [comment]
Hello! Have you tried this with the most recent release of mongo-connector? Thanks!

**Comment by bbonnin** [comment]
Hello,

With mongo-connector 2.2, I have the following error:

mongo-connector -m localhost:27100 -t localhost:10200 -n test.inkmetadata --fields fileId -d elastic_doc_manager
Logging to mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2-py2.7.egg/mongo_connector/oplog_manager.py", line 206, in run
    if not self.filter_oplog_entry(entry):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2-py2.7.egg/mongo_connector/oplog_manager.py", line 351, in filter_oplog_entry
    pop_excluded_fields(entry_o)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.2-py2.7.egg/mongo_connector/oplog_manager.py", line 345, in pop_excluded_fields
    for key in set(doc) - self._fields:
TypeError: unsupported operand type(s) for -: 'set' and 'list'

**Comment by aherlihy** [comment]
Hello!

The "TypeError: unsupported operand type(s) for -: 'set' and 'list'" error was a bug introduced with Mongo-Connector 2.2, and fixed in 2.3. Are you still experiencing trouble with the most recent version, off master?

Thank you for your patience!

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more questions. Thanks!

**Comment by bbonnin** [comment]
Hi, no more problem with mongo-connector 2.3. Thanks !
