### ISSUE TITLE
Error updating MongoDb fields

### ISSUE THREAD

**Issue by nestorbr** [mongodb-labs/mongo-connector#368]
Hi,

I'm connecting Solr with MongoDB as following:

Create Solr Core
Configure solarconfg.xml
Configure data-config.xml
Configure schema.xml
Create mongodb replica set.

After running the script, all the documents are indexed successfully in Solr, but when I try to update any object in mongodb database I've got this error 

$ mongo-connector -m localhost:27017 -t http://localhost:8983/solr/restaurants2 -d solr_doc_manager
Logging to mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 263, in run
    ns, timestamp)
  File "/usr/lib/python2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector-2.2.dev0-py2.7.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 248, in update
    doc.pop('ns')
KeyError: 'ns'

Do you have any idea why is this happening? 

Thanks,
Nestor.

**Comment by nestorbr** [comment]
Fixed adding

   <field name="_ts" type="long" indexed="true" stored="true" />
   <field name="ns" type="string" indexed="true" stored="true"/>

To schema.xml
