### ISSUE TITLE
Exception when drop a collection in mongodb. Using ES 2.1.1

### ISSUE THREAD

**Issue by gammaliu** [mongodb-labs/mongo-connector#373]
virtual@ubuntu:~/Downloads$ mongo-connector -m localhost:27017 -t localhost:9200 -d elastic_doc_manager
Logging to mongo-connector.log.

```python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 272, in run
    timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 111, in handle_command
    self.elastic.indices.delete_mapping(index=db.lower(),
AttributeError: 'IndicesClient' object has no attribute 'delete_mapping'
```

Notice that : AttributeError: 'IndicesClient' object has no attribute 'delete_mapping'
Does this mean that it's a error caused by the python client of ES 2.1.1 ?

**Comment by behackett** [comment]
MongoConnector does not currently support ES2. See https://github.com/mongodb-labs/mongo-connector/issues/351
