### ISSUE TITLE
TypeError: string indices must be integers in oplog_manager.py

### ISSUE THREAD

**Issue by tomasaftalion** [mongodb-labs/mongo-connector#374]
Hi,

I'm getting the following error:

[ERROR] mongo_connector.oplog_manager:467 - Could not upsert document: {..}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 462, in upsert_each
    dm.upsert(doc, mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "<string>", line 2, in reraise
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers

Using:

elasticsearch (2.2.0)
mongo-connector (2.1)

Any idea what might be happening?

Best,
Tomas

**Comment by behackett** [comment]
mongo-connector does not yet support ES2 (the API of the eastic search driver changed). See #351 .

**Comment by tomasaftalion** [comment]
Thanks
