### ISSUE TITLE
fatal error ... with elasticsearch ... although " --continue-on-error"

### ISSUE THREAD

**Issue by ysimonx** [mongodb-labs/mongo-connector#378]
Hello
i've got a fatal error on this line
        # Index the source document, using lowercase namespace as index name.
        self.elastic.index(index=index, doc_type=doc_type,
                           body=self._formatter.format_document(doc), id=doc_id,
                           refresh=(self.auto_commit_interval == 0))
which is not tolerated altough i specified "ignore on error" feature

in : doc_managers/elastic_doc_manager.py

    @wrap_exceptions
    def upsert(self, doc, namespace, timestamp):
        """Insert a document into Elasticsearch."""
        index, doc_type = self._index_and_mapping(namespace)
        # No need to duplicate '_id' in source document
        doc_id = u(doc.pop("_id"))
        metadata = {
            "ns": namespace,
            "_ts": timestamp
        }
        # Index the source document, using lowercase namespace as index name.
        self.elastic.index(index=index, doc_type=doc_type,
                           body=self._formatter.format_document(doc), id=doc_id,
                           refresh=(self.auto_commit_interval == 0))
        # Index document metadata with original namespace (mixed upper/lower).
        self.elastic.index(index=self.meta_index_name, doc_type=self.meta_type,
                           body=bson.json_util.dumps(metadata), id=doc_id,
                           refresh=(self.auto_commit_interval == 0))
        # Leave _id, since it's part of the original document
        doc['_id'] = doc_id

the logs are
2016-01-19 15:47:20,340 [DEBUG] mongo_connector.oplog_manager:289 - OplogThread: Doc is processed.
2016-01-19 15:47:20,378 [DEBUG] mongo_connector.oplog_manager:189 - OplogThread: Iterating through cursor, document number in this cursor is 1
2016-01-19 15:47:20,379 [DEBUG] mongo_connector.oplog_manager:234 - OplogThread: Operation for this entry is i
2016-01-19 15:47:20,379 [DEBUG] urllib3.util.retry:155 - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-01-19 15:47:20,382 [DEBUG] urllib3.connectionpool:362 - "PUT /lesbeautes/notification/569e4c782fd11196258b456e?refresh=false HTTP/1.1" 400 282
2016-01-19 15:47:20,382 [WARNING] elasticsearch:82 - PUT /lesbeautes/notification/569e4c782fd11196258b456e?refresh=false [status:400 request:0.003s]
2016-01-19 15:47:20,382 [DEBUG] elasticsearch:90 - > {"extended_params": {"to_id": "569d76fc2fd1110f398b4567", "to_type": "thread", "who_what": "comment_thread", "who_id": "564c4cccd26021e06a8b456a", "who_type": "user"}, "read": false, "created_on": "2016-01-19T14:47:20.323000", "tag": "comment_thread", "params": {"username": "sarah D.", "author_id": "56791b0bd260214c278b4568", "_id": "569d76fc2fd1110f398b4567"}, "user": "56791b0bd260214c278b4568", "message": "%%username%% a posté une réponse sur ta conversation", "extended_message": "%%username%% a posté une réponse sur ta conversation %%thead_title%%", "channel": "messages"}
2016-01-19 15:47:20,383 [ERROR] mongo_connector.util:87 - Fatal Exception

elastic search : 1.7
mongo-connector : last one with pip install

i managed to bypass this fatal error with a " return if doc_type = notification " before the 1st self.elastic.index 
(which is useless in my case)

**Comment by ysimonx** [comment]
stderr: 

No handlers could be found for logger "elasticsearch.trace"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 257, in run
    docman.upsert(doc, ns, timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "<string>", line 2, in reraise
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers

**Comment by ysimonx** [comment]
this issues seems to happen because the "elasticsearch" python library installed when "pip install mongo-connector"  is 2.2

my elasticsearch server is only 1.7

so, i tried to change the "elasticsearch" python library with the 1.7 version
thanks to
https://pypi.python.org/pypi/elasticsearch

**Comment by behackett** [comment]
Thanks for letting us know. We are planning to support ES2. See #351.
