### ISSUE TITLE
how to skip error index all data not stop

### ISSUE THREAD

**Issue by jackbbhua** [mongodb-labs/mongo-connector#379]
I try to index 2000 items.and if there has error,all stop there.this time just index success 200 items.how can i set index all data not stop. thank you.
Logging to mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 256, in run
    docman.upsert(doc, ns, timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "<string>", line 2, in reraise
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers

**Comment by behackett** [comment]
What version of Elasticsearch are you using?

**Comment by jackbbhua** [comment]
i think it is 1.7,do i need use elastic at least 2.1?

**Comment by behackett** [comment]
Can you check what version of the Elasticsearch driver you have installed? This issue sounds specific to the ES 2.x driver, which we don't yet support. See #351.

**Comment by jackbbhua** [comment]
hi,behackett 
i had try this version.it also has error:
Logging to mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 272, in run
    timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "<string>", line 2, in reraise
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/exceptions.py", line 55, in __str__
    cause = ', %r' % self.info['error']['root_cause'][0]['reason']
TypeError: string indices must be integers


elasticsearch version is 
{
status: 200,
name: "Lightbright",
cluster_name: "elasticsearch",
version: {
number: "1.7.3",
build_hash: "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
build_timestamp: "2015-10-15T09:14:17Z",
build_snapshot: false,
lucene_version: "4.10.4"
},
tagline: "You Know, for Search"
}


thank you.

**Comment by behackett** [comment]
I think that's the server version. Can you run this on the command line and post the output?

```
python -c "import elasticsearch; print(elasticsearch.VERSION)"
```

**Comment by jackbbhua** [comment]
thanks for your great help.i had find the problem and fix by this:
https://github.com/mongodb-labs/mongo-connector/issues/378
thank you very much.

**Comment by behackett** [comment]
Great. Thanks for letting us know.

**Comment by ysimonx** [comment]
hey ! great

as i am the writer of #378, i think it would be great if elasticsearch version library was verified when installing mongo-connector with pip install :-)

**Comment by behackett** [comment]
That change has already been made in https://github.com/mongodb-labs/mongo-connector/commit/85fbe99c3f9c1d0e70f097f13bf4dc90532fd13a. A new mongo-connector release with it is coming soon.
