### ISSUE TITLE
mongo-connector oplog error after ReadTimeoutError

### ISSUE THREAD

**Issue by JuHwon** [mongodb-labs/mongo-connector#383]
Hi guys. I am using mongo-connector to fetch data from the mongodb into elasticsearch.

When my DB gets bigger and i do send requests to mongodb the mongo-connector sometimes raises the following error:

```
  2016-01-28 12:20:19,436 [WARNING] elasticsearch:82 - PUT http://localhost:9200/mongodb_meta/mongodb_meta/56a9f968a87401d779db2fe7?refresh=false [status:N/A request:10.604s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10)
```

a view seconds before i was starting an aggregation in the mongodb
```
[12:20:02.134] - info: starting TenMinutesAggregation Job
```
The aggregation Job also removes some entries from the mongodb.
It seems that ElasticSearch had a small time frame where it was not responsing.

Is it normal that the mongo-connector is crashing in such a case?

And now when i try to restart the mongo-connector it tells me:
```
2016-01-28 12:20:22,920 [ERROR] mongo_connector.util:87 - Fatal Exception
2016-01-28 12:26:20,504 [ERROR] mongo_connector.oplog_manager:162 - OplogThread: Last entry no longer in oplog cannot recover! Collection(Database(MongoClient(u'localhost', 27017), u'local'), u'oplog.rs')
2016-01-28 12:26:21,385 [ERROR] __main__:302 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 139793134741248)> unexpectedly stopped! Shutting down
```

What can i do now? What do i have to do to make this setup stable? Please help me out here.
I have installed mongo-connector about 3 month ago via pip. 

BR

**Comment by prigozhinroman** [comment]
I'm experiencing the same issue during initial bulk indexing. I'm trying to index 100 mill records from MongoDB in ElasticSearch, the database is over 150 gigs in size, after about 6 hours of operation I get a timeout.

I think there is a solution to this issue, as ElasticSearch supports timeout parameter in bulk indexing call, all we need is an ability to pass this configuration parameter. I've looked at your configuration tests and  noticed this section of code: 

                        'docManager': 'solr_doc_manager',
                        'targetURL': solr_url,
                        'args': {
                            'clientOptions': {
                                'timeout': 100
                            }
                        }
                    }

I've added it to the config file, then enabled debugging and looked at the log, I still don't see timeout parameter in JSON call of elastic. 

Please advise

**Comment by mikkhait** [comment]
Any update on this?

**Comment by aherlihy** [comment]
Hi @mikkhait @JuHwon @prigozhinroman this is on the to-do list, there are a few other issues to resolve first but it's on the way!

**Comment by JuHwon** [comment]
@aherlihy When can we expect a fix on this issue? I am sorry to say but my time is running and when this will not be fixed soon i have to use an alternative product.

**Comment by llvtt** [comment]
@JuHwon, I just merged a PR that fixes catching some additional exception types. Would you be willing to try against the latest version from the master branch to see if your problem is resolved?

**Comment by JuHwon** [comment]
Thanks for the info and effort!
I will try it and will report you the result. This could take a while though, since the error occurs randomly once a week or something like that.

**Comment by JuHwon** [comment]
I guess it is working now :)

I got everyday the following error:
```bash
    refresh=(self.auto_commit_interval == 0))
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_urllib3.py", line 102, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionFailed: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10))
```

Though the the mongo-connector is still working properly and is not crashing.
I guess we can close this ticket. Thanks for your effort. :star:
