### ISSUE TITLE
TypeError when specify fields in config.json

### ISSUE THREAD

**Issue by tad2021** [mongodb-labs/mongo-connector#397]
I want to index some fields of the documents stored in MongoDB. Then I config the config.json in the way below.
...
"fields": ["_id","title","content","author"],
..
Finally, start up connector using command "mongo-connector -c config.json".

Oops, An error jump out suddenly. The traceback is
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 206, in run
    if not self.filter_oplog_entry(entry):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 351, in filter_oplog_entry
    pop_excluded_fields(entry_o)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 345, in pop_excluded_fields
    for key in set(doc) - self._fields:
TypeError: unsupported operand type(s) for -: 'set' and 'list'

**Comment by behackett** [comment]
@aherlihy this looks like a bug in 2.2.

**Comment by aherlihy** [comment]
Sure does. Looking into it!

**Comment by tad2021** [comment]
Bug fixed by @aherlihy
