### ISSUE TITLE
No replica set members match selector "Primary()"

### ISSUE THREAD

**Issue by adrien-candiotti** [mongodb-labs/mongo-connector#411]
Hi!

I was using mongo-connector with a replica set without ssl.
I added ssl and since i get this error that I don't understand:

```
mongo-connector-1 | 2016-03-23T16:03:16.782699519Z Traceback (most recent call last):
mongo-connector-1 | 2016-03-23T16:03:16.782721233Z   File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
mongo-connector-1 | 2016-03-23T16:03:16.782739915Z     self.run()
mongo-connector-1 | 2016-03-23T16:03:16.782751435Z   File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 85, in wrapped
mongo-connector-1 | 2016-03-23T16:03:16.782783475Z     func(*args, **kwargs)
mongo-connector-1 | 2016-03-23T16:03:16.782794877Z   File "/usr/local/lib/python3.5/site-packages/mongo_connector/connector.py", line 292, in run
mongo-connector-1 | 2016-03-23T16:03:16.782805894Z     **self.kwargs)
mongo-connector-1 | 2016-03-23T16:03:16.782815843Z   File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 93, in __init__
mongo-connector-1 | 2016-03-23T16:03:16.782829814Z     if not self.oplog.find_one():
mongo-connector-1 | 2016-03-23T16:03:16.782840214Z   File "/usr/local/lib/python3.5/site-packages/pymongo/collection.py", line 1006, in find_one
mongo-connector-1 | 2016-03-23T16:03:16.782850734Z     for result in cursor.limit(-1):
mongo-connector-1 | 2016-03-23T16:03:16.782860365Z   File "/usr/local/lib/python3.5/site-packages/pymongo/cursor.py", line 1090, in next
mongo-connector-1 | 2016-03-23T16:03:16.782870611Z     if len(self.__data) or self._refresh():
mongo-connector-1 | 2016-03-23T16:03:16.782880305Z   File "/usr/local/lib/python3.5/site-packages/pymongo/cursor.py", line 1012, in _refresh
mongo-connector-1 | 2016-03-23T16:03:16.782890676Z     self.__read_concern))
mongo-connector-1 | 2016-03-23T16:03:16.782900373Z   File "/usr/local/lib/python3.5/site-packages/pymongo/cursor.py", line 850, in __send_message
mongo-connector-1 | 2016-03-23T16:03:16.782910730Z     **kwargs)
mongo-connector-1 | 2016-03-23T16:03:16.782920913Z   File "/usr/local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 781, in _send_message_with_response
mongo-connector-1 | 2016-03-23T16:03:16.782931710Z     server = topology.select_server(selector)
mongo-connector-1 | 2016-03-23T16:03:16.782943398Z   File "/usr/local/lib/python3.5/site-packages/pymongo/topology.py", line 142, in select_server
mongo-connector-1 | 2016-03-23T16:03:16.782953775Z     address))
mongo-connector-1 | 2016-03-23T16:03:16.782963418Z   File "/usr/local/lib/python3.5/site-packages/pymongo/topology.py", line 118, in select_servers
mongo-connector-1 | 2016-03-23T16:03:16.782973855Z     self._error_message(selector))
mongo-connector-1 | 2016-03-23T16:03:16.782983689Z pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()"
```

When I'm checking the status of the set with rs.status() I can see my primary.

Here is my way of launching it :

```
mongo-connector -m mongodb://$USERNAME:$PASSWORD@hostname.com:port/?ssl=true --ssl-certificate-policy ignored
```

No need to precise that i can connect to any member with the mongo-client and ssl.

Thank you for your help!

**Comment by adrien-candiotti** [comment]
It was a configuration issue on my side :)

Just for the record if anyone runs into this issue: the primary was set with the local hostname, making it unreachable i guess for external calls.

**Comment by aipladmin** [comment]
Hey , I am facing this error, can you tell me exactly where I have to make changes

**Comment by SamWangGibhub** [comment]
> It was a configuration issue on my side :)
> 
> Just for the record if anyone runs into this issue: the primary was set with the local hostname, making it unreachable i guess for external calls.

Hi,
I am meeting a similar problem.
**pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()"**
How to solve it?
Thanks!

**Comment by tejash-jl** [comment]
> It was a configuration issue on my side :)
> 
> Just for the record if anyone runs into this issue: the primary was set with the local hostname, making it unreachable i guess for external calls.

I was able to fix this issue by updating replica member host by the domain name or ip address that will be used for connection
```
cfg = rs.conf()
--
cfg.members[1].host = "mongodb1.example.net:27017"
rs.reconfig(cfg)
```
