### ISSUE TITLE
OverlappingFileLockException with elastic search / es2-doc-man

### ISSUE THREAD

**Issue by brackmayhall** [mongodb-labs/mongo-connector#414]
Hi All,

I have been working through trying to get this set up over the last few days but I am still not having any luck. My current set up is the following.

OS: OSX
MongoConnector: latest. Installed through setup.py install
Elastic Search 2.1.2
Mongo: 3.2.3
DocManager: elastic2-doc-manager

The process that I am following is 
1. start up mongodb with `/mongod --dbpath /Volumes/2TB_EXTERN/mongo_data/db/ --replSet myDevReplSet`
2. start elastic search `./elasticsearch` (config file points to same drive but different folder as mongo)
3.start connector with `mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager`

I have tried this with a fully populated mongo database as well as an empty mongodb(and doing single insert) 
I get the same stack trace each time i try to run the connector.

`[2016-03-25 22:10:34,936][WARN ][cluster.action.shard     ] [Titanium Man] [test][4] received shard failed for [test][4], node[bkNMxFjxRZGWCr4soq__nw], [P], v[1], s[INITIALIZING], a[id=zNDl6OsmTZ2o3MP3-fodBQ], unassigned_info[[reason=INDEX_CREATED], at[2016-03-26T02:10:34.476Z]], indexUUID [ch_ujnLTTROBQTXDQiZPkg], message [failed recovery], failure [IndexShardRecoveryException[failed recovery]; nested: OverlappingFileLockException; ]
[test][[test][4]] **IndexShardRecoveryException**[failed recovery]; nested: **OverlappingFileLockException**;
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:114)
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
	at org.apache.lucene.store.FileSwitchDirectory.obtainLock(FileSwitchDirectory.java:75)
	at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:94)
	at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:94)
	at org.apache.lucene.store.SleepingLockWrapper.obtainLock(SleepingLockWrapper.java:84)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:775)
	at org.elasticsearch.index.engine.InternalEngine.createWriter(InternalEngine.java:1090)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:150)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1437)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1421)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:920)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:892)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	... 3 more`

OverlappingFileLockException????? I take it that that means that two processes are trying to lock on the same file at the same time. Has anyone else ran into this issue?

Also should this be posted in the Elastic Search 2 Doc Manager repo issues?

Thanks,
B

**Comment by behackett** [comment]
This looks like a bug in the Elasticsearch database, not mongo-connector. mongo-connector is maintained by MongoDB, not Elasticsearch. I suggest you ask elastic for help:

https://github.com/elastic/elasticsearch/issues
