### ISSUE TITLE
Mongo-connector stuck on fatal exception due to BSON size

### ISSUE THREAD

**Issue by atuljangra** [mongodb-labs/mongo-connector#415]
This is the stack trace: 
```
2016-03-27 05:23:09,079 [ERROR] mongo_connector.util:77 - Call to <bound method Cursor.count of <pymongo.cursor.Cursor object at 0x7fd538991190>> failed too many times in retry_until_ok
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 72, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 831, in count
    **command)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 535, in command
    codec_options, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 440, in _command
    msg, allowable_errors)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 213, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('count', u'oplog.rs'), ('fields', None), ('query', {'ns': {'$in': [u'rssDb.rssStore', u'rssDb.$cmd', 'admin.$cmd']}, 'ts': {'$gte': Timestamp(1459055175, 13)}})]) on namespace local.$cmd failed: exception: BSONObj size: 779314537 (0x2E736569) is invalid. Size must be between 0 and 16793600(16MB) First element: ms: ?type=99
2016-03-27 05:23:09,080 [ERROR] mongo_connector.util:87 - Fatal Exception
```

If I remove the oplog.timestamp file, then it runs well for one run. But eventually it runs into this exception.

**Comment by behackett** [comment]
This must be a bug in MongoDB. What version of MongoDB are you using?

**Comment by atuljangra** [comment]
I'm using Mongo 3.0.7
Yes it seems like a bug in mongo. Can you advise as what could be going wrong. Probably the db got corrupted due to an unexpected shutdown.

**Comment by atuljangra** [comment]
Any update on this?

**Comment by behackett** [comment]
The problem appears to be corruption in the server's oplog. How many replica set members do you have? You could step down the current primary and replace it.

**Comment by behackett** [comment]
I'm going to close this ticket. This isn't a mongoc-connector bug. If you need further help solving the oplog corruption issue I would suggest asking on [mongodb-user](https://groups.google.com/forum/#!forum/mongodb-user).
