### ISSUE TITLE
Mongo-connector instalaltion issue

### ISSUE THREAD

**Issue by skanta200** [mongodb-labs/mongo-connector#429]
When I am trying to start Mongo-Connector, I am getting the following error:

[mongod@ombomdb-qc-a1s doc_managers]$  mongo-connector -m ombomdb-qc-a1s.ula.comcast.net:27017 > -t ombomdb-dt-a3s.ula.comcast.net:27017 > -d /app/mongoconnector/mongo-connector-2.3/mongo_connector/doc_managers/mongo_doc_manager.py
Traceback (most recent call last):
   File "/usr/bin/mongo-connector", line 5, in <module>
     from pkg_resources import load_entry_point
   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
     working_set.require(__requires__)
   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
     needed = self.resolve(parse_requirements(requirements))
   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
     raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pysolr>=3.1.0
[mongod@ombomdb-qc-a1s doc_managers]$

**Comment by aherlihy** [comment]
How have you installed mongo-connector?

Try installing mongo-connector with "pip install mongo-connector", it should automatically download and install the most recent release with any required packages. 

Also, you may want to take a look at the [Usage with MongoDB](https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-MongoDB) wiki page, since it seems you are running mongo-connector with the pre-2.0 release usage. You may be able to run it with just the name of the doc manager, i.e. 
`mongo-connector -m <host:port> -t <host:port> -d mongo_doc_manager`

**Comment by skanta200** [comment]
Our servers don't connect to the Internet directly, thats why I have downloaded the mongo-connector from the following link:

https://github.com/mongodb-labs/mongo-connector

Is there a doc which shows step by step process of installation and setup using the downloaded binaries instead of pip

Or can someone walkthough in our environement. I am available from 9 AM to 6 PM EST . My number is 8566305318

Thanks
Sudheer

**Comment by aherlihy** [comment]
From the FAQ: https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#how-can-i-install-mongo-connector-without-internet-access

Hope that helps!

**Comment by aherlihy** [comment]
@skanta200 Has this solved your problem?

**Comment by skanta200** [comment]
We are not able to get pip on our VM's

Is there an alternative other than PIP , just by using Python commands

Thanks
Sudheer

**Comment by behackett** [comment]
Installing mongo-connector requires pysolr as a dependency. PySolr requires requests as a dependency. requests has,,, a lot of dependencies, which each have more dependencies, and so on, and so on. Manually downloading and installing each of those dependencies is going to be painful.

Why can't you install pip? It's a standard python package available in every modern linux distro's package manager.

**Comment by aherlihy** [comment]
@skanta200, are you still having issues?

**Comment by skanta200** [comment]
Yes. We are still having issues with pip on our server.

Thanks
Sudheer

**Comment by aherlihy** [comment]
Would you mind answering our most recent questions?

> Installing mongo-connector requires pysolr as a dependency. PySolr requires requests as a dependency. requests has... a lot of dependencies, which each have more dependencies, and so on, and so on. Manually downloading and installing each of those dependencies is going to be painful.
> 
> Why can't you install pip? It's a standard python package available in every modern linux distro's package manager. The latest versions of python (2.7.9+, 3.4.0+) include setuptools and pip by default.
> 
> What operating system and version are you using?

**Comment by skanta200** [comment]
For some reason we are not able to install pip on our VM.

Operation System : CentOS Linux release 7.0.1406

Thanks
Sudheer

**Comment by skanta200** [comment]
I tried offline install and I am getting the following permission error. Do we have to run this command as root?



[mongod@xyz-qc-a1s mongo]$ pip install --no-index --find-links /u01/mongodb/mongo-connector/app/home/mradmin/mongo/ mongo-connector

Ignoring indexes: https://pypi.python.org/simple

Collecting mongo-connector

Collecting pymongo>=2.9 (from mongo-connector)

Collecting pysolr>=3.1.0 (from mongo-connector)

Collecting requests>=2.0 (from pysolr>=3.1.0->mongo-connector)

Installing collected packages: pymongo, requests, pysolr, mongo-connector

  Running setup.py install for pymongo

    Complete output from command /opt/rh/python27/root/usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-K146cO/pymongo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3rRJEL-record/install-record.txt --single-version-externally-managed --compile:

    running install

    running build

    running build_py

    creating build

    creating build/lib.linux-x86_64-2.7

    creating build/lib.linux-x86_64-2.7/bson

    copying bson/code.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/errors.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/json_util.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/objectid.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/dbref.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/timestamp.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/raw_bson.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/regex.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/__init__.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/min_key.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/tz_util.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/codec_options.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/max_key.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/son.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/binary.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/int64.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/py3compat.py -> build/lib.linux-x86_64-2.7/bson

    creating build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server_description.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server_type.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/bulk.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/thread_util.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/operations.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/monitor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/uri_parser.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server_selectors.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/pool.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/errors.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/mongo_replica_set_client.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/database.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/read_preferences.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ssl_context.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ssl_match_hostname.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/write_concern.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/monotonic.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/cursor_manager.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/message.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/command_cursor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/cursor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/collection.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/response.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/son_manipulator.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ssl_support.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/__init__.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/common.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/helpers.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/mongo_client.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/monitoring.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/results.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ismaster.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/client_options.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/topology_description.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/auth.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/network.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/periodic_executor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/settings.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/read_concern.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/topology.py -> build/lib.linux-x86_64-2.7/pymongo

    creating build/lib.linux-x86_64-2.7/gridfs

    copying gridfs/errors.py -> build/lib.linux-x86_64-2.7/gridfs

    copying gridfs/__init__.py -> build/lib.linux-x86_64-2.7/gridfs

    copying gridfs/grid_file.py -> build/lib.linux-x86_64-2.7/gridfs

    running build_ext

    building 'bson._cbson' extension

    creating build/temp.linux-x86_64-2.7

    creating build/temp.linux-x86_64-2.7/bson

    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ibson -I/opt/rh/python27/root/usr/include/python2.7 -c bson/_cbsonmodule.c -o build/temp.linux-x86_64-2.7/bson/_cbsonmodule.o

    bson/_cbsonmodule.c:23:20: fatal error: Python.h: No such file or directory

     #include "Python.h"

                        ^

    compilation terminated.

    /tmp/pip-build-K146cO/pymongo/setup.py:225: UserWarning:

    ********************************************************************

    WARNING: The bson._cbson extension module could not

    be compiled. No C extensions are essential for PyMongo to run,

    although they do result in significant speed improvements.

    The output above this warning shows how the compilation failed.



    Please see the installation docs for solutions to build issues:



    http://api.mongodb.org/python/current/installation.html



    Here are some hints for popular operating systems:



    If you are seeing this message on Linux you probably need to

    install GCC and/or the Python development package for your

    version of Python.



    Debian and Ubuntu users should issue the following command:



        $ sudo apt-get install build-essential python-dev



    Users of Red Hat based distributions (RHEL, CentOS, Amazon Linux,

    Oracle Linux, Fedora, etc.) should issue the following command:



        $ sudo yum install gcc python-devel



    If you are seeing this message on Microsoft Windows please install

    PyMongo using the MS Windows installer for your version of Python,

    available on pypi here:



    http://pypi.python.org/pypi/pymongo/#downloads



    If you are seeing this message on OSX please read the documentation

    here:



    http://api.mongodb.org/python/current/installation.html#osx

    ********************************************************************



      "The output above "

    command 'gcc' failed with exit status 1

    building 'pymongo._cmessage' extension

    creating build/temp.linux-x86_64-2.7/pymongo

    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ibson -I/opt/rh/python27/root/usr/include/python2.7 -c pymongo/_cmessagemodule.c -o build/temp.linux-x86_64-2.7/pymongo/_cmessagemodule.o

    pymongo/_cmessagemodule.c:23:20: fatal error: Python.h: No such file or directory

     #include "Python.h"

                        ^

    compilation terminated.

    /tmp/pip-build-K146cO/pymongo/setup.py:225: UserWarning:

    ********************************************************************

    WARNING: The pymongo._cmessage extension module could not

    be compiled. No C extensions are essential for PyMongo to run,

    although they do result in significant speed improvements.

    The output above this warning shows how the compilation failed.



    Please see the installation docs for solutions to build issues:



    http://api.mongodb.org/python/current/installation.html



    Here are some hints for popular operating systems:



    If you are seeing this message on Linux you probably need to

    install GCC and/or the Python development package for your

    version of Python.



    Debian and Ubuntu users should issue the following command:



        $ sudo apt-get install build-essential python-dev



    Users of Red Hat based distributions (RHEL, CentOS, Amazon Linux,

    Oracle Linux, Fedora, etc.) should issue the following command:



        $ sudo yum install gcc python-devel



    If you are seeing this message on Microsoft Windows please install

    PyMongo using the MS Windows installer for your version of Python,

    available on pypi here:



    http://pypi.python.org/pypi/pymongo/#downloads



    If you are seeing this message on OSX please read the documentation

    here:



    http://api.mongodb.org/python/current/installation.html#osx

    ********************************************************************



      "The output above "

    command 'gcc' failed with exit status 1

    running install_lib

    creating /opt/rh/python27/root/usr/lib64/python2.7/site-packages/bson

    error: could not create '/opt/rh/python27/root/usr/lib64/python2.7/site-packages/bson': Permission denied



    ----------------------------------------

Command "/opt/rh/python27/root/usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-K146cO/pymongo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3rRJEL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-K146cO/pymongo

[mongod@xyz-qc-a1s mongo]$

From: Sudheer KantaReddy <sudheer_kantareddy2@cable.comcast.com<mailto:sudheer_kantareddy2@cable.comcast.com>>
Date: Monday, May 9, 2016 at 3:32 PM
To: mongodb-labs/mongo-connector <reply@reply.github.com<mailto:reply@reply.github.com>>, mongodb-labs/mongo-connector <mongo-connector@noreply.github.com<mailto:mongo-connector@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [mongodb-labs/mongo-connector] Installing mongo-connector on a system with no internet access (#429)

For some reason we are not able to install pip on our VM.

Operation System : CentOS Linux release 7.0.1406

Thanks
Sudheer

**Comment by skanta200** [comment]
I installed as root and it says successful but when I try to use, we are getting some errors. Please help:


[root@ombomdb-qc-a1s mongo-connector]# pip install --no-index --find-links /u01/mongodb/mongo-connector/app/home/mradmin/mongo/ mongo-connector

Ignoring indexes: https://pypi.python.org/simple

Collecting mongo-connector

Collecting pymongo>=2.9 (from mongo-connector)

Collecting pysolr>=3.1.0 (from mongo-connector)

Collecting requests>=2.0 (from pysolr>=3.1.0->mongo-connector)

Installing collected packages: pymongo, requests, pysolr, mongo-connector

  Running setup.py install for pymongo

Successfully installed mongo-connector-2.3 pymongo-3.2.2 pysolr-3.4.0 requests-2.10.0

[root@ombomdb-qc-a1s mongo-connector]#



But when I try to use, I got the following error:



[mongod@ombomdb-qc-a1s pymongo-3.2.2]$ mongo-connector

Traceback (most recent call last):

  File "/usr/bin/mongo-connector", line 5, in <module>

    from pkg_resources import load_entry_point

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>

    working_set.require(__requires__)

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require

    needed = self.resolve(parse_requirements(requirements))

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: pysolr>=3.1.0

[mongod@ombomdb-qc-a1s pymongo-3.2.2]$



Thanks

Sudheer

From: Sudheer KantaReddy <sudheer_kantareddy2@cable.comcast.com<mailto:sudheer_kantareddy2@cable.comcast.com>>
Date: Tuesday, May 10, 2016 at 10:47 AM
To: mongodb-labs/mongo-connector <reply@reply.github.com<mailto:reply@reply.github.com>>, mongodb-labs/mongo-connector <mongo-connector@noreply.github.com<mailto:mongo-connector@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [mongodb-labs/mongo-connector] Installing mongo-connector on a system with no internet access (#429)

I tried offline install and I am getting the following permission error. Do we have to run this command as root?



[mongod@xyz-qc-a1s mongo]$ pip install --no-index --find-links /u01/mongodb/mongo-connector/app/home/mradmin/mongo/ mongo-connector

Ignoring indexes: https://pypi.python.org/simple

Collecting mongo-connector

Collecting pymongo>=2.9 (from mongo-connector)

Collecting pysolr>=3.1.0 (from mongo-connector)

Collecting requests>=2.0 (from pysolr>=3.1.0->mongo-connector)

Installing collected packages: pymongo, requests, pysolr, mongo-connector

  Running setup.py install for pymongo

    Complete output from command /opt/rh/python27/root/usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-K146cO/pymongo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3rRJEL-record/install-record.txt --single-version-externally-managed --compile:

    running install

    running build

    running build_py

    creating build

    creating build/lib.linux-x86_64-2.7

    creating build/lib.linux-x86_64-2.7/bson

    copying bson/code.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/errors.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/json_util.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/objectid.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/dbref.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/timestamp.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/raw_bson.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/regex.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/__init__.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/min_key.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/tz_util.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/codec_options.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/max_key.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/son.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/binary.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/int64.py -> build/lib.linux-x86_64-2.7/bson

    copying bson/py3compat.py -> build/lib.linux-x86_64-2.7/bson

    creating build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server_description.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server_type.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/bulk.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/thread_util.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/operations.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/monitor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/uri_parser.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server_selectors.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/pool.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/errors.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/mongo_replica_set_client.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/database.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/server.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/read_preferences.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ssl_context.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ssl_match_hostname.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/write_concern.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/monotonic.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/cursor_manager.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/message.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/command_cursor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/cursor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/collection.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/response.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/son_manipulator.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ssl_support.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/__init__.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/common.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/helpers.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/mongo_client.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/monitoring.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/results.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/ismaster.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/client_options.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/topology_description.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/auth.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/network.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/periodic_executor.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/settings.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/read_concern.py -> build/lib.linux-x86_64-2.7/pymongo

    copying pymongo/topology.py -> build/lib.linux-x86_64-2.7/pymongo

    creating build/lib.linux-x86_64-2.7/gridfs

    copying gridfs/errors.py -> build/lib.linux-x86_64-2.7/gridfs

    copying gridfs/__init__.py -> build/lib.linux-x86_64-2.7/gridfs

    copying gridfs/grid_file.py -> build/lib.linux-x86_64-2.7/gridfs

    running build_ext

    building 'bson._cbson' extension

    creating build/temp.linux-x86_64-2.7

    creating build/temp.linux-x86_64-2.7/bson

    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ibson -I/opt/rh/python27/root/usr/include/python2.7 -c bson/_cbsonmodule.c -o build/temp.linux-x86_64-2.7/bson/_cbsonmodule.o

    bson/_cbsonmodule.c:23:20: fatal error: Python.h: No such file or directory

     #include "Python.h"

                        ^

    compilation terminated.

    /tmp/pip-build-K146cO/pymongo/setup.py:225: UserWarning:

    ********************************************************************

    WARNING: The bson._cbson extension module could not

    be compiled. No C extensions are essential for PyMongo to run,

    although they do result in significant speed improvements.

    The output above this warning shows how the compilation failed.



    Please see the installation docs for solutions to build issues:



    http://api.mongodb.org/python/current/installation.html



    Here are some hints for popular operating systems:



    If you are seeing this message on Linux you probably need to

    install GCC and/or the Python development package for your

    version of Python.



    Debian and Ubuntu users should issue the following command:



        $ sudo apt-get install build-essential python-dev



    Users of Red Hat based distributions (RHEL, CentOS, Amazon Linux,

    Oracle Linux, Fedora, etc.) should issue the following command:



        $ sudo yum install gcc python-devel



    If you are seeing this message on Microsoft Windows please install

    PyMongo using the MS Windows installer for your version of Python,

    available on pypi here:



    http://pypi.python.org/pypi/pymongo/#downloads



    If you are seeing this message on OSX please read the documentation

    here:



    http://api.mongodb.org/python/current/installation.html#osx

    ********************************************************************



      "The output above "

    command 'gcc' failed with exit status 1

    building 'pymongo._cmessage' extension

    creating build/temp.linux-x86_64-2.7/pymongo

    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ibson -I/opt/rh/python27/root/usr/include/python2.7 -c pymongo/_cmessagemodule.c -o build/temp.linux-x86_64-2.7/pymongo/_cmessagemodule.o

    pymongo/_cmessagemodule.c:23:20: fatal error: Python.h: No such file or directory

     #include "Python.h"

                        ^

    compilation terminated.

    /tmp/pip-build-K146cO/pymongo/setup.py:225: UserWarning:

    ********************************************************************

    WARNING: The pymongo._cmessage extension module could not

    be compiled. No C extensions are essential for PyMongo to run,

    although they do result in significant speed improvements.

    The output above this warning shows how the compilation failed.



    Please see the installation docs for solutions to build issues:



    http://api.mongodb.org/python/current/installation.html



    Here are some hints for popular operating systems:



    If you are seeing this message on Linux you probably need to

    install GCC and/or the Python development package for your

    version of Python.



    Debian and Ubuntu users should issue the following command:



        $ sudo apt-get install build-essential python-dev



    Users of Red Hat based distributions (RHEL, CentOS, Amazon Linux,

    Oracle Linux, Fedora, etc.) should issue the following command:



        $ sudo yum install gcc python-devel



    If you are seeing this message on Microsoft Windows please install

    PyMongo using the MS Windows installer for your version of Python,

    available on pypi here:



    http://pypi.python.org/pypi/pymongo/#downloads



    If you are seeing this message on OSX please read the documentation

    here:



    http://api.mongodb.org/python/current/installation.html#osx

    ********************************************************************



      "The output above "

    command 'gcc' failed with exit status 1

    running install_lib

    creating /opt/rh/python27/root/usr/lib64/python2.7/site-packages/bson

    error: could not create '/opt/rh/python27/root/usr/lib64/python2.7/site-packages/bson': Permission denied



    ----------------------------------------

Command "/opt/rh/python27/root/usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-K146cO/pymongo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3rRJEL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-K146cO/pymongo

[mongod@xyz-qc-a1s mongo]$

From: Sudheer KantaReddy <sudheer_kantareddy2@cable.comcast.com<mailto:sudheer_kantareddy2@cable.comcast.com>>
Date: Monday, May 9, 2016 at 3:32 PM
To: mongodb-labs/mongo-connector <reply@reply.github.com<mailto:reply@reply.github.com>>, mongodb-labs/mongo-connector <mongo-connector@noreply.github.com<mailto:mongo-connector@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [mongodb-labs/mongo-connector] Installing mongo-connector on a system with no internet access (#429)

For some reason we are not able to install pip on our VM.

Operation System : CentOS Linux release 7.0.1406

Thanks
Sudheer

**Comment by aherlihy** [comment]
It's probably a permissions issue since you are installing it as a root but then trying to run it as a different user. You can either run mongo-connector as root, install a python for Mongo-Connector, or install mongo-connector into a specific directory using [--target](https://pip.pypa.io/en/stable/reference/pip_install/?highlight=target#cmdoption--target) and then add that python directory to your PYTHONPATH so you know exactly where it is. 

Another option is to use virtual environments.

**Comment by skanta200** [comment]
I tried mongo-connector as root and still got the same error


root@ombomdb-qc-a1s ~]# mongo-connector

Traceback (most recent call last):

  File "/usr/bin/mongo-connector", line 5, in <module>

    from pkg_resources import load_entry_point

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>

    working_set.require(__requires__)

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require

    needed = self.resolve(parse_requirements(requirements))

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: pysolr>=3.1.0

[root@ombomdb-qc-a1s ~]#



Thanks

Sudheer

**Comment by aherlihy** [comment]
Did you try any of the other options mentioned above?

**Comment by skanta200** [comment]
I tried exporting the Python Path , but still the same error

Thanks
Sudheer
