### ISSUE TITLE
bulk_upsert using index name instead of namespace in elastic1/2 doc managers

### ISSUE THREAD

**Issue by AnnaMag** [mongodb-labs/mongo-connector#432]
mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager -n dbart.artobjcoll

Logging to mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 161, in run
    cursor, cursor_len = self.init_cursor()
  File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 617, in init_cursor
    self.checkpoint = self.rollback()
  File "/usr/local/lib/python3.5/site-packages/mongo_connector/oplog_manager.py", line 739, in rollback
    database, coll = original_namespace.split('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by aherlihy** [comment]
Hello! Sorry for the delay in getting back to you.

It seems the elastic2_doc_manager is returning only the database name instead of "database.collection". The issue is happening in the 'rollback' code, so it's hard to reproduce, but we are working on a solution.

Thank you for reporting the bug!

**Comment by aherlihy** [comment]
I've fixed the bug in elastic2-doc-manager and also in elastic-doc-manager. Thank you for helping us track this down! I will include this in the next release, but for now you can get it off master.

[Elastic 2.x fix](https://github.com/mongodb-labs/elastic2-doc-manager/commit/b7042b10b9b5fa9668926a7e3edcad8f5711a44d)

[Elastic 1.x fix](https://github.com/mongodb-labs/elastic-doc-manager/commit/7352afd6e53f5eddf5de2d139a1e8d47ed178540)

**Comment by AnnaMag** [comment]
great!
