### ISSUE TITLE
Do not assume _id is ObjectId

### ISSUE THREAD

**Issue by rectalogic** [mongodb-labs/mongo-connector#443]
OplogThread assumes that _id in the document is an ObjectId [here](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L817) and [here](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L831)

This also assumes the _ids returned by `DocManager.search()` and `DocManager.get_last_doc()` can be coerced to ObjectId.

But mongo does [not require](https://docs.mongodb.org/manual/core/document/#field-names) _id to be ObjectId.

    _id ... may be of any type other than an array

The unit tests don't even assume it is ObjectId. e.g. the [test_solr_doc_manager.p unit tests](https://github.com/mongodb-labs/mongo-connector/blob/master/tests/test_solr_doc_manager.py#L37) for search use the string '1' as the _id.

Most of the existing DocManagers coerce the _id to a string and store that, and return that string in search and get_last_doc and OplogThread attempts to coerce that string to ObjectId. So I think fixing this would require DocManagers to return the original _id instance and not a string.

**Comment by aherlihy** [comment]
Hello!

Are you running into a particular error? What are you trying to accomplish with mongo-connector that would require this change?

**Comment by rectalogic** [comment]
I'm writing a DocManager and noticed test failures during a simulated rollback. We do have tables that use non-ObjectId for _id - they use a SON containing various keys as the _id.

A workaround is to specify a list of collections to include and exclude any that do not use ObjectId as _id in the mongo-connector config.

**Comment by llvtt** [comment]
This is tricky; the `_id` field is coerced into a string for the purposes of storing it in Elastic/Solr, since `ObjectId` is a MongoDB-specific type. However, we have to turn those strings back into whatever their original type was, so that we can query MongoDB. This means we need to know the original type of `_id`, which isn't encoded anywhere. It could even be different types from document to document (insane, perhaps, but possible).

This is obviously a bug, but I'm not sure how big the impact is. I'm guessing that most are using ObjectId as the type for `_id`, since that's the default. Of those people who are using something else, only a fraction might experience a rollback that requires mongo-connector's intervention (and thus hit this bug). The fix for this will require encoding the original type somehow, and will probably require a breaking change. :(

**Comment by behackett** [comment]
It's pretty common for applications to use UUIDs or GUIDs for _id.

**Comment by p-backman-ericsson** [comment]
I think we hit this problem using mongo-connector 2.4.1. We use UUIDs as _id.

```
2016-11-23 19:43:22,230 [ERROR] mongo_connector.util:92 - Fatal Exception
Traceback (most recent call last):
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 199, in run
    cursor, cursor_empty = self.init_cursor()
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 744, in init_cursor
    self.checkpoint = self.rollback()
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 867, in rollback
    bson_obj_id_list = [obj_id(doc['_id']) for doc in doc_list]
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 867, in <listcomp>
    bson_obj_id_list = [obj_id(doc['_id']) for doc in doc_list]
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/eiffel/es/eiseiffel2.es58.3/dist/python/lib/python3.4/site-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: '96d0b1ea-1eb4-4fe2-bcf3-54f3b8d10ad7' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
2016-11-23 19:43:22,977 [ERROR] __main__:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 140098446280448)> unexpectedly stopped! Shutting down
```

Would it be possible to document this limitation in the FAQ or elsewhere?
If conversion to ObjectId fails couldn't you just use _id as a string? Wouldn't that solve a lot of other types used?

**Comment by p-backman-ericsson** [comment]
I think we hit this problem using mongo-connector 2.4.1. We use UUIDs as _id.
```
Traceback (most recent call last):
  File "/usr/.../python3.4/site-packages/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/usr/.../python3.4/site-packages/mongo_connector/oplog_manager.py", line 199, in run
    cursor, cursor_empty = self.init_cursor()
  File "/usr/.../python3.4/site-packages/mongo_connector/oplog_manager.py", line 744, in init_cursor
    self.checkpoint = self.rollback()
  File "/usr/.../python3.4/site-packages/mongo_connector/oplog_manager.py", line 867, in rollback
    bson_obj_id_list = [obj_id(doc['_id']) for doc in doc_list]
  File "/usr/.../python3.4/site-packages/mongo_connector/oplog_manager.py", line 867, in <listcomp>
    bson_obj_id_list = [obj_id(doc['_id']) for doc in doc_list]
  File "/usr/.../python3.4/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/.../python3.4/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/.../python3.4/site-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/.../python3.4/site-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: '96d0b1ea-1eb4-4fe2-bcf3-54f3b8d10ad7' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```
Would it be possible to document this limitation in the FAQ or elsewhere?
If conversion to ObjectId fails couldn't you just use _id as a string as fallback? Wouldn't that solve a lot of other types used?

**Comment by afoninsky** [comment]
We are don't use ObjectId too. Instead we generate own unique id from code (various logic for various business purposes). This is common practice.

Unfortunately, looks like mongo-connector is totally non usable in this case.

**Comment by afoninsky** [comment]
Any updates about this issue? Should i wait for a little, or should i use other sync solution? :(

**Comment by ShaneHarvey** [comment]
I think I have a simple idea that may fix this issue for most use cases without storing the original `_id` type in the target system. What we add a flag/config option that provides another type that `_id` could be decoded to. For example, `--alternate-id-type=uuid` would mean mongo-connector will first try to decode the `_id` as an ObjectId and if that fails it would then try to decode it as a `UUID`.

@afoninsky @rectalogic @Webgardener @llovett thoughts?

**Comment by rectalogic** [comment]
In our case that would need to be configured per-collection, most collections use ObjectId but one uses a bson.SON(). But maybe a per-collection configurable id_encoder/id_decoder would work. And the default would be id_encoder=str and id_decoder=bson.ObjectId - and the encoder is responsible for encoding the _id into some string representation that the decoder can parse back to the original.

**Comment by ShaneHarvey** [comment]
After talking to @llovett, we came up with a much better solution that should fix the problem without requiring any configuration changes or changes to the `_id`s in the target system.

We'll let the DocManager encode the `_id` field as [MongoDB Extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/) with all the proper type information but only in the private meta-collection. The DocManager will then decode the `_id` before giving it back to mongo-connector. This will allow `_id` to be any type and not just ObjectId.

**Comment by ShaneHarvey** [comment]
The fix for this will depend on using the [MongoDB extended JSON](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst) implementation in the upcoming PyMongo 3.5 release: https://jira.mongodb.org/browse/PYTHON-1214

**Comment by benlavalley** [comment]
I was about to post a new issue and figured I'd try my hand at bumping this one.


Running: mongo-connector 3.1.1, Python 3.6.7, PyMongo 3.7.2, source DB MongoDB 4.0, ElasticSearch 5.6.14, on Ubuntu LTS 18.04.

Getting this error in my logs with what I believe to be the the latest version of mongo-connector and Python 3.5x+:

Error:"bson.errors.InvalidId: 'MBZRpS5aFtNKNZzDt' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string"

Full error:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/mongo_connector/util.py", line 107, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mongo_connector/oplog_manager.py", line 217, in run
    cursor, cursor_empty = retry_until_ok(self.init_cursor)
  File "/usr/local/lib/python3.6/dist-packages/mongo_connector/util.py", line 79, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mongo_connector/oplog_manager.py", line 833, in init_cursor
    self.update_checkpoint(self.rollback())
  File "/usr/local/lib/python3.6/dist-packages/mongo_connector/oplog_manager.py", line 954, in rollback
    bson_obj_id_list = [obj_id(doc["_id"]) for doc in doc_list]
  File "/usr/local/lib/python3.6/dist-packages/mongo_connector/oplog_manager.py", line 954, in <listcomp>
    bson_obj_id_list = [obj_id(doc["_id"]) for doc in doc_list]
  File "/usr/local/lib/python3.6/dist-packages/bson/objectid.py", line 125, in __init__
    self.__validate(oid)
  File "/usr/local/lib/python3.6/dist-packages/bson/objectid.py", line 221, in __validate
    _raise_invalid_id(oid)
  File "/usr/local/lib/python3.6/dist-packages/bson/objectid.py", line 67, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: 'MBZRpS5aFtNKNZzDt' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```

```
$ pip3 freeze | grep mongo
mongo-connector==3.1.1
pymongo==3.7.2
```

```
$ python3 -c "import pymongo; print(pymongo.version); print(pymongo.has_c())"
3.7.2
True
```

I tried downgrading to PyMongo 3.5.1 via "pip3 install pymongo==3.5.1" thinking that perhaps something changed recently but that didn't seem to help.
I have installed mongo-connector with "pip3 install 'mongo-connector[elastic5]'" and by cloning it from Git and "running pip3 install ./mongo-connector"

I had mongo-connector humming along nicely before my Mongo 3.6 upgrade where I had to upgrade mongo-connector and install python3 in order to work with the changes in Mongo's oplog. 

Figured I'd post this up as I'm at a loss with this one and hoping I don't have to delve into Python/Pymongo changelogs, code-level analysis, etc. Mongo-connector has been an incredibly useful tool and I'm crossing my fingers this problem is simple enough to sort out :)

**Comment by benlavalley** [comment]
Looking over the code in [oplog_manager.py](https://github.com/yougov/mongo-connector/blob/master/mongo_connector/oplog_manager.py), I see the proposed changes here to encode the _id as extended JSON were never actually implemented (I'd believed they were based on the reply preceding mine thanking llvtt for resolving the problem). 

And thanks for that formatting edit @jaraco, I see you 👍
