### ISSUE TITLE
InvalidBSON: normalized days too large to fit in a C int

### ISSUE THREAD

**Issue by herma88wan** [mongodb-labs/mongo-connector#444]
Hi All, please help, im encounter this error when initializing step of mongo-connector. 

Here is the stacktrace. 

2016-05-09 19:52:29,518 [CRITICAL] mongo_connector.oplog_manager:549 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector-2.3-py2.6.egg/mongo_connector/oplog_manager.py", line 501, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.6/site-packages/mongo_connector-2.3-py2.6.egg/mongo_connector/oplog_manager.py", line 485, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/lib/python2.6/site-packages/mongo_connector-2.3-py2.6.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector-2.3-py2.6.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 292, in bulk_upsert
    for i in range(self.chunk_size))
  File "/usr/lib/python2.6/site-packages/mongo_connector-2.3-py2.6.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 292, in <genexpr>
    for i in range(self.chunk_size))
  File "/usr/lib/python2.6/site-packages/mongo_connector-2.3-py2.6.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 286, in <genexpr>
    cleaned = (self._clean_doc(d, namespace, timestamp) for d in docs)
  File "/usr/lib/python2.6/site-packages/mongo_connector-2.3-py2.6.egg/mongo_connector/oplog_manager.py", line 448, in docs_to_dump
    for doc in cursor:
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 1032, in _refresh
    self.__max_await_time_ms))
  File "build/bdist.linux-x86_64/egg/pymongo/cursor.py", line 903, in __send_message
    codec_options=self.__codec_options)
  File "build/bdist.linux-x86_64/egg/pymongo/helpers.py", line 133, in _unpack_response
    "data": bson.decode_all(response[20:], codec_options)}
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 815, in decode_all
    reraise(InvalidBSON, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 807, in decode_all
    codec_options))
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 344, in _elements_to_dict
    for key, value in _iterate_elements(data, position, obj_end, opts):
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 337, in _iterate_elements
    (key, value, position) = _element_to_dict(data, position, obj_end, opts)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 326, in _element_to_dict
    element_name)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 147, in _get_object
    obj = _elements_to_dict(data, position + 4, end, opts)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 344, in _elements_to_dict
    for key, value in _iterate_elements(data, position, obj_end, opts):
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 337, in _iterate_elements
    (key, value, position) = _element_to_dict(data, position, obj_end, opts)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 326, in _element_to_dict
    element_name)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 178, in _get_array
    data, position, obj_end, opts, element_name)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 147, in _get_object
    obj = _elements_to_dict(data, position + 4, end, opts)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 344, in _elements_to_dict
    for key, value in _iterate_elements(data, position, obj_end, opts):
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 337, in _iterate_elements
    (key, value, position) = _element_to_dict(data, position, obj_end, opts)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 326, in _element_to_dict
    element_name)
  File "build/bdist.linux-x86_64/egg/bson/__init__.py", line 243, in _get_date
    seconds=seconds, microseconds=micros)
InvalidBSON: normalized days too large to fit in a C int
2016-05-09 19:52:29,524 [ERROR] mongo_connector.oplog_manager:557 - OplogThread: Failed during dump collection cannot recover!

**Comment by behackett** [comment]
This is a limitation of Python's datetime module. You may be able to work around it by reinstalling PyMongo *with* its C extensions.

https://api.mongodb.com/python/current/installation.html#dependencies-for-installing-c-extensions-on-unix

**Comment by herma88wan** [comment]
thankyou so much @behackett  currently the version of pymongo we are using is 2.1.0. I think it's far behind. Will try your suggestion on reinstally the pyMongo.
