### ISSUE TITLE
GridFS and ElasticSearch usage clarification

### ISSUE THREAD

**Issue by ivanpbl** [mongodb-labs/mongo-connector#447]
Hello,
I'm trying to index some pdf files from GridFS collection in ElasticSearch but it appears nothing gets to ES index. I followed these steps from your wiki:

```
curl -XPUT http://localhost:9200/myindex

curl -XPUT http://localhost:9200/myindex/collection.fs/_mapping -d'{
    "fs": {
        "properties": {
            "content": {"type": "attachment"}
}}}'
```

But I got this response form ES:

> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   420  100   333  100    87  20812   5437 --:--:-- --:--:-- --:--:-- 20812{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [fs : {properties={content={type=attachment}}}]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [fs : {properties={content={type=attachment}}}]"},"status":400}

So the mapping doesn't succeed.

When I tried mapping like this:
```
curl -XPOST localhost:9200/myindex -d'
{
  "mappings": {
      "fs": {
        "properties": {
           "content": { "type": "attachment" }
 }}}}'
```
the index and mapping were created but no files were imported to ES after putting them into GridFS.

This is the resulting mapping document:
`{"myindex":{"aliases":{},"mappings":{"fs":{"properties":{"content":{"type":"attachment","fields":{"content":{"type":"string"},"author":{"type":"string"},"title":{"type":"string"},"name":{"type":"string"},"date":{"type":"date","format":"strict_date_optional_time||epoch_millis"},"keywords":{"type":"string"},"content_type":{"type":"string"},"content_length":{"type":"integer"},"language":{"type":"string"}}}}}},"settings":{"index":{"creation_date":"1463326301015","uuid":"h4mZeX26SiGs3oSl3oNbHw","number_of_replicas":"1","number_of_shards":"5","version":{"created":"2010299"}}},"warmers":{}}}`

So my question is - am I doing something wrong or missing some steps?

My tools' versions are:
elasticsearch-2.1.2
mongodb-3,2,6
mongo_connector-2.3
elasticsearch-mapper-attachments-3.1.2

**Comment by mallegrini** [comment]
+1

**Comment by amjustin13** [comment]
I am having the same problem. @ivanpbl were you able to solve the problem? 

Thanks, 
AJ

**Comment by jicro** [comment]
I have the similar problem. I have a field with type "String", and it stores a date like '2017-02-03', but the connector deals it with a 'Date' type, and then throws an exception.
The exception is:
`2017-03-23 20:03:01,069 [ERROR] mongo_connector.doc_managers.elastic2_doc_manager:491 - Bulk request failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 484, in send_buffered_operations
    successes, errors = bulk(self.elastic, action_buffer)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 190, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'doc_info', u'_id': u'575fc5ef68b2c57d488fdadc', u'error': {u'caused_by': {u'reason': u'mapper [factors.word] of different type, current_type [string], merged_type [date]', u'type': u'illegal_argument_exception'}, u'reason': u'failed to parse', u'type': u'mapper_parsing_exception'}, u'_index': u'dataBaseName'}}])`

The source data is:
`{
            "position" : {
                "senId" : NumberInt(1), 
                "paraId" : NumberInt(2)
            }, 
            "word" : "2016-09-08", 
            "update_time" : ISODate("2016-09-09T16:58:02.573+0800"), 
            "type" : NumberInt(4), 
            "user" : "webdev1"
        }, `

**Comment by zhaojiexi** [comment]
I also met this problem, have you solved it?
