### ISSUE TITLE
Process doesn't exit after fatal exception

### ISSUE THREAD

**Issue by quintstoffers** [mongodb-labs/mongo-connector#451]
I'm running mongo-connector in a Docker container, and it seems like the process doesn't exit when it encounters a fatal exception. Because of this the container doesn't automatically restart, meaning my MongoDB and ElasticSearch aren't synced until I manually restart.

The container does restart properly when I don't pass some required parameters (such as the MongoDB URL), so it seems like some exceptions do cause the process to exit, but others don't.

Here's the exception that occurs before the process hangs. The process doesn't print anything after this, nor does it sync anything.
```
[mongo-connector-1]2016-05-20T12:11:32.329932128Z 2016-05-20 12:11:32,314 [ERROR] mongo_connector.util:87 - Fatal Exception 
[mongo-connector-1]2016-05-20T12:11:32.329935834Z Traceback (most recent call last): 
[mongo-connector-1]2016-05-20T12:11:32.329939647Z   File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 385, in _make_request 
[mongo-connector-1]2016-05-20T12:11:32.329943392Z     httplib_response = conn.getresponse(buffering=True) 
[mongo-connector-1]2016-05-20T12:11:32.329946700Z TypeError: getresponse() got an unexpected keyword argument 'buffering' 
[mongo-connector-1]2016-05-20T12:11:32.329950152Z  
[mongo-connector-1]2016-05-20T12:11:32.329953470Z During handling of the above exception, another exception occurred: 
[mongo-connector-1]2016-05-20T12:11:32.329956872Z  
[mongo-connector-1]2016-05-20T12:11:32.329960082Z Traceback (most recent call last): 
[mongo-connector-1]2016-05-20T12:11:32.329964337Z   File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 387, in _make_request 
[mongo-connector-1]2016-05-20T12:11:32.329967784Z     httplib_response = conn.getresponse() 
[mongo-connector-1]2016-05-20T12:11:32.329971009Z   File "/usr/local/lib/python3.4/http/client.py", line 1227, in getresponse 
[mongo-connector-1]2016-05-20T12:11:32.329976754Z     response.begin() 
[mongo-connector-1]2016-05-20T12:11:32.329980198Z   File "/usr/local/lib/python3.4/http/client.py", line 386, in begin 
[mongo-connector-1]2016-05-20T12:11:32.329983688Z     version, status, reason = self._read_status() 
[mongo-connector-1]2016-05-20T12:11:32.329987148Z   File "/usr/local/lib/python3.4/http/client.py", line 348, in _read_status 
[mongo-connector-1]2016-05-20T12:11:32.329991069Z     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") 
[mongo-connector-1]2016-05-20T12:11:32.329994673Z   File "/usr/local/lib/python3.4/socket.py", line 378, in readinto 
[mongo-connector-1]2016-05-20T12:11:32.329998165Z     return self._sock.recv_into(b) 
[mongo-connector-1]2016-05-20T12:11:32.330001603Z   File "/usr/local/lib/python3.4/ssl.py", line 748, in recv_into 
[mongo-connector-1]2016-05-20T12:11:32.330005153Z     return self.read(nbytes, buffer) 
[mongo-connector-1]2016-05-20T12:11:32.330008468Z   File "/usr/local/lib/python3.4/ssl.py", line 620, in read 
[mongo-connector-1]2016-05-20T12:11:32.330012106Z     v = self._sslobj.read(len, buffer) 
[mongo-connector-1]2016-05-20T12:11:32.330015388Z socket.timeout: The read operation timed out 
[mongo-connector-1]2016-05-20T12:11:32.330018681Z  
[mongo-connector-1]2016-05-20T12:11:32.330022087Z During handling of the above exception, another exception occurred: 
[mongo-connector-1]2016-05-20T12:11:32.330025402Z  
[mongo-connector-1]2016-05-20T12:11:32.330028622Z Traceback (most recent call last): 
[mongo-connector-1]2016-05-20T12:11:32.330032443Z   File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request 
[mongo-connector-1]2016-05-20T12:11:32.330036472Z     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw) 
[mongo-connector-1]2016-05-20T12:11:32.330040082Z   File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 623, in urlopen 
[mongo-connector-1]2016-05-20T12:11:32.330043575Z     _stacktrace=sys.exc_info()[2]) 
[mongo-connector-1]2016-05-20T12:11:32.330047077Z   File "/usr/local/lib/python3.4/site-packages/urllib3/util/retry.py", line 232, in increment 
[mongo-connector-1]2016-05-20T12:11:32.330050629Z     raise six.reraise(type(error), error, _stacktrace) 
[mongo-connector-1]2016-05-20T12:11:32.330053961Z   File "/usr/local/lib/python3.4/site-packages/urllib3/packages/six.py", line 310, in reraise 
[mongo-connector-1]2016-05-20T12:11:32.330057537Z     raise value 
[mongo-connector-1]2016-05-20T12:11:32.330060866Z   File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 578, in urlopen 
[mongo-connector-1]2016-05-20T12:11:32.330064424Z     chunked=chunked) 
[mongo-connector-1]2016-05-20T12:11:32.330067639Z   File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 389, in _make_request 
[mongo-connector-1]2016-05-20T12:11:32.330071241Z     self._raise_timeout(err=e, url=url, timeout_value=read_timeout) 
[mongo-connector-1]2016-05-20T12:11:32.330074724Z   File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 314, in _raise_timeout 
[mongo-connector-1]2016-05-20T12:11:32.330078348Z     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value) 
[mongo-connector-1]2016-05-20T12:11:32.330082184Z urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='REDACTED', port=11087): Read timed out. (read timeout=10) 
[mongo-connector-1]2016-05-20T12:11:32.330088026Z  
[mongo-connector-1]2016-05-20T12:11:32.330091505Z During handling of the above exception, another exception occurred: 
[mongo-connector-1]2016-05-20T12:11:32.330094919Z  
[mongo-connector-1]2016-05-20T12:11:32.330098034Z Traceback (most recent call last): 
[mongo-connector-1]2016-05-20T12:11:32.330101233Z   File "/usr/local/lib/python3.4/site-packages/mongo_connector/util.py", line 85, in wrapped 
[mongo-connector-1]2016-05-20T12:11:32.330104678Z     func(*args, **kwargs) 
[mongo-connector-1]2016-05-20T12:11:32.330107933Z   File "/usr/local/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 268, in run 
[mongo-connector-1]2016-05-20T12:11:32.330111398Z     ns, timestamp) 
[mongo-connector-1]2016-05-20T12:11:32.330115180Z   File "/usr/local/lib/python3.4/site-packages/mongo_connector/util.py", line 32, in wrapped 
[mongo-connector-1]2016-05-20T12:11:32.330118668Z     return f(*args, **kwargs) 
[mongo-connector-1]2016-05-20T12:11:32.330121962Z   File "/usr/local/lib/python3.4/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 122, in update 
[mongo-connector-1]2016-05-20T12:11:32.330125834Z     id=u(document_id)) 
[mongo-connector-1]2016-05-20T12:11:32.330129173Z   File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped 
[mongo-connector-1]2016-05-20T12:11:32.330132624Z     return func(*args, params=params, **kwargs) 
[mongo-connector-1]2016-05-20T12:11:32.330135990Z   File "/usr/local/lib/python3.4/site-packages/elasticsearch/client/__init__.py", line 330, in get 
[mongo-connector-1]2016-05-20T12:11:32.330139525Z     doc_type, id), params=params) 
[mongo-connector-1]2016-05-20T12:11:32.330142777Z   File "/usr/local/lib/python3.4/site-packages/elasticsearch/transport.py", line 307, in perform_request 
[mongo-connector-1]2016-05-20T12:11:32.330146292Z     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout) 
[mongo-connector-1]2016-05-20T12:11:32.330149674Z   File "/usr/local/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 86, in perform_request 
[mongo-connector-1]2016-05-20T12:11:32.330153184Z     raise ConnectionTimeout('TIMEOUT', str(e), e) 
[mongo-connector-1]2016-05-20T12:11:32.330502705Z elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPSConnectionPool(host='REDACTED', port=11087): Read timed out. (read timeout=10))
```

EDIT: To clarify, using `mongo-connector` 2.3 and the latest `elastic_doc_manager` for Elastic 1.x.

**Comment by llvtt** [comment]
Just to clarify-- Is this printed continuously in a loop, or does this print and then nothing ever happens after?

Is there anything in mongo-connector's log?

**Comment by pdspicer** [comment]
I discovered something similar after looking through related issues (#383, #402), my thought was that only checking the .running property for OplogThreads and not .is_alive() in connector.py causes this behavior. Some initial testing has confirmed this, and I've put in a pull request (#468) to address this and the other two issues

**Comment by quintstoffers** [comment]
@llvtt This is mongo-connector's log, outputted to stdout (and captured from the output of the docker container). It absolutely hangs, no infinite loops going on.

@pdspicer My python skills aren't good enough to judge the code, but it does seem like that could fix the issue I'm seeing. It would be great if someone more knowledgable could have a look!

**Comment by llvtt** [comment]
@quintstoffers, I just accepted @pdspicer 's patch. Would you mind seeing if the latest version from the master branch resolves this issue for you?

**Comment by quintstoffers** [comment]
Since upping the timeout I'm not seeing this very often anymore, but I'll update the container to use the current master and report back once I notice it (not) restarting.

**Comment by llvtt** [comment]
I haven't heard any complaints since merging the fix from @pdspicer, so I'm going to assume for now that this issue has gone away. Please feel free to report a bug if this happens again.
