### ISSUE TITLE
update oplog  process throw exception

### ISSUE THREAD

**Issue by northlandsnow** [mongodb-labs/mongo-connector#473]
Mongo-connector throw a exception when process some oplogs as below:
`
{
	"ts" : Timestamp(1465903002, 3),
	"h" : NumberLong("951619352658186131"),
	"v" : 2,
	"op" : "u",
	"ns" : "qing-base-service.wxusers",
	"o2" : {
		"_id" : ObjectId("56ff4c0a02dc8746418c39a0")
	},
	"o" : {
		"$set" : {
			"content.2.count" : 2,
			"content.2.date" : null
		}
	}
}
`
the error log:
`
2016-06-14 19:16:42,389 [ERROR] mongo_connector.oplog_manager:318 - Unable to process oplog document {u'h': 951619352658186131L, u'ts': Timestamp(1465903002, 3), u'o': {u'$set': {u'content.2.count': 2, u'content.2.date': None}}, u'v': 2, u'ns': u'qing-base-service.wxusers', u'o2': {u'_id': ObjectId('56ff4c0a02dc8746418c39a0')}, u'op': u'u'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/oplog_manager.py", line 304, in run
    ns, timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elastic2_doc_manager-0.1.0-py2.7.egg/mongo_connector/doc_managers/elastic2_doc_manager.py", line 136, in update
    updated = self.apply_update(document['_source'], update_spec)
  File "/usr/local/lib/python2.7/dist-packages/elastic2_doc_manager-0.1.0-py2.7.egg/mongo_connector/doc_managers/elastic2_doc_manager.py", line 86, in apply_update
    return super(DocManager, self).apply_update(doc, update_spec)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/doc_managers/doc_manager_base.py", line 91, in apply_update
    exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/doc_managers/doc_manager_base.py", line 71, in apply_update
    wl = len(where)
UpdateDoesNotApply: Cannot apply update {u'$set': {u'content.2.count': 2, u'content.2.date': None}} to {u'headimgurl': u'http://wx.qlogo.cn/mmopen/g4SST0Nf32NAtzkDyIqyTREicsfhSTsewCl4hLYdTYov7RbGkjFkQ2Zglo04nldKCYjTWF9CW0I5sR4rwfCyE0LZ2ZpdI8oJk/0', u'sex': u'1', u'subscribe': 1, u'wechat_id': u'gh_55107c7776f7', u'city': u'', u'subscribe_time': u'2015-07-06T05:03:05', u'from': [u'subscribe', u'auth'], u'content': [{u'count': 1, u'from': u'phoneInfo', u'version': u'4.4.2', u'os': u'android', u'tag': u'H60-L02', u'model': u'phone', u'ua': u'Mozilla/5.0 (Linux; Android 4.4.2; H60-L02 Build/HDH60-L02) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile MQQBrowser/6.2 TBS/036523 Safari/537.36 MicroMessenger/6.3.18.800 NetType/WIFI Language/zh_CN'}, None, None, {u'count': 1, u'tag': u'article', u'from': u'appLog'}, {u'count': 1, u'tag': u'nine', u'from': u'appLog'}], u'authTime': u'2016-06-14T11:15:08.792000', u'privilege': [], u'groupid': u'0', u'province': u'', u'openid': u'ow44Et3NZ52D4qTMXOZMcZC_QDW0', u'firstAuthTime': u'2016-06-05T09:52:07.849000', u'appid': u'wx7899ad58eafc44a9', u'nickname': u'\u6600\u9686', u'remark': u'', u'language': u'zh_CN', u'unionid': None, u'__v': 1, u'country': u'\u4e2d\u56fd', u'createdTime': u'2016-04-02T04:35:18.289000'}
2016-06-14 19:18:01,828 [ERROR] mongo_connector.oplog_manager:318 - Unable to process oplog document {u'h': 7015697349301976388L, u'ts': Timestamp(1465903081, 2), u'o': {u'$set': {u'content.2.count': 3}}, u'v': 2, u'ns': u'qing-base-service.wxusers', u'o2': {u'_id': ObjectId('56ff4c0902dc8746418c2e9e')}, u'op': u'u'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/oplog_manager.py", line 304, in run
    ns, timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elastic2_doc_manager-0.1.0-py2.7.egg/mongo_connector/doc_managers/elastic2_doc_manager.py", line 136, in update
    updated = self.apply_update(document['_source'], update_spec)
  File "/usr/local/lib/python2.7/dist-packages/elastic2_doc_manager-0.1.0-py2.7.egg/mongo_connector/doc_managers/elastic2_doc_manager.py", line 86, in apply_update
    return super(DocManager, self).apply_update(doc, update_spec)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/doc_managers/doc_manager_base.py", line 91, in apply_update
    exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/doc_managers/doc_manager_base.py", line 71, in apply_update
    wl = len(where)
UpdateDoesNotApply: Cannot apply update {u'$set': {u'content.2.count': 3}} to {u'headimgurl': u'http://wx.qlogo.cn/mmopen/Rl9ZticcOxxiaNl4FEGGpqba4pcSg8suZ9LmqC9JRRbfAmtMTeoNKLicZ8hY2c7TDMia3OR3VwyyNYlOzXEEkK4icMwV7B8s0IOcv/0', u'sex': u'1', u'subscribe': 1, u'wechat_id': u'gh_55107c7776f7', u'city': u'\u5927\u8fde', u'subscribe_time': u'2015-09-15T02:41:56', u'from': [u'subscribe', u'auth'], u'content': [{u'count': 1, u'from': u'phoneInfo', u'version': u'9.3.2', u'os': u'ios', u'tag': u'iphone', u'model': u'phone', u'ua': u'Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 MicroMessenger/6.3.13 NetType/WIFI Language/zh_CN'}, None, None, {u'count': 1, u'tag': u'article', u'from': u'appLog'}, {u'count': 1, u'tag': u'nine', u'from': u'appLog'}], u'authTime': u'2016-06-05T12:27:32.576000', u'privilege': [], u'groupid': u'0', u'province': u'\u8fbd\u5b81', u'openid': u'ow44EtylYU0NSoAnXEhAxJLuRdFo', u'firstAuthTime': u'2016-06-05T12:27:32.576000', u'appid': u'wx7899ad58eafc44a9', u'nickname': u'\u84dd\u8272\u6d77\u6d0b', u'remark': u'', u'language': u'zh_CN', u'unionid': None, u'__v': 1, u'country': u'\u4e2d\u56fd', u'createdTime': u'2016-04-02T04:35:18.280000'}
2016-06-14 19:40:12,721 [ERROR] mongo_connector.oplog_manager:318 - Unable to process oplog document {u'h': -2596747296935320919L, u'ts': Timestamp(1465904412, 4), u'o': {u'$set': {u'content.6.date': u'20160614', u'content.6.count': 4}}, u'v': 2, u'ns': u'qing-base-service.wxusers', u'o2': {u'_id': ObjectId('5747a3d0652c3fa9a1ee89ae')}, u'op': u'u'}
`

**Comment by zy1989** [comment]
I got the same problem
It seem like only update operation would throw this error.

My configuration
Mongo 3.0.6
elasticsearch 1.4.5
elasticsearch-analysis-ik 1.2.6
mongo-connector with Elastic 1.x 
mongo-connector -m remote:27017 -t localhost:9200 -d elastic_doc_manager --auto-commit-interval=0 -o mongo-connector.oplog --admin-username xxx --password xxx -n collection --no-dump
