### ISSUE TITLE
mongo-connector stuck in "Logging to mongo-connector.log."

### ISSUE THREAD

**Issue by 001balance** [mongodb-labs/mongo-connector#481]
I'm new to Mongo-connector and Solr, I followed the steps provided : https://github.com/mongodb-labs/mongo-connector/wiki/Getting-Started , however in the terminal I only get one line: "Logging to mongo-connector.log." and it gets stuck in there.
Any idea why that happens and how to fix that please ?
Thank you

**Comment by rohandodeja** [comment]
I am also facing this issue.

**Comment by hungvotrung** [comment]
You can enable the log level to 3 or verbose, then it will tell you more detail.

**Comment by 001balance** [comment]
how can I do that please ? 
I went to the file containing mongo-connector ( c:\Python27\Scripts) and it contains a new TIMESTAMP file named oplog which has only one entry : ["myrs", 6301159082740940801] , myrs is the name of my replicaSet in MongoDB, so does that give an idea where things went wrong ?

**Comment by llvtt** [comment]
This issue is too generic to be addressed; we'll need to create new issues to address specific problems. The message "Logging to mongo-connector.log" means messages of any significance will be sent to the file called "mongo-connector.log". This is completely normal behavior. If you believe you are having an issue, please create a new issue and make sure to include the contents of this file, which will have more details on what is going wrong.

As @hungvotrung noted above, you can increase the verbosity of the log file like this: https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#verbosity

**Comment by 001balance** [comment]
If I may, the problem is that it doesn't display anything in the command line other than "Logging to mongo-connector.log" however  the file called "mongo-connector.log" is empty and it doesn't change even after several minutes of execution. 
I suppose this can be qualified as an issue (there are others facing the same problem as well) knowing that I followed all the steps provided in your documentation, but I can't provide further details since the log file is empty which is an abnormal behaviour. 
Is there a solution please ?

**Comment by ty-me** [comment]
Same issue I faced. Nothing in mongo-connector.log file.

**Comment by jayendra13** [comment]
I am facing the same issue. My `mongo-connector` version is `2.5.1`. The operating system I am using is `Ubuntu-16`. I have started the mongo server in replica-set mode with the command `sudo mongod --replSet myDevReplSet`.

```
$ mongo-connector --version
mongo-connector version: 2.5.1
```
I have tried the following ways to increase the verbosity of log, but none of them worked. In my case too mongo-connector hung without any indication in error log.

```
$ mongo-connector --verbose 3 --unique-key=id -n solr_test.films -m localhost:27017 -t http://localhost:8983/solr/films -d solr_doc_manager
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 1275, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/config.py", line 106, in parse_args
    + ', '.join(args))
mongo_connector.errors.InvalidConfiguration: The following command line arguments are not recognized: 3
```

```
$ mongo-connector -v 3 --unique-key=id -n solr_test.films -m localhost:27017 -t http://localhost:8983/solr/films -d solr_doc_manager
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 1275, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/config.py", line 106, in parse_args
    + ', '.join(args))
mongo_connector.errors.InvalidConfiguration: The following command line arguments are not recognized: 3
```

```
$ mongo-connector --verbose=3 --unique-key=id -n solr_test.films -m localhost:27017 -t http://localhost:8983/solr/films -d solr_doc_manager
Usage: mongo-connector [options]

mongo-connector: error: --verbose option does not take a value
```

```
$ mongo-connector -v=3 --unique-key=id -n solr_test.films -m localhost:27017 -t http://localhost:8983/solr/films -d solr_doc_manager
Usage: mongo-connector [options]

mongo-connector: error: no such option: -=
```

It stucks here without pushing/syncing any data to solr
```
$ mongo-connector --verbose --unique-key=id -n solr_test.films -m localhost:27017 -t http://localhost:8983/solr/films -d solr_doc_manager
Logging to /home/eddie7/mongo-connector.log.
````

Here is the log from `mongo-connector.log`
```
2018-03-15 17:19:20,607 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2018-03-15 17:19:20,607 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609]
2018-03-15 17:19:20,607 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
2018-03-15 17:19:20,607 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.3.0
2018-03-15 17:19:20,610 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.2.18
2018-03-15 17:19:20,611 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.solr_doc_manager version: 0.1.0
2018-03-15 17:19:20,616 [INFO] mongo_connector.oplog_manager:120 - OplogThread: Initializing oplog thread
2018-03-15 17:19:20,617 [INFO] mongo_connector.connector:390 - MongoConnector: Starting connection thread MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=u'myDevReplSet')
2018-03-15 17:19:20,618 [DEBUG] mongo_connector.oplog_manager:194 - OplogThread: Run thread started
2018-03-15 17:19:20,618 [DEBUG] mongo_connector.oplog_manager:196 - OplogThread: Getting cursor
2018-03-15 17:19:20,618 [DEBUG] mongo_connector.oplog_manager:830 - OplogThread: reading last checkpoint as Timestamp(1521109253, 1)
2018-03-15 17:19:20,619 [DEBUG] mongo_connector.oplog_manager:704 - OplogThread: Oldest oplog entry has timestamp Timestamp(1520932472, 1).
2018-03-15 17:19:20,620 [DEBUG] mongo_connector.oplog_manager:217 - OplogThread: about to process new oplog entries
2018-03-15 17:19:20,620 [DEBUG] mongo_connector.oplog_manager:219 - OplogThread: Cursor is still alive and thread is still running.
2018-03-15 17:19:21,620 [DEBUG] mongo_connector.oplog_manager:219 - OplogThread: Cursor is still alive and thread is still running.
```

Here is a `strace`  log if that can be helpful.

```
ps -aux | grep mongo-connector
userx    9351  0.0  0.0  54108  8744 pts/28   S+   17:23   0:00 vim mongo-connector.log
userx   10824  4.7  0.1 745076 35296 pts/19   Sl+  17:31   0:00 /usr/bin/python /usr/local/bin/mongo-connector --verbose --unique-key=id -n solr_test.films -m localhost:27017 -t http://localhost:8983/solr/films -d solr_doc_manager
userx   10904  0.0  0.0  14228   932 pts/30   S+   17:31   0:00 grep --color=auto mongo-connector

$ sudo strace -p 10824
[sudo] password for eddie7: 
strace: Process 10824 attached
select(0, NULL, NULL, NULL, {2, 839525}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {3, 0})     = 0 (Timeout)
```
