### ISSUE TITLE
Did mongo-connector reserved elasticsearch index cache if the index was deleted?

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [mongodb-labs/mongo-connector#496]
Hi,
Recently I upgraded mongo-connector to the newest version for support of `-e EXCLUDE_FIELDS`.

I deleted the older es index for re-indexing. After I typed the command
```
mongo-connector -m 10.10.20.155:27118 -t localhost:9200 -d elastic2_doc_manager -n ask.zd_topic -a usvr_sereader -p XXXXXXXXX --continue-on-error -e pic_urls 
```

Then it raised too many same errors
```
OperationFailed: TransportError(404, u'{"_index":"ask","_type":"zd_topic","_id":"54631758068d39201d000002","found":false}')
2016-07-27 17:17:38,601 [ERROR] mongo_connector.oplog_manager:317 - Unable to process oplog document {u'h': 6187461290046076228L, u'ts': Timestamp(1469611058, 1), u'o': {u'$set': {u'view_num': 156L}}, u'v': 2, u'ns': u'ask.zd_topic', u'o2': {u'_id': ObjectId('56c28d8a7f8b9a422e08e4ec')}, **u'op': u'u'**}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 303, in run
    ns, timestamp)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 135, in update
    id=u(document_id))
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 346, in get
    doc_type, id), params=params)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'{"_index":"ask","_type":"zd_topic","_id":"56c28d8a7f8b9a422e08e4ec","found":false}')
```

It says it could not find the _id when try to do an update.

So I guess if mongo-connector cached a deleted _id?

Thank you for help.

**Comment by ShaneHarvey** [comment]
Hi Morriaty-The-Murderer, thanks for filing this issue. Before we file this as a bug can you confirm that you have deleted the oplog progress file (usually called “oplog.timestamp”) before restarting mongo-connector as instructed under [How to Perform a Re-Sync](https://github.com/mongodb-labs/mongo-connector/wiki/Resyncing%20the%20Connector#how-to-perform-a-re-sync)?

**Comment by Morriaty-The-Murderer** [comment]
Thank you ,@ShaneHarvey.

I delete `oplog.timestamp`, and all goes fine. Sorry for my careless when reading the docs.
