### ISSUE TITLE
MongoConnector throw exception when dumping data to elasticsearch

### ISSUE THREAD

**Issue by happynewday** [mongodb-labs/mongo-connector#501]
I build a test environment to learn how to use mongo-connector to inter-work with elasticsearch. but anytime when i trying to dump a record from mongo to elasticsearch, mongo-connector throw a exception and exit. this failure can be repeated follow below sequence:
- before insert record in mongo, i create the index 'bdtt' in elasticsearch with command:
_curl -XPUT '127.0.0.1:9200/bdtt' -d '{"settings" : {"number_of_shards" : 1 }, "mappings" : {"test" : { "properties" : {"name" : { "type" : "string", "index" : "not_analyzed" } } } } }'_

- then i start mongo-connector with:
_mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager_

- insert a record in mongo replication Primary:
_use bdtt
db.test.insert({"name":"test mongo connector"});_

and the trace log reported by mongo-connector:
2016-08-10 15:55:20,182 [CRITICAL] mongo_connector.oplog_manager:625 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 578, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 562, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 203, in bulk_upsert
    for ok, resp in responses:
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 132, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'2 document(s) failed to index.', [{u'index': {u'status': 404, u'_type': u'mongodb_meta', u'_id': u'57aace5d415162c300b4e5a7', u'error': {u'index': u'mongodb_meta', u'reason': u'no such index', u'type': u'index_not_found_exception', u'resource.id': u'mongodb_meta', u'resource.type': u'index_expression'}, u'_index': u'mongodb_meta'}}, {u'index': {u'status': 404, u'_type': u'mongodb_meta', u'_id': u'57aadb7bb2ec891bc74975a3', u'error': {u'index': u'mongodb_meta', u'reason': u'no such index', u'type': u'index_not_found_exception', u'resource.id': u'mongodb_meta', u'resource.type': u'index_expression'}, u'_index': u'mongodb_meta'}}])
2016-08-10 15:55:20,183 [ERROR] mongo_connector.oplog_manager:633 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=u'shard1'), u'local'), u'oplog.rs')
2016-08-10 15:55:21,163 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140434469525248)> unexpectedly stopped! Shutting down

the versions of each component i use:
mongo-connector:
_---
Metadata-Version: 2.0
Name: mongo-connector
Version: 2.4
Summary: Mongo Connector
Home-page: https://github.com/10gen-labs/mongo-connector
Author: MongoDB, Inc.
Author-email: mongodb-user@googlegroups.com
License: http://www.apache.org/licenses/LICENSE-2.0.html
Location: /usr/lib/python2.7/site-packages
Requires: pymongo, pysolr
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Topic :: Database
  Topic :: Software Development :: Libraries :: Python Modules
  Operating System :: Unix
  Operating System :: MacOS :: MacOS X
  Operating System :: Microsoft :: Windows
  Operating System :: POSIX
Entry-points:
  [console_scripts]
  mongo-connector = mongo_connector.connector:main_

elastic2-doc-manager:
_---
Metadata-Version: 2.0
Name: elastic2-doc-manager
Version: 0.1.0
Summary: Elastic2 plugin for mongo-connector
Home-page: https://github.com/mongodb-labs/elastic2-doc-manager
Author: mongodb
Author-email: mongodb-user@googlegroups.com
Installer: pip
License: Apache License, Version 2.0
Location: /usr/lib/python2.7/site-packages
Requires: mongo-connector, elasticsearch
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Topic :: Database
  Topic :: Software Development :: Libraries :: Python Modules
  Operating System :: Unix
  Operating System :: MacOS :: MacOS X
  Operating System :: Microsoft :: Windows
  Operating System :: POSIX_

elasticsearch: 
_Version: 2.3.5, Build: 90f439f/2016-07-27T10:36:52Z, JVM: 1.8.0_101_

mongo:
_db version v3.2.8
git version: ed70e33130c977bda0024c125b56d159573dbaf0
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64_

python:
_Python 2.7.5_

**Comment by happynewday** [comment]
I tried elastic2-doc-manager unittest later on, and seems all unit test failed with quite same reasons:
_======================================================================
ERROR: test_commands (tests.test_elastic2_doc_manager.TestElasticDocManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 224, in test_commands
    self.elastic_doc.upsert(docs[0], 'test.test2', 1)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 160, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')

======================================================================
ERROR: test_elastic_commit (tests.test_elastic2_doc_manager.TestElasticDocManager)
Test the auto_commit_interval attribute.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 170, in test_elastic_commit
    docman.upsert(docc, *TESTARGS)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 160, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')

======================================================================
ERROR: test_get_last_doc (tests.test_elastic2_doc_manager.TestElasticDocManager)
Test the get_last_doc method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 190, in test_get_last_doc
    base = self.elastic_doc.get_last_doc()
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 311, in get_last_doc
    size=1
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')

======================================================================
ERROR: test_insert_file (tests.test_elastic2_doc_manager.TestElasticDocManager)
Ensure we can properly insert a file into ElasticSearch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 114, in test_insert_file
    MockGridFSFile(docc, test_data), *TESTARGS)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 230, in insert_file
    body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 291, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(400, u'mapper_parsing_exception', u'No handler for type [attachment] declared on field [content]')

======================================================================
ERROR: test_remove (tests.test_elastic2_doc_manager.TestElasticDocManager)
Test the remove method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 87, in test_remove
    self.elastic_doc.upsert(docc, *TESTARGS)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 160, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')

======================================================================
ERROR: test_remove_file (tests.test_elastic2_doc_manager.TestElasticDocManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 134, in test_remove_file
    MockGridFSFile(docc, test_data), *TESTARGS)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 230, in insert_file
    body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 291, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(400, u'mapper_parsing_exception', u'No handler for type [attachment] declared on field [content]')

======================================================================
ERROR: test_search (tests.test_elastic2_doc_manager.TestElasticDocManager)
Test the search method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 148, in test_search
    self.elastic_doc.upsert(docc, 'test.test', 5767301236327972865)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 160, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')

======================================================================
ERROR: test_update (tests.test_elastic2_doc_manager.TestElasticDocManager)
Test the update method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 36, in test_update
    self.elastic_doc.upsert(doc, *TESTARGS)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 160, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')

======================================================================
ERROR: test_upsert (tests.test_elastic2_doc_manager.TestElasticDocManager)
Test the upsert method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_elastic2_doc_manager.py", line 53, in test_upsert
    self.elastic_doc.upsert(docc, *TESTARGS)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "mongo_connector/doc_managers/elastic2_doc_manager.py", line 160, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')

----------------------------------------------------------------------
Ran 10 tests in 3.196s_

**Comment by happynewday** [comment]
I changed debug level to get more log, seems the error is happen due to lack of mongodb_meta index in elasticsearch. I followed every step in page "https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch", am i missed some configuration?
  
2016-08-11 11:47:14,507 [DEBUG] mongo_connector.oplog_manager:229 - OplogThread: Iterating through cursor, document number in this cursor is 0
2016-08-11 11:47:14,508 [DEBUG] mongo_connector.oplog_manager:274 - OplogThread: Operation for this entry is c
2016-08-11 11:47:14,508 [DEBUG] urllib3.util.retry:170 - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-08-11 11:47:14,509 [INFO] urllib3.connectionpool:214 - Starting new HTTP connection (1): localhost
2016-08-11 11:47:14,533 [DEBUG] urllib3.connectionpool:401 - "PUT /bdtt/_mapping/test HTTP/1.1" 200 21
2016-08-11 11:47:14,534 [INFO] elasticsearch:63 - PUT http://localhost:9200/bdtt/_mapping/test [status:200 request:0.025s]
2016-08-11 11:47:14,534 [DEBUG] elasticsearch:65 - > {"_source": {"enabled": true}}
2016-08-11 11:47:14,534 [DEBUG] elasticsearch:66 - < {"acknowledged":true}
2016-08-11 11:47:14,535 [DEBUG] mongo_connector.oplog_manager:327 - OplogThread: Documents removed: 0, inserted: 0, updated: 0 so far
2016-08-11 11:47:14,535 [DEBUG] mongo_connector.oplog_manager:329 - OplogThread: Doc is processed.
2016-08-11 11:47:14,535 [DEBUG] mongo_connector.oplog_manager:229 - OplogThread: Iterating through cursor, document number in this cursor is 1
2016-08-11 11:47:14,535 [DEBUG] mongo_connector.oplog_manager:274 - OplogThread: Operation for this entry is i
2016-08-11 11:47:14,536 [DEBUG] urllib3.util.retry:170 - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
**2016-08-11 11:47:14,563 [DEBUG] urllib3.connectionpool:401 - "PUT /bdtt/test/57abf5422ee47ff27a06edd2?refresh=false HTTP/1.1" 201 141**
2016-08-11 11:47:14,564 [INFO] elasticsearch:63 - PUT http://localhost:9200/bdtt/test/57abf5422ee47ff27a06edd2?refresh=false [status:201 request:0.028s]
2016-08-11 11:47:14,564 [DEBUG] elasticsearch:65 - > {"test": "test mongo connector"}
2016-08-11 11:47:14,564 [DEBUG] elasticsearch:66 - < {"_index":"bdtt","_type":"test","_id":"57abf5422ee47ff27a06edd2","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}
2016-08-11 11:47:14,565 [DEBUG] urllib3.util.retry:170 - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2016-08-11 11:47:14,566 [DEBUG] urllib3.connectionpool:401 - "PUT /mongodb_meta/mongodb_meta/57abf5422ee47ff27a06edd2?refresh=false HTTP/1.1" 404 335
2016-08-11 11:47:14,568 [WARNING] elasticsearch:82 - PUT /mongodb_meta/mongodb_meta/57abf5422ee47ff27a06edd2?refresh=false [status:404 request:0.003s]
2016-08-11 11:47:14,568 [DEBUG] elasticsearch:90 - > {"ns": "bdtt.test", "_ts": 6317412566133899266}
2016-08-11 11:47:14,568 [DEBUG] elasticsearch:93 - < {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"mongodb_meta","index":"mongodb_meta"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"mongodb_meta","index":"mongodb_meta"},"status":404}
2016-08-11 11:47:14,569 [ERROR] mongo_connector.oplog_manager:317 - Unable to process oplog document {u'h': -6440389684713070132L, u'ts': Timestamp(1470887234, 2), u'o': {u'test': u'test mongo connector'}, u't': 2L, u'v': 2, u'ns': u'bdtt.test', u'op': u'i'}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 296, in run
    docman.upsert(doc, ns, timestamp)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 160, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'index_not_found_exception', u'no such index')
2016-08-11 11:47:14,570 [DEBUG] mongo_connector.oplog_manager:327 - OplogThread: Documents removed: 0, inserted: 0, updated: 0 so far
2016-08-11 11:47:14,570 [DEBUG] mongo_connector.oplog_manager:329 - OplogThread: Doc is processed.

**Comment by llvtt** [comment]
I think the instructions assume that indexes can be created dynamically by inserting a document into it. Do you have [`action.auto_create_index: false`](https://www.elastic.co/guide/en/elasticsearch/guide/current/_creating_an_index.html) in your `elasticsearch.yml`? If so, try creating the `mongodb_meta` index manually. If that solves the problem, then I'll update the wiki accordingly.

**Comment by happynewday** [comment]
yes, @llvtt, as you said, after set auto_index open for mongodb_meta and other affected indices, mongo-connector can successfully dump doc from mongodb to es now without report errors.
there are two ways to avoid this error. 
1. Open auto_index for mongodb_meta and other affected indices, in my case, I add one line in elasticsearch.yml: action.auto_create_index: bdtt,mongodb_meta
2. create the mongodb_meta and other indices manually along with mapping settings.

**Comment by llvtt** [comment]
Glad it's working! I updated the documentation on the elastic page by mentioning `auto_create_index`: https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-ElasticSearch#elasticsearch-indexes-mappings-and-types.

**Comment by vancouverwill** [comment]
we got this to work with elastic search 5.4.0. With elastic search v2.4.0 the index was getting populated but all strings were not being analysed so weren't showing up in our `_all` search.
