### ISSUE TITLE
TransportError on new documents

### ISSUE THREAD

**Issue by BlueRayONE** [mongodb-labs/mongo-connector#506]
When I add (a lot of) data to my MongoDB instance, the mongo-connector.log is flooded with the following error-type:

```
2016-08-15 12:34:33,698 [ERROR] mongo_connector.oplog_manager:317 - Unable to process oplog document {u'h': -3006652613200498869L, u'ts': Timestamp(1471253779, 4816), u'o': {u'_id': u'2a1ff5db04c2b06e32c057af65141b0f4930f9568e739fc363cade4db90eec26'}, u't': 15L, u'v': 2, u'ns': u'hsi.hplhdk_singleentries', u'op': u'd'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 279, in run
    entry['o']['_id'], ns, timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 254, in remove
    refresh=(self.auto_commit_interval == 0))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 722, in delete
    doc_type, id), params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'{"found":false,"_index":"hplhdk_singleentries","_type":"hsi","_id":"2a1ff5db04c2b06e32c057af65141b0f4930f9568e739fc363cade4db90eec26","_version":1,"_shards":{"total":2,"successful":1,"failed":0}}')
```

```
2016-08-15 12:34:33,708 [ERROR] mongo_connector.oplog_manager:317 - Unable to process oplog document {u'h': -7721836120818217017L, u'ts': Timestamp(1471253779, 4817), u'o': {u'_id': u'7ef3abb4bcaeef6c8769643eb3bf38aec8b4b5139d0b4e25d548c81d0f87fc4b'}, u't': 15L, u'v': 2, u'ns': u'hsi.hplhdk_singleentries', u'op': u'd'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 279, in run
    entry['o']['_id'], ns, timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 254, in remove
    refresh=(self.auto_commit_interval == 0))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 722, in delete
    doc_type, id), params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'{"found":false,"_index":"hplhdk_singleentries","_type":"hsi","_id":"7ef3abb4bcaeef6c8769643eb3bf38aec8b4b5139d0b4e25d548c81d0f87fc4b","_version":1,"_shards":{"total":2,"successful":1,"failed":0}}')
```

The doc of the second error above for example looks like this:

```
{
    "_id" : "7ef3abb4bcaeef6c8769643eb3bf38aec8b4b5139d0b4e25d548c81d0f87fc4b",
    "SN" : "9262011744",
    "happenedAt" : ISODate("2016-08-13T13:13:19.000Z"),
    "printJobID" : "1608131750719",
    "printJob" : 1,
    "country" : "Netherlands"
}
```

This looks normal to me and I don't understand the problem here. I can execlude the solution of issue #214.

I'm using mongo-connector v2.4 and pymongo v3.2.2.

Edit 2:
I should mention additionally, that I'm syncing to Elasticsearch and that the documents above nevertheless arrive there! So for which reason thos error!?

**Comment by ShaneHarvey** [comment]
Hi @BlueRayONE,

The OperationFailed errors you're getting are because the document to delete does not exist in Elastic. This could be because mongo-connector is applying some oplog entries for "deletes" that were already done. Re-applying oplog entries is normal and correct behavior. This in combination with the fact that documents are being replicated indicates that this is a non-issue.

Are you facing any other issues besides the abundance of failed delete errors in the logs?

**Comment by BlueRayONE** [comment]
Hello @ShaneHarvey,

alright, that's logical. 
No, I didn't discovered any other issues in this context. I was just wondering because of the big number of these messages which sound bad at first sight, so that I thought there would be other problems I didn't saw yet.
So this is a non-issue, yes. Sorry.

But thanks for clarification!
