### ISSUE TITLE
ConnectionFailed: <urlopen error [Errno 104] Connection reset by peer>?

### ISSUE THREAD

**Issue by finch0001** [mongodb-labs/mongo-connector#507]
1. the mongo-connector log file:
2016-08-17 11:18:51,257 [CRITICAL] mongo_connector.oplog_manager:626 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 594, in do_dump
    dm.insert_file(gridfile, dest_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1.dev0-py2.7.egg/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1.dev0-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1.dev0-py2.7.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 316, in insert_file
    response = urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
ConnectionFailed: <urlopen error [Errno 104] Connection reset by peer>
2016-08-17 11:18:51,258 [ERROR] mongo_connector.oplog_manager:634 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['10.0.0.88:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=u'myreplset'), u'local'), u'oplog.rs')
2016-08-17 11:18:51,312 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140535467656960)> unexpectedly stopped! Shutting down

2. my command line:
mongo-connector -a solr -p spider -n drwifi.fs --gridfs-set=drwifi.fs  --auto-commit-interval=0 -m 10.0.0.88:27017 -t http://10.0.0.88:8983/solr/collection1 -d solr_doc_manager

3. solr server log:
INFO  - 2016-08-17 11:18:09.451; org.apache.solr.update.processor.LogUpdateProcessor; [collection1] webapp=/solr path=/update/extract params={literal.filename=timg&literal._id=57a99897a68454c3253f0fff&literal._ts=6316750526989992372&commit=true&literal.ns=drwifi.fs&literal.md5=69237a81cf3f4278f3428181b17512b0&literal.upload_date=2016-08-09+08:47:19.840000} {add=[57a99897a68454c3253f0fff (1542878804734640128)],commit=} 0 55
INFO  - 2016-08-17 11:18:09.471; org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2016-08-17 11:18:09.620; org.apache.solr.core.SolrDeletionPolicy; SolrDeletionPolicy.onCommit: commits: num=2
        commit{dir=NRTCachingDirectory(MMapDirectory@/opt/solr/data/index lockFactory=NativeFSLockFactory@/opt/solr/data/index; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_3aq1,generation=153865}
        commit{dir=NRTCachingDirectory(MMapDirectory@/opt/solr/data/index lockFactory=NativeFSLockFactory@/opt/solr/data/index; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_3aq2,generation=153866}
INFO  - 2016-08-17 11:18:09.621; org.apache.solr.core.SolrDeletionPolicy; newest commit generation = 153866
INFO  - 2016-08-17 11:18:09.629; org.apache.solr.search.SolrIndexSearcher; Opening Searcher@65e04983[collection1] main
INFO  - 2016-08-17 11:18:09.629; org.apache.solr.core.QuerySenderListener; QuerySenderListener sending requests to Searcher@65e04983[collection1] main{StandardDirectoryReader(segments_35y3:331636:nrt _3ddu(4.10.4):C6184 _3ddv(4.10.4):C1 _3ddw(4.10.4):C1 _3ddx(4.10.4):C1 _3ddy(4.10.4):C1 _3ddz(4.10.4):C1 _3de0(4.10.4):C1 _3de1(4.10.4):C1)}
INFO  - 2016-08-17 11:18:09.629; org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2016-08-17 11:18:09.630; org.apache.solr.core.QuerySenderListener; QuerySenderListener done.
INFO  - 2016-08-17 11:18:09.631; org.apache.solr.core.SolrCore; [collection1] Registered new searcher Searcher@65e04983[collection1] main{StandardDirectoryReader(segments_35y3:331636:nrt _3ddu(4.10.4):C6184 _3ddv(4.10.4):C1 _3ddw(4.10.4):C1 _3ddx(4.10.4):C1 _3ddy(4.10.4):C1 _3ddz(4.10.4):C1 _3de0(4.10.4):C1 _3de1(4.10.4):C1)}
INFO  - 2016-08-17 11:18:09.631; org.apache.solr.update.processor.LogUpdateProcessor; [collection1] webapp=/solr path=/update/extract params={literal.filename=08012275e6e3ebb4577c253af21dc92b9793e14c8f2366fbe0a35a34d0849c89-primary.xml.gz&literal._id=57a99898a68454c3253f1001&literal._ts=6316750526989992372&commit=true&literal.ns=drwifi.fs&literal.md5=dbe7fb9f5209dd9222ffa609dd323ce7&literal.upload_date=2016-08-09+08:47:20.443000} {add=[57a99898a68454c3253f1001 (1542878804803846144)],commit=} 0 176
INFO  - 2016-08-17 11:18:09.639; org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2016-08-17 11:18:09.683; org.apache.solr.core.SolrDeletionPolicy; SolrDeletionPolicy.onCommit: commits: num=2
        commit{dir=NRTCachingDirectory(MMapDirectory@/opt/solr/data/index lockFactory=NativeFSLockFactory@/opt/solr/data/index; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_3aq2,generation=153866}
INFO  - 2016-08-17 11:18:09.684; org.apache.solr.core.SolrDeletionPolicy; newest commit generation = 153867
INFO  - 2016-08-17 11:18:09.686; org.apache.solr.search.SolrIndexSearcher; Opening Searcher@41f1548f[collection1] main
INFO  - 2016-08-17 11:18:09.687; org.apache.solr.core.QuerySenderListener; QuerySenderListener sending requests to Searcher@41f1548f[collection1] main{StandardDirectoryReader(segments_35y3:331638:nrt _3ddu(4.10.4):C6184 _3ddv(4.10.4):C1 _3ddw(4.10.4):C1 _3ddx(4.10.4):C1 _3ddy(4.10.4):C1 _3ddz(4.10.4):C1 _3de0(4.10.4):C1 _3de1(4.10.4):C1 _3de2(4.10.4):C1)}
INFO  - 2016-08-17 11:18:09.687; org.apache.solr.core.QuerySenderListener; QuerySenderListener done.
INFO  - 2016-08-17 11:18:09.687; org.apache.solr.update.DirectUpdateHandler2; end_commit_flush
INFO  - 2016-08-17 11:18:09.688; org.apache.solr.core.SolrCore; [collection1] Registered new searcher Searcher@41f1548f[collection1] main{StandardDirectoryReader(segments_35y3:331638:nrt _3ddu(4.10.4):C6184 _3ddv(4.10.4):C1 _3ddw(4.10.4):C1 _3ddx(4.10.4):C1 _3ddy(4.10.4):C1 _3ddz(4.10.4):C1 _3de0(4.10.4):C1 _3de1(4.10.4):C1 _3de2(4.10.4):C1)}
INFO  - 2016-08-17 11:18:09.688; org.apache.solr.update.processor.LogUpdateProcessor; [collection1] webapp=/solr path=/update/extract params={literal.filename=unknow_name&literal._id=57a99898a68454c3253f1003&literal._ts=6316750526989992372&commit=true&literal.ns=drwifi.fs&literal.md5=8e12d4b8ba50db4ea5a2663b1af845fb&literal.upload_date=2016-08-09+08:47:20.612000} {add=[57a99898a68454c3253f1003 (1542878804981055488)],commit=} 0 54
INFO  - 2016-08-17 11:18:09.700; org.apache.solr.update.DirectUpdateHandler2; start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
INFO  - 2016-08-17 11:18:09.757; org.apache.solr.core.SolrDeletionPolicy; SolrDeletionPolicy.onCommit: commits: num=2
        commit{dir=NRTCachingDirectory(MMapDirectory@/opt/solr/data/index lockFactory=NativeFSLockFactory@/opt/solr/data/index; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_3aq3,generation=153867}
        commit{dir=NRTCachingDirectory(MMapDirectory@/opt/solr/data/index lockFactory=NativeFSLockFactory@/opt/solr/data/index; maxCacheMB=48.0 maxMergeSizeMB=4.0),segFN=segments_3aq4,generation=153868}
INFO  - 2016-08-17 11:18:09.757; org.apache.solr.core.SolrDeletionPolicy; newest commit generation = 153868
INFO  - 2016-08-17 11:18:09.758; org.apache.solr.search.SolrIndexSearcher; Opening Searcher@3c230457[collection1] main
INFO  - 2016-08-17 11:18:09.758; org.apache.solr.core.QuerySenderListener; QuerySenderListener sending requests to Searcher@3c230457[collection1] main{StandardDirectoryReader(segments_35y3:331641:nrt _3ddu(4.10.4):C6184 _3ddv(4.10.4):C1 _3ddw(4.10.4):C1 _3ddx(4.10.4):C1 _3ddy(4.10.4):C1 _3ddz(4.10.4):C1 _3de0(4.10.4):C1 _3de1(4.10.4):C1 _3de2(4.10.4):C1 _3de3(4.10.4):C1)}
INFO  - 2016-08-17 11:18:09.758; org.apache.solr.core.QuerySenderListener; QuerySenderListener done.
INFO  - 2016-08-17 11:18:09.758; org.apache.solr.update.DirectUpdateHandler2; end_commit_flush

**Comment by llvtt** [comment]
It looks like there was a problem making the request to the endpoint that does text extraction in Solr. Given your base url of `http://10.0.0.88:8983/solr/collection1`, this should be `http://10.0.0.88:8983/solr/collection1/update/extract`. Is there an [`ExtractingRequestHandler`](https://wiki.apache.org/solr/ExtractingRequestHandler) configured (see "Configuration" section about halfway down)?

**Comment by finch0001** [comment]
1. I checked my solr sorlconfig.xml  and i think it's not the problem of ExtractingRequestHandler configuration. Here is part of my extractingRequestHandler configuration file:
 <requestHandler name="/update/extract"
                  startup="lazy"
                  class="solr.extraction.ExtractingRequestHandler" >
    <lst name="defaults">
      <str name="lowernames">true</str>
      <str name="uprefix">ignored_</str>
      
      <str name="captureAttr">true</str>
      <str name="fmap.a">links</str>
      <str name="fmap.div">ignored_</str>
    </lst>
  </requestHandler>

2. i tried the base url of http://10.0.0.88:8983/solr/collection/extract. But an error has occured: 
mongo_connector.errors.OperationFailed: Solr responded with an error (HTTP 404): [Reason: HTTP Status 404 - /solr/collection1/update/extract/admin/luke]

3. the error "Connection reset by peer" occured when my mongodb fs.chunks collections stored this kind of file: xxx.psf (Content-Type: application/octet-stream) ,may be other kind of file cause this error. After that, when i check my solr collection1 i found i index this file success , but at the same time mongo-connector occurred above error and exit. 

4. when i index my files(text pdf doc jpeg gif gz zip), i found these kind files could index normally.

**Comment by pranav-margino** [comment]
it probably happens because mongo-connector is looking for mongo-connector.log and/or oplog.timestamp(created the first time mongo-connector starts). Therefore, switch to directory where you first started mongo-connector and try to restart.
