### ISSUE TITLE
incremental sync

### ISSUE THREAD

**Issue by kubage88** [mongodb-labs/mongo-connector#514]
when i restart mongo-connector process, it will not push data to elasticsearch any more, unless deleting oplog.timestamp, but if i do this , mongo-connector will sync data from beginning, i have a large amount  of data in mongodb,  how can i synchronize data incrementally when i restart mongo-connector process?

**Comment by kubage88** [comment]
could you give me an answer? thanks a lot...

**Comment by ShaneHarvey** [comment]
Sorry for the delay in getting back to you @kubage88. Mongo-connector is designed to handle a restart as long as the the `oplog.timestamp` oplog entry still exists in the oplog. If that happens mongo-connector logs an error message and shuts down. In the log do you see this error message `Last entry no longer in oplog cannot recover!`? If not this may be a bug. 

What version of mongo-connector and elastic-doc-manager are you using? I just tested your scenario with mongo-connector version 2.4.1 and elastic2-doc-manager version 0.2.0 and the connector was able to continue pushing updates to elastic after the restart.

**Comment by kubage88** [comment]
you are so nice!
my mongo-connector's  version is  2.4.1 and elastic2-doc-manager's  version is 0.2.0。
my scenario is that when mongo-connnector  is pushing data to elasticsearch,  i press **ctrl+c** to stop the process manually,   then i run  **mongo-connector  -c  es.json**  in cmd again,   it will not push data  any more unless deleting oplog.timestamp.

the first zip file is the oplog when i pressed   **ctrl+c**.
the second zip file is the oplog when i ran    **mongo-connector  -c  es.json**     in cmd again for five minutes.

i hope it will be useful for you!

**Comment by kubage88** [comment]
[log1.zip](https://github.com/mongodb-labs/mongo-connector/files/443961/log1.zip)
[log2.zip](https://github.com/mongodb-labs/mongo-connector/files/443962/log2.zip)
[es.json.zip](https://github.com/mongodb-labs/mongo-connector/files/443967/es.json.zip)

**Comment by ShaneHarvey** [comment]
I was able to reproduce your issue. It seems that you are stopping the connector while it is performing the initial collection dump. The problem is that the oplog.progress file is already created but not all the documents have been synced to the target.

The giveaway was that your mongo-connector.log has many errors like:
```python
2016-08-30 11:45:06,188 [ERROR] mongo_connector.oplog_manager:324 - Unable to process oplog document {u'h': 3277330390668528290L, u'ts': Timestamp(1472528706, 7), u'o': {u'$set': {u'__v': 3, u'UpdateTime': u'2016-08-30T11:45:06.5826447+08:00'}}, u'v': 2, u'ns': u'ScrmDB.Contacts.Contact', u'o2': {u'_id': ObjectId('000000000000000366252065')}, u'op': u'u'}
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\mongo_connector\oplog_manager.py", line 310, in run
    ns, timestamp)
  File "c:\python27\lib\site-packages\mongo_connector\util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "c:\python27\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "c:\python27\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 161, in update
    id=u(document_id))
  File "c:\python27\lib\site-packages\elasticsearch\client\utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "c:\python27\lib\site-packages\elasticsearch\client\__init__.py", line 341, in get
    doc_type, id), params=params)
  File "c:\python27\lib\site-packages\elasticsearch\transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "c:\python27\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\python27\lib\site-packages\elasticsearch\connection\base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'{"_index":"scrmdb","_type":"Contacts.Contact","_id":"000000000000000366252065","found":false}')
```

**Comment by kubage88** [comment]
I do not think **full re-sync** is a good idea, because  I have a large amount of data in mongodb ,if the server where is mongo-connector located at is shutdown with some  irresistible causes  while the initial collection dump is nearing completion , I must perform a full re-sync again, It will spends a lot of time, Is there any other ways to continue to push data while  above scenario occured .

**Comment by ShaneHarvey** [comment]
Currently there's no way to resume the initial collection dump.  Let's say the connector completed 95% of the collection dump before shutting down. When you restart the connector, it *should* realize that it did not finish the collection dump and either abort with a message OR possibly resume from where it left off. 

Instead what happens in versions 2.4.1 and below is that new documents and changes to 95% of the documents will be updated and mongo-connector will still run, but *your data will not be consistent*. Additionally, changes to the 5% of the documents that were not dumped will result in the `Unable to process oplog document` errors you are seeing. 

That said, I think we may be able to support a resumable initial collection dump. We'll use this issue to track the bug fix and then the resumable collection dump enhancement (which might be part of the same commit).

**Comment by metanav** [comment]
Any progress on it? I have 300 GB of data in MongoDB and initial dump takes 12 days to complete. But for some reason either I have to cancel the dumping or  server has to be restarted. I want to resume the initial dumping instead of re-doing.

**Comment by aki83reo** [comment]
@ShaneHarvey  , is there  any  work around    for this issue  raised  by @kubage88  ,  i  am  facing the same issue  , I  have  to  delete  every  time  the opplog.timestamp  file  before starting  the  mongo-connector ,  the  CMD freezes   if  i dont  delete  the  file  .
