### ISSUE TITLE
serious bug

### ISSUE THREAD

**Issue by kubage88** [mongodb-labs/mongo-connector#517]
this is a serious bug, i can not sync data with mongo-connector, please see the log.

[mongo-connector.log.zip](https://github.com/mongodb-labs/mongo-connector/files/455161/mongo-connector.log.zip)_

**Comment by dingding2015** [comment]
InvalidBSON: 'utf8' codec can't decode byte 0xc0 in position 2: invalid start byte
2016-09-04 15:24:11,413 [ERROR] __main__:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 140569963648768)> unexpectedly stopped! Shutting down

we have the same question!

**Comment by kubage88** [comment]
I am not sure ,How could I solve the problem?

**Comment by kubage88** [comment]
No, They are different, Yours was caused by encoding, Mine was caused by **object of type 'NoneType' has no len()** , I have read elastic2-doc-manager  code, It seems like missing a  validation  in doc_manager_base.py line 70

**Comment by kubage88** [comment]
Mongo-Connector is not very stable, Sometimes it will stop sync data to ElasticSearch with no errors!

**Comment by ShaneHarvey** [comment]
Posting the error from the log here so it's easier to view:
```python
2016-09-05 21:52:50,916 [ERROR] mongo_connector.util:92 - Fatal Exception
Traceback (most recent call last):
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\oplog_manager.py", line 310, in run
    ns, timestamp)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 162, in update
    updated = self.apply_update(document['_source'], update_spec)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 112, in apply_update
    return super(DocManager, self).apply_update(doc, update_spec)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\doc_manager_base.py", line 70, in apply_update
    wl = len(where)
TypeError: object of type 'NoneType' has no len()
2016-09-05 21:52:51,511 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 6792)> unexpectedly stopped! Shutting down
 ```

**Comment by ShaneHarvey** [comment]
Can you post your elastic configuration? Do you have [_source enabled?](https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#why-are-my-documents-empty-in-elasticsearch-why-are-updates-not-happening-in-elasticsearch)

**Comment by kubage88** [comment]
@ShaneHarvey  
I'm sorry! I  will paste the error log here  next time. 
I have enabled _source.

**Comment by ShaneHarvey** [comment]
@kubage88 can you provide the steps to reproduce this problem? If it's due to a specific oplog entry, can you post that here too? I'd like to fix this and add a test to make sure it doesn't come back.

**Comment by ShaneHarvey** [comment]
@kubage88 whatever `$set` update that caused this issue will no longer cause the connector to halt. Instead, the update will fail and be logged as an `UpdateDoesNotApply` error.

If you find out how to reproduce the failure with a specific update or oplog entry please post it here.

**Comment by kubage88** [comment]
It  sounds exciting, I hope release 2.5.0 to be published as soon  as possible!
