### ISSUE TITLE
Not able to use Configuration file for connecting to mongo-connector

### ISSUE THREAD

**Issue by nprasannaganesh** [mongodb-labs/mongo-connector#527]
Team,
Not sure this is the right place for asking questions. Please excuse me if its not correct place.

I'm trying to establish a connection between 2 mongo replica sets through mongo connector and its working fine. But instead of mentioning the server name and port details in cmd line argument, I want to configure it in a config file. 

mongo-connector -m localhost:27017 -t localhost:37017 -d mongo_doc_manager

I followed the steps mentioned in the link [](](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options)  but its not working. I'm also pasting my config.json file here. Please correct if i'm making any mistakes.

I want to pass command like this `mongo-connector -c myconfig.json` instead of `mongo-connector -m localhost:27017 -t localhost:37017 -d mongo_doc_manager`

myconfig.json file
```
{
    "__comment__": "Configuration options starting with '__' are disabled",
    "__comment__": "To enable them, remove the preceding '__'",

    "mainAddress": "localhost:27017",
    "oplogFile": "C:\Dev\mongodb\mongo-connector\oplog.timestamp",
	"noDump": false,
	"batchSize": -1,
    "verbosity": 2,
    "continueOnError": false,

    "logging": {
        "type": "file",
        "filename": "C:\Dev\mongodb\mongo-connector\mongo-connector.log",
		"__format": "%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s",
        "__rotationWhen": "D",
        "__rotationInterval": 1,
        "__rotationBackups": 10,
        "__type": "syslog",
		"__host": "localhost:27017"        
    },	
	

    "docManagers": [
        {
            "docManager": "mongo_doc_manager",
            "targetURL": "localhost:37010",
            "__autoCommitInterval": null
        }
    ]
}
```

**Comment by ShaneHarvey** [comment]
The only thing that stands out to me is your targetURL port number is 37010 instead of the 37017 in your examples. Are there any errors reported in ``mongo-connector.log``?

**Comment by nprasannaganesh** [comment]
Thanks for the response. I have corrected it in myconfig.json but still getting same exception.Please find below the exception details.

C:\Dev\mongodb\mongo-connector>mongo-connector -c myconfig.json
Fatal Exception
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 110, in parse_args
    self.load_json(f.read())
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 132, in load_json
    parsed_config = json.loads(text)
  File "C:\Program Files\Python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 6 column 21 (char 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\connector.py", line 1059, in main
    conf.parse_args()
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 112, in parse_args
    reraise(errors.InvalidConfiguration, *sys.exc_info()[1:])
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\compat.py", line 9, in reraise
    raise exctype(str(value)).with_traceback(trace)
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 110, in parse_args
    self.load_json(f.read())
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 132, in load_json
    parsed_config = json.loads(text)
  File "C:\Program Files\Python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
mongo_connector.errors.InvalidConfiguration: Invalid \escape: line 6 column 21 (char 201)
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 110, in parse_args
    self.load_json(f.read())
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 132, in load_json
    parsed_config = json.loads(text)
  File "C:\Program Files\Python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 6 column 21 (char 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python\Scripts\mongo-connector-script.py", line 9, in <module>
    load_entry_point('mongo-connector==2.5.0.dev0', 'console_scripts', 'mongo-connector')()
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\connector.py", line 1059, in main
    conf.parse_args()
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 112, in parse_args
    reraise(errors.InvalidConfiguration, *sys.exc_info()[1:])
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\compat.py", line 9, in reraise
    raise exctype(str(value)).with_traceback(trace)
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 110, in parse_args
    self.load_json(f.read())
  File "C:\Program Files\Python\lib\site-packages\mongo_connector-2.5.0.dev0-py3.6.egg\mongo_connector\config.py", line 132, in load_json
    parsed_config = json.loads(text)
  File "C:\Program Files\Python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
mongo_connector.errors.InvalidConfiguration: Invalid \escape: line 6 column 21 (char 201)

**Comment by nprasannaganesh** [comment]
As you aware, I'm trying this in windows environment.

**Comment by ShaneHarvey** [comment]
You need to escape your backslashes, eg.
``"C:\\Dev\\mongodb\\mongo-connector\\oplog.timestamp"``

**Comment by nprasannaganesh** [comment]
Hurray!!! It worked this time. Silly mistake killed my time. Thank you very much for resolving this.
