### ISSUE TITLE
Windows: mongo-connector halts after MemoryError

### ISSUE THREAD

**Issue by kubage88** [mongodb-labs/mongo-connector#562]
mongo-connector stops synchronizing data with some errors.

2016-10-26 10:34:39,881 [ERROR] mongo_connector.util:92 - Fatal Exception
Traceback (most recent call last):
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 90, in wrapped
    func(_args, *_kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\oplog_manager.py", line 310, in run
    ns, timestamp)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(_args, *_kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 165, in update
    self.upsert(updated, namespace, timestamp)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(_args, *_kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 182, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\elasticsearch\client\utils.py", line 69, in _wrapped
    return func(_args, params=params, *_kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\elasticsearch\client__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\elasticsearch\transport.py", line 310, in perform_request
    body = body.encode('utf-8')
MemoryError
2016-10-26 10:34:40,265 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 11004)> unexpectedly stopped! Shutting down

**Comment by ShaneHarvey** [comment]
I don't know there's anything MongoConnector can do about Python throwing MemoryError. 

- Can you show the version of Python you're using? If it's a 32-bit Python perhaps you can try 64-bit so it will be less likely to run into this problem. To check on Windows:

  ```python
>>> import platform
>>> platform.architecture()
('32bit', 'WindowsPE')
  ```
- Can you describe your environment? Windows version/RAM/etc..
- Run `python -m pip freeze` to list your mongo-connector/elastic versions.

**Comment by kubage88** [comment]
![snip20161027_11](https://cloud.githubusercontent.com/assets/2314092/19761039/de9c083c-9c66-11e6-867c-85a683a2e1c6.jpg)
![snip20161027_5](https://cloud.githubusercontent.com/assets/2314092/19761042/e135a08a-9c66-11e6-802b-e4605869b797.jpg)
![snip20161027_10](https://cloud.githubusercontent.com/assets/2314092/19761053/e6a5ec46-9c66-11e6-84e6-03fd0f6a6597.png)

**Comment by ShaneHarvey** [comment]
It looks like you have a very small amount of virtual memory available (113 MB). Are you running other services on this machine? I can only recommend increasing your ram or increasing your swap space. There's nothing mongo-connector can do if the system is out of resources.
