### ISSUE TITLE
MongoConnector deletes documents from Elastic after restart after it lost connection to Mongo

### ISSUE THREAD

**Issue by ronaldploeger** [mongodb-labs/mongo-connector#572]
Hi, 

we have a MongoDB replica set and yesterday we changed which node is primary by letting the current primary step down. It took a few seconds for a new primary to be elected and during this time MongoConnector emitted the following error: 

```
2016-10-27 14:45:22,810 [ERROR] mongo_connector.oplog_manager:350 - Cursor closed due to an exception. Will attempt to reconnect.
Traceback (most recent call last):
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 225, in run
    for n, entry in enumerate(cursor):
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1032, in _refresh
    self.__max_await_time_ms))
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/cursor.py", line 850, in __send_message
    **kwargs)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 798, in _send_message_with_response
    exhaust)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 809, in _reset_on_error
    return func(*args, **kwargs)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/server.py", line 120, in send_message_with_response
    response_data = sock_info.receive_message(1, request_id)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/pool.py", line 246, in receive_message
    self._raise_connection_failure(error)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/pool.py", line 346, in _raise_connection_failure
    raise error
AutoReconnect: connection closed
2016-10-27 14:45:39,861 [ERROR] mongo_connector.oplog_manager:350 - Cursor closed due to an exception. Will attempt to reconnect.
Traceback (most recent call last):
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 225, in run
    for n, entry in enumerate(cursor):
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1032, in _refresh
    self.__max_await_time_ms))
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/cursor.py", line 850, in __send_message
    **kwargs)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 798, in _send_message_with_response
    exhaust)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 809, in _reset_on_error
    return func(*args, **kwargs)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/server.py", line 120, in send_message_with_response
    response_data = sock_info.receive_message(1, request_id)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/pool.py", line 246, in receive_message
    self._raise_connection_failure(error)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/pymongo/pool.py", line 346, in _raise_connection_failure
    raise error
AutoReconnect: connection closed
```

We then restarted the MongoConnector instance:

```
2016-10-27 14:47:02,434 [INFO] mongo_connector.connector:1062 - Beginning Mongo Connector
2016-10-27 14:47:02,479 [INFO] mongo_connector.oplog_manager:92 - OplogThread: Initializing oplog thread
2016-10-27 14:47:02,483 [INFO] mongo_connector.connector:296 - MongoConnector: Starting connection thread MongoClient(host=[u'elastic-stage-1.xxx.de:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=u'esc-stage')
2016-10-27 14:48:41,428 [INFO] urllib3.connectionpool:214 - Starting new HTTP connection (1): elastic-stage-11.xxx.de
```

For a while everything looked good. Then we saw that MongoConnector was trying to update documents in Elastic but could not retrieve the documents from Elastic:

```
2016-10-27 14:54:29,469 [WARNING] elasticsearch:82 - GET /index_v20/entry/5811af180cf2c44f7e8ad8c6 [status:404 request:0.002s]
2016-10-27 14:54:29,470 [ERROR] mongo_connector.oplog_manager:317 - Unable to process oplog document {u'h': -8419284649862194854L, u'ts': Timestamp(1477572869, 4), u'o': {... {u'_id': ObjectId('5811af180cf2c44f7e8ad8c6')}, u'op': u'u'}
Traceback (most recent call last):
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 303, in run
    ns, timestamp)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/mongo_connector/util.py", line 43, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 135, in update
    id=u(document_id))
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 346, in get
    doc_type, id), params=params)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/var/virtualenv/mongo-connector-2.4-elastic2-doc-manager/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'{"_index":"index_v20","_type":"entry","_id":"5811af180cf2c44f7e8ad8c6","found":false}')
```

We could also see that the number of documents slowly but steadyly decreased in our ElasticSearch index. 

When we stopped MongoConnector the number of documents in Elastic stayed the same, when we started MongoConnector again, the number of documents started to decrease again. 

Therefore MongoConnector was deleting document in Elastic but we could not find any log entries for this in the MongoConnector log which we run on "verbosity": 2

We checked the oplog of our MongoDB and there was not delete operation for the mentioned object. 

Therefore it seems that MongoConnector was deleting documents in our ElasticSearch index on its own. 

Any idea why this happened would be appreciated?

**Comment by ShaneHarvey** [comment]
Any chance you can try looking for deletes in the Elasticsearch log?

First mongo-connector should be able to handle a connection failure to

**Comment by ShaneHarvey** [comment]
Can you also add your MongoDB version, Elasticsearch version, and mongo-connector version (`pip freeze`)? And your config file. Please remember to redact any sensitive information.

**Comment by ronaldploeger** [comment]
Hi, 

thanks, I appreciate that you are looking into this.

Regarding elastic logs I could not find any information concerning deletes. But then the log is not that detailed. 

We are using:
- mongodb version v2.6.10
- elastic 2.3.1

pip freeze:
elastic2-doc-manager==0.1.0
elasticsearch==2.3.0
mongo-connector==2.4
pymongo==3.2.2
pysolr==3.5.0
requests==2.10.0
urllib3==1.16

Config:
```
{
    "__comment__": "Configuration options starting with '__' are disabled",
    "__comment__": "To enable them, remove the preceding '__'",
    "mainAddress": "<%= @mongodb_host %>:<%= @mongodb_port %>",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 2,
    "continueOnError": true,
    "logging": {
        "type": "file",
        "filename": "/var/log/mongo-connector/index_v20.log",
        "rotationInterval": 0
    },
    "authentication": {
        "adminUsername": "xxx",
        "passwordFile": "/var/mongo-connector/passwords/xxx-password"
    },
    "namespaces": {
        "include": ["xx.yy"],
        "mapping": {
                "xx.yy": "index_v20.entry"
        }
    },
    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "<%= @elastic_host %>:<%= @elastic_port %>",
            "args": {
              "clientOptions": {"timeout": 100}
            }
        }
    ]
}
```

Here is the oplog entries for "5811af180cf2c44f7e8ad8c6":

```
{ "ts" : Timestamp(1477553945, 1), "h" : NumberLong("-4255217858771921737"), "v" : 2, "op" : "i", "ns" : "xx.yy" }
{ "ts" : Timestamp(1477558444, 50), "h" : NumberLong("-3090217483104770716"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477558566, 2), "h" : NumberLong("1146974894952798907"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477558625, 54), "h" : NumberLong("7626505905232205825"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477564323, 2), "h" : NumberLong("5380705482320498"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477564505, 5), "h" : NumberLong("-7303962542891951456"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477572869, 4), "h" : NumberLong("-8419284649862194854"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477573865, 6), "h" : NumberLong("8069593645982629790"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477573868, 3), "h" : NumberLong("-566094036316565444"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477581964, 4), "h" : NumberLong("-5676365465914338805"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
{ "ts" : Timestamp(1477582024, 5), "h" : NumberLong("7288815515185720138"), "v" : 2, "op" : "u", "ns" : "xx.yy", "o2" : { "_id" : ObjectId("5811af180cf2c44f7e8ad8c6") } }
```

**Comment by ShaneHarvey** [comment]
I don't see anything that would cause an update to be converted into a delete in the elastic2-doc-manager. Perhaps the `xx.yy` collection has documents with a string that is the same as the value mongo-connector uses to store the ObjectId? Can you try searching the oplog for `"_id": "5811af180cf2c44f7e8ad8c6"`?

**Comment by ronaldploeger** [comment]
I tried searching the oplog for "_id": "5811af180cf2c44f7e8ad8c6" and it did not return any results.

**Comment by ShaneHarvey** [comment]
Thanks, so then it is probably something else. It's worth pointing out that your mongo-connector, elastic2-doc-manager, and Elasticsearch versions are outdated. Perhaps this issue is not present in the current releases.
