### ISSUE TITLE
Unable to connect to 

### ISSUE THREAD

**Issue by relio** [mongodb-labs/mongo-connector#587]
Hi all!
even if I used the "_" version of the basic command, I got the error below. Can anyone help me?
TIA!

`aurelio@laura:~/elastic2-doc-manager$ mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager
No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 9, in <module>
    load_entry_point('mongo-connector==2.4.1', 'console_scripts', 'mongo-connector')()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1-py2.7.egg/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1-py2.7.egg/mongo_connector/connector.py", line 1059, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1-py2.7.egg/mongo_connector/config.py", line 118, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1-py2.7.egg/mongo_connector/connector.py", line 854, in apply_doc_managers
    dm_instances.append(DocManager(target_url, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/elastic2_doc_manager-0.2.1.dev0-py2.7.egg/mongo_connector/doc_managers/elastic2_doc_manager.py", line 114, in __init__
    self.elastic = Elasticsearch(hosts=url, **client_options)
  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 169, in __init__
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 126, in __init__
  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 257, in sniff_hosts
elasticsearch.exceptions.TransportError: TransportError(N/A, 'Unable to sniff hosts - no viable hosts found.')
`

**Comment by ShaneHarvey** [comment]
This should be fixed by the above change in the elastic2-doc-manager.
