### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by kubage88** [mongodb-labs/mongo-connector#592]
`2016-11-17 17:13:52,233 [ERROR] mongo_connector.util:92 - Fatal Exception
Traceback (most recent call last):
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\oplog_manager.py", line 310, in run
    ns, timestamp)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 162, in update
    updated = self.apply_update(document['_source'], update_spec)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 112, in apply_update
    return super(DocManager, self).apply_update(doc, update_spec)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\doc_manager_base.py", line 70, in apply_update
    wl = len(where)
TypeError: object of type 'NoneType' has no len()
2016-11-17 17:13:53,202 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 14100)> unexpectedly stopped! Shutting down
2016-11-17 17:14:07,283 [ERROR] mongo_connector.util:92 - Fatal Exception
Traceback (most recent call last):
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\oplog_manager.py", line 310, in run
    ns, timestamp)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 162, in update
    updated = self.apply_update(document['_source'], update_spec)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 112, in apply_update
    return super(DocManager, self).apply_update(doc, update_spec)
  File "c:\users\yaoshirong\appdata\local\programs\python\python35\lib\site-packages\mongo_connector\doc_managers\doc_manager_base.py", line 70, in apply_update
    wl = len(where)
TypeError: object of type 'NoneType' has no len()
2016-11-17 17:14:08,253 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 33500)> unexpectedly stopped! Shutting down
`

**Comment by ShaneHarvey** [comment]
This was fixed in #565 and will be in the upcoming release 2.5.0. If you can reproduce this bug, can you post what MongoDB operations cause it? Please comment on the original issue (https://github.com/mongodb-labs/mongo-connector/issues/517) instead of opening a new one
