### ISSUE TITLE
unable to run mongo-connector getting error elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', 'no [query] registered for [filtered]')

### ISSUE THREAD

**Issue by zqadora1** [mongodb-labs/mongo-connector#603]
Hello,

When trying to get mongo-connector between mongodb 3.4 and elasticsearch 5x, I get the following error 

[root@bpirpt-dev01 site-packages]# mongo-connector -m localhost:27017 -t http://localhost:9200 -o /opt/rh/rh-python34/root/usr/bin/mongo-connector.oplog -d elastic2_doc_manager -n test_database.test_problems
Logging to mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 199, in run
    cursor, cursor_empty = self.init_cursor()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 714, in init_cursor
    self.checkpoint = self.rollback()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 850, in rollback
    for doc in dm.search(start_ts, end_ts):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 289, in _stream_search
    scroll='10m', **kwargs):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/helpers/__init__.py", line 277, in scan
    resp = client.search(body=query, scroll=scroll, size=size, **kwargs)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/client/__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', 'no [query] registered for [filtered]')

Any idea what might be causing this issue?

**Comment by zqadora1** [comment]
using the current dev version of mongo-connector resolved this issue, but introduced another one 
 
    for ok, resp in responses:
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'test_clone', '_id': '57dad2d40a65c65a391af889', 'status': 400, '_type': 'test_problems', 'error': {'reason': 'Limit of total fields [1000] in index [synergy_clone] has been exceeded', 'type': 'illegal_argument_exception'}}}])
2016-12-06 09:07:35,958 [ERROR] mongo_connector.oplog_manager:817 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='rs0'), 'local'), 'oplog.rs')
2016-12-06 09:07:36,336 [ERROR] mongo_connector.connector:347 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140432903554816)> unexpectedly stopped! Shutting down
