### ISSUE TITLE
Duplicated oplog entries with MongoDB 2.4 breaks mongo-connector

### ISSUE THREAD

**Issue by mikael-lindstrom** [mongodb-labs/mongo-connector#621]
I tried to use mongo-connector with MongoDB 2.4 and have found a problem with duplicated entries in the oplog. Basically $unset is written to the oplog even if the field being unset doesn't exist.

Example:
```
PRIMARY> db.version()
2.4.14
PRIMARY> use test;
switched to db test
PRIMARY> db.test.insert({"a":"1","b":"2"});
PRIMARY> db.test.find();
{ "_id" : ObjectId("586a4f39656f449ce6b62c25"), "a" : "1", "b" : "2" }
PRIMARY> db.test.update({"_id" : ObjectId("586a4f39656f449ce6b62c25")},{$unset:{"a":"1"}});
PRIMARY> db.test.find()
{ "_id" : ObjectId("586a4f39656f449ce6b62c25"), "b" : "2" }
PRIMARY> db.test.update({"_id" : ObjectId("586a4f39656f449ce6b62c25")},{$unset:{"a":"1"}});
PRIMARY> db.test.find()
{ "_id" : ObjectId("586a4f39656f449ce6b62c25"), "b" : "2" }
PRIMARY> use local
switched to db local
PRIMARY> db.oplog.rs.find();
{ "ts" : Timestamp(1483362083, 1), "h" : NumberLong(0), "v" : 2, "op" : "n", "ns" : "", "o" : { "msg" : "initiating set" } }
{ "ts" : Timestamp(1483362106, 1), "h" : NumberLong("-2373604974530658287"), "v" : 2, "op" : "i", "ns" : "test.test", "o" : { "_id" : ObjectId("586a4f39656f449ce6b62c25"), "a" : "1", "b" : "2" } }
{ "ts" : Timestamp(1483362127, 1), "h" : NumberLong("5823667433637975028"), "v" : 2, "op" : "u", "ns" : "test.test", "o2" : { "_id" : ObjectId("586a4f39656f449ce6b62c25") }, "o" : { "$unset" : { "a" : 1 } } }
{ "ts" : Timestamp(1483362141, 1), "h" : NumberLong("-1127311525069515859"), "v" : 2, "op" : "u", "ns" : "test.test", "o2" : { "_id" : ObjectId("586a4f39656f449ce6b62c25") }, "o" : { "$unset" : { "a" : 1 } } }
```

This causes a problem since the `apply_update` method throws a KeyError if the field doesn't exist.
Relevant code is here: https://github.com/mongodb-labs/mongo-connector/blob/d6ef8b265b4e3b77e2d5e6b93d8abc12e8569989/mongo_connector/doc_managers/doc_manager_base.py#L79-L85

MongoDB 2.6 and later seems to have removed these duplicated entries (only tested 2.6 so far).
Since 2.4 reached End of Life in March 2016 it might not make any sense fixing this issue and mongo-connector could just drop support for 2.4.

**Comment by ShaneHarvey** [comment]
I cannot reproduce this with MongoDB 2.4 and mongo-connector 2.5.0. Can you post the traceback you are seeing?

**Comment by mikael-lindstrom** [comment]
I'm using mongo-connector 2.5.0 with elastic2-doc-manager 0.3.0.
The problem only seems to happen when a document currently being cached for a bulk update gets an `$unset` on a non existing field. Without bulk updates it seems to work fine.

I have made a small patch which fixes the problem for us by ignoring `KeyError` if its an `$unset`.
If you want I can clean up my patch an make an PR.

**Comment by ShaneHarvey** [comment]
I'm able to reproduce this error using your example above. My environment must have been off in some way the last time I tested it. The error when mongo-connector attempts to process the second $unset:
```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 150, in run
    self._docman.send_buffered_operations()
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 482, in send_buffered_operations
    action_buffer = self.BulkBuffer.get_buffer()
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 693, in get_buffer
    self.update_sources()
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 648, in update_sources
    updated = self.docman.apply_update(source, update_spec)
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 224, in apply_update
    return super(DocManager, self).apply_update(doc, update_spec)
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/doc_managers/doc_manager_base.py", line 90, in apply_update
    exc_tb)
  File "/Users/shane/venv-mc-local/lib/python2.6/site-packages/mongo_connector/doc_managers/doc_manager_base.py", line 85, in apply_update
    doc.pop(to_unset)
UpdateDoesNotApply: Cannot apply update {u'$unset': {u'a': 1}} to {u'b': u'2'}
```

I think simply ignoring `KeyError` in this case may be the best approach. We could also catch the `UpdateDoesNotApply` and ignore the update but that would require changes to the DocManagers.

**Comment by ShaneHarvey** [comment]
Fixed by https://github.com/mongodb-labs/mongo-connector/commit/f5f3cda5c27b2f74fe43d5697f5ff8825c3db5db and https://github.com/mongodb-labs/mongo-connector/commit/53200e100f14a1820ec0c6cca6f2b72740979b44.
