### ISSUE TITLE
listDatabases command

### ISSUE THREAD

**Issue by saribmahmood55** [mongodb-labs/mongo-connector#629]
Hi, why I'm I getting this issue as I've specified the namespace already. So as per the docs the listDatabases permission is not required if you provide the namespace-set

2017-01-19 17:40:32,738 [ERROR] mongo_connector.util:86 - Call to <bound method MongoClient.database_names of MongoClient(host=['remotemongo-url:port'], document_class=dict, tz_aware=False, connect=True, replicaset=replicaset)> failed too many times in retry_until_ok
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mongo_connector/util.py", line 78, in retry_until_ok
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1149, in database_names
    "listDatabases")["databases"]]
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pymongo/database.py", line 494, in command
    codec_options, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: not authorized on admin to execute command { listDatabases: 1 }

**Comment by ballerabdude** [comment]
Are you using mlabs or a shared database?

**Comment by saribmahmood55** [comment]
@ballerabdude i'm using mlabs mongodb database

**Comment by ballerabdude** [comment]
I had the same issue! I have updated the mongo-connector code to use another set of credentials to do reads https://github.com/ballerabdude/mongo-connector I have not made a pull request yet since I am waiting for a question of mine to be answered https://github.com/mongodb-labs/mongo-connector/issues/626

**Comment by ShaneHarvey** [comment]
Duplicates https://github.com/mongodb-labs/mongo-connector/issues/626.
