### ISSUE TITLE
mongo to elatsic error

### ISSUE THREAD

**Issue by anekix** [mongodb-labs/mongo-connector#644]
on using this command i get the below error
`sudo mongo-connector -m localhost:27017 -t 1xx.xxx.xxx.xxx -d elastic2_doc_manager  --admin-username xxxx --password xxxx`

```
No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 94, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 1206, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/config.py", line 120, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 972, in apply_doc_managers
    DocManager = import_dm_by_name(dm['docManager'])
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 942, in import_dm_by_name
    return import_dm_by_path(full_name)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 959, in import_dm_by_path
    "vailable doc managers." % package)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic2_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers.
```

**Comment by ShaneHarvey** [comment]
Have you installed monog-connector and the elastic2-doc-manager with the same version of python? See the [installation guide](https://github.com/mongodb-labs/mongo-connector/wiki/Installation).

To see what packages you have installed:
`$ python -m pip freeze`

**Comment by ShaneHarvey** [comment]
I suspect that you may not have [`elasticsearch`](https://pypi.python.org/pypi/elasticsearch) installed. See #669.

**Comment by yog989** [comment]
check if replica set is working fine.
`rs.status() or rs.conf() or rs.help()`
