### ISSUE TITLE
MongoConnector looks stuck

### ISSUE THREAD

**Issue by gandola** [mongodb-labs/mongo-connector#646]
Hi Guys,

I've recreated an index and during the dump phase, we had the following error:
```
2017-02-10 05:59:29,766 [ERROR] mongo_connector.oplog_manager:610 - OplogThread: caught exception during bulk upsert, re-upserting documents serially
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 607, in upsert_all
    mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 44, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 367, in bulk_upsert
    for ok, resp in responses:
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
OperationFailed: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'OrderAttribution', u'_id': u'57acd4db3cfd131700dbf72c', u'error': {u'reason': u'mapper [order.channels.virtual.utm_term] of different type, current_type [double], merged_type [string]', u'type': u'illegal_argument_exception'}, u'_index': u'divvit_v7'}}])
```
I'm running with the **continueOnError=true** option and I was expecting that MC would simply ignore the error and continue. However, now I see ElasticSearch indexing but the document count for this index is stuck and not increasing. What does MongoConnector after an error like this during the dump phase?

**Env:**
Mongo 3.4
ElasticSearch 2.3
MongoConnector:  2.5.0
ES Doc Manager: 0.3.0

Cheers 
Thank you

**Comment by yog989** [comment]
Please check if your replica set is working fine with 
`rs.status() , rs.conf() or rs.help()`
