### ISSUE TITLE
Cannot index long value

### ISSUE THREAD

**Issue by tpham** [mongodb-labs/mongo-connector#658]
So I have documents similar to this in mongodb:

```
{
	"_id" : ObjectId("58a6745bbfa1389ce59552a4"),
	"bSpeakEnglish" : false,
	"sFirstName" : "Leroy",
	"sGender" : "Male",
	"sLastName" : "Cooper",
	"sSSN" : "973-65-1458",
	"tDOB" : 1487303714786,
	"dtHiringDate" : ISODate("2017-04-03T18:21:18.096Z")
...
}
```
And the value of tDOB is a timestamp, so I defined it in the Solr schema as "long":

```
  <field name="tDOB" type="long" indexed="true" stored="true"/>
```

However, when I started mongo connector, the indexing failed with this stack trace (see below). Any guidance is appreciated! Thanks.

```
2017-02-16 20:07:37,522 [ERROR] pysolr:392 - Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=58a6745bbfa1389ce5955136] Error adding field 'tDOB'='1.48730355564e+12' msg=For input string: "1.48730355564e+12"]
2017-02-16 20:07:37,522 [CRITICAL] mongo_connector.oplog_manager:666 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 621, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 607, in upsert_all
    mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 44, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 294, in bulk_upsert
    self.solr.add(batch, **add_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 891, in add
    overwrite=overwrite, handler=handler)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 478, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
OperationFailed: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=58a6745bbfa1389ce5955136] Error adding field 'tDOB'='1.48730355564e+12' msg=For input string: "1.48730355564e+12"]
```

**Comment by ShaneHarvey** [comment]
`Error adding field 'tDOB'='1.48730355564e+12'`

It looks like the `tDOB` field is a BSON double type not a 64-bit integer. Try using the "double" type.

**Comment by tpham** [comment]
Yes, but that's not what in mongo db, which is something like 1487303714786 (Unix epoch time -- this is not the exact number shown in the stack trace btw, just an example from a similar document.) I'm not sure how it got into this format 1.48730355564e+12 when Solr attempted to index it. Could it be a DocManager issue when it constructs data from the corresponding document from mongo? NOTE: I got around this problem by defining tDOB as float in Solr schema; it works but doesn't seem right technically.

**Comment by ShaneHarvey** [comment]
Are you sure that all the documents have a "tDOB" field that's of type "long"? It could be that some documents are "long" and some are "double", for example:
```javascript
myrepl2:PRIMARY> db.test.insert({_id:1, number: 1487303714786})
WriteResult({ "nInserted" : 1 })
myrepl2:PRIMARY> db.test.insert({_id:2, number: NumberLong("1487303714786")})
WriteResult({ "nInserted" : 1 })
myrepl2:PRIMARY> db.test.insert({_id:3, number: NumberInt("1487303714786")})
WriteResult({ "nInserted" : 1 })
myrepl2:PRIMARY> db.test.find()
{ "_id" : 1, "number" : 1487303714786 }
{ "_id" : 2, "number" : NumberLong("1487303714786") }
{ "_id" : 3, "number" : 1245030370 }
myrepl2:PRIMARY> db.test.find({number: {$type: "int"}})
{ "_id" : 3, "number" : 1245030370 }
myrepl2:PRIMARY> db.test.find({number: {$type: "long"}})
{ "_id" : 2, "number" : NumberLong("1487303714786") }
myrepl2:PRIMARY> db.test.find({number: {$type: "double"}})
{ "_id" : 1, "number" : 1487303714786 }
```

Running `db.your_collection.find({"tDOB": {"$type": "double"}})` and then `db.your_collection.find({"tDOB": {"$type": "long"}})` will determine what types are present?

**Comment by tpham** [comment]
My friend - how can I buy you a beer? MongoDB is in fact storing Epoch unix timestamp as double. Thank you very much for your insight.

**Comment by ShaneHarvey** [comment]
You're welcome!
