### ISSUE TITLE
Refresh the whole index

### ISSUE THREAD

**Issue by iliakan** [mongodb-labs/mongo-connector#677]
I'm getting errors like this:
```
2017-03-03 14:18:19,189 [ERROR] mongo_connector.doc_managers.elastic2_doc_manager:491 - Bulk request failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 484, in send_buffered_operations
    successes, errors = bulk(self.elastic, action_buffer)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 194, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 91, in _process_bulk_chunk
    raise e
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10))
2017-03-03 14:18:31,094 [ERROR] mongo_connector.doc_managers.elastic2_doc_manager:632 - mGET: Document id: 58b950aeef320e218435e801 has not been found in Elasticsearch. Due to that following update failed: {u'$set': {u'modified': datetime.datetime(2017, 3, 3, 11, 18, 8, 294000)}}
2017-03-03 14:18:31,094 [ERROR] mongo_connector.doc_managers.elastic2_doc_manager:632 - mGET: Document id: 58b950b4ef320e218435e812 has not been found in Elasticsearch. Due to that following update failed: {u'$set': {u'modified': datetime.datetime(2017, 3, 3, 11, 18, 8, 306000)}}
2
```

Don't know what's wrong.

Maybe it's a bug? 

Initially it worked. How can I refresh the whole index?

**Comment by seancoleman2** [comment]
I am dealing with the same issue, did you find a solution?

**Comment by zhangwenzhao** [comment]
@seancoleman2  how to do ?
