### ISSUE TITLE
mongo_connector.oplog_manager:625 - Exception during collection dump

### ISSUE THREAD

**Issue by zhonggithub** [mongodb-labs/mongo-connector#683]
the log is: 

mongo_connector.oplog_manager:625 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 578, in do_dump
    upsert_all(dm)
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 562, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 203, in bulk_upsert
    for ok, resp in responses:
  File "/usr/lib/python2.6/site-packages/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/lib/python2.6/site-packages/elasticsearch/helpers/__init__.py", line 132, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'tb_auth_log', u'_id': u'58bff247b6a42aea563966e4', u'error': {u'caused_by': {u'reason': u'Invalid format: "361488970807.0"', u'type': u'illegal_argument_exception'}, u'reason': u'failed to parse [ExpireTime]', u'type': u'mapper_parsing_exception'}, u'_index': u'uwifi'}}])
2017-03-13 15:16:55,742 [ERROR] mongo_connector.oplog_manager:633 - OplogThread: Failed during dump collection cannot recover! 
2017-03-13 15:16:56,670 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140298115454720)> unexpectedly stopped! Shutting down

**Comment by turivishal** [comment]
Have you got any solution on this?
