### ISSUE TITLE
"CollectionInvalid: collection <CC> already exists" exception when catching up the op-log

### ISSUE THREAD

**Issue by bhyde** [mongodb-labs/mongo-connector#696]
My use case is moving a replica set from A to B.  I take an EBS snapshot of A (at time t1) and use that to seed B.   That can take while so let's say I get it up at time t2.   I then use mongo-connector bring B into sync with A via A's oplog.    I do that with noDump.  The oldest entry in the oplog is from time t0.    Of course it's hopeless if t1 > t0; but the good news is it's not.  It's slower than one might like if t0 is much earlier than t1, but that's ok.

But.  I'm encountering a problem where mongo conector fails

```
2017-04-11 20:53:38.814307500  2017-04-11 20:53:38,813 [ERROR] mongo_connector.util:106 - Fatal Exception
2017-04-11 20:53:38.814321500  Traceback (most recent call last):
2017-04-11 20:53:38.814322500    File "/home/bhyde/.pyenv/versions/2.7.11/lib/python2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
2017-04-11 20:53:38.814323500      func(*args, **kwargs)
2017-04-11 20:53:38.814324500    File "/home/bhyde/.pyenv/versions/2.7.11/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 283, in run
2017-04-11 20:53:38.814325500      timestamp)
2017-04-11 20:53:38.814325500    File "/home/bhyde/.pyenv/versions/2.7.11/lib/python2.7/site-packages/mongo_connector/util.py", line 35, in wrapped
2017-04-11 20:53:38.814326500      return f(*args, **kwargs)
2017-04-11 20:53:38.814327500    File "/home/bhyde/.pyenv/versions/2.7.11/lib/python2.7/site-packages/mongo_connector/doc_managers/mongo_doc_manager.py", line 150, in handle_command
2017-04-11 20:53:38.814328500      self.mongo[new_db].create_collection(coll)
2017-04-11 20:53:38.814329500    File "/home/bhyde/.pyenv/versions/2.7.11/lib/python2.7/site-packages/pymongo/database.py", line 342, in create_collection
2017-04-11 20:53:38.814329500      raise CollectionInvalid("collection %s already exists" % name)
2017-04-11 20:53:38.814330500  CollectionInvalid: collection <CC> already exists
```

Which I presume means that <CC> was created during the interval t0..t1.

Mumble ... idempotent ... mumble.

I guess I'm thinking the work around is to catch the exception, delete the collection, and try again.  Or preflight the operation and delete the collection before creating it.

**Comment by bhyde** [comment]
As an aside I was previously trying to be clever, to avoid tedium of starting at t0 rather than some time only a bit earlier that t1.  But that hand work was fraught, mistakes were made, time was wasted.  So I switched to the simpler, slower, and presumably safer approach shown above.

**Comment by ShaneHarvey** [comment]
Yes, this is a problem with mongo-connector. MongoDB's oplog entries are idempotent to MongoDB internally (a create collection oplog entry can be re-applied without error), but mongo-connector turns a create collection oplog entry into a call to the [`create`](https://docs.mongodb.com/manual/reference/command/create/) collection _command_. The `create` command is also idempotent but instead of doing nothing if the collection already exists it returns an error.

I don't think simply catching and ignoring `CollectionInvalid: collection <CC> already exists` is a good solution because that might mask legitimate errors. For example, the destination has a collection named "db.foo" that the user forgot to delete. They run mongo-connector and create a new "db.foo" collection on the source. In this case, mongo-connector should quit when it tries to re-create "db.foo" on the destination. 

Alternatively, you can use mongo-connector without `noDump` to avoid this issue altogether.

**Comment by bhyde** [comment]
In my use case, where we don't delete collections or tinker with their assorted properties; we only add 'em  in the most vanilla way.   So, I think i'm fine ignoring the error.

In the general case it's accurate to catch the error, delete the collection, and then recreate the collection.  At least I'd think so.

Seeding from the snapshot + noDump is a huge win if the database is huge; for example you don't need to unwind the compression, serialize, move it over wires, etc. etc.

**Comment by raffaeleguidi** [comment]
Progress on the issue seems to have stalled - but I am still facing it. I would suggest that a --continue-on-error flag would be useful for the oplog as well (--continue-on-oplog-error?) or at least something specific for the collection already exists error

**Comment by ThomasLobker** [comment]
It seems like this was fixed in fb6250ed36216cff7423a51e8ee8dc2dac8612d6
