### ISSUE TITLE
missing authentication token for REST request

### ISSUE THREAD

**Issue by leaverij** [mongodb-labs/mongo-connector#712]
Hi all,
I run local mongo (3.0) replica set and elasticsearch. When I install elasticsearch 2.4.3 all things work fine. The JSON document is synced to elasticsearch successfully. However, if I install elastic using the latest version 5.4.0 it does not work. Below is my steps:
1. Launch mongo replica set and elasticsearch 5.4.0.
2. create config.json
`
{
    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "username:password@localhost:9200"
        }
    ]
}
`
3. Launch mongo-connector using command:
mongo-connector -c config.json -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager -v
4. insert a document into mongodb 
5. get security exception in log file:
`2017-06-12 17:41:30,329 [DEBUG] elasticsearch:110 - < {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/_bulk]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/_bulk]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
2017-06-12 17:41:30,329 [ERROR] mongo_connector.doc_managers.elastic2_doc_manager:491 - Bulk request failed with exception
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 484, in send_buffered_operations
    successes, errors = bulk(self.elastic, action_buffer)
  File "c:\python36\lib\site-packages\elasticsearch\helpers\__init__.py", line 195, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "c:\python36\lib\site-packages\elasticsearch\helpers\__init__.py", line 163, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "c:\python36\lib\site-packages\elasticsearch\helpers\__init__.py", line 92, in _process_bulk_chunk
    raise e
  File "c:\python36\lib\site-packages\elasticsearch\helpers\__init__.py", line 88, in _process_bulk_chunk
    resp = client.bulk('\n'.join(bulk_actions) + '\n', **kwargs)
  File "c:\python36\lib\site-packages\elasticsearch\client\utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "c:\python36\lib\site-packages\elasticsearch\client\__init__.py", line 1165, in bulk
    doc_type, '_bulk'), params=params, body=self._bulk_body(body))
  File "c:\python36\lib\site-packages\elasticsearch\transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "c:\python36\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\python36\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, 'security_exception', 'missing authentication token for REST request [/_bulk]')
`

Could someone tell what's wrong?

**Comment by qyou** [comment]
@leaverij You can use one of the config file or the arguments only. The arguments you passed have overwritten the settings in the`config.json` . Try it like this:

```bash
mongo-connector -c config.json -m localhost:27017 
```
or 
```bash
mongo-connector -m localhost:27017 -t username:password@localhost:9200 -d elastic2_doc_manager 
```
