### ISSUE TITLE
ServerSelectionTimeoutError: 192.168.0.103:27019: timed out,192.168.0.101:27018: timed out

### ISSUE THREAD

**Issue by bytename** [mongodb-labs/mongo-connector#716]
The remote server is synchronized to the local monogo
The mongodb on the remote server is version 2.8
Local mongo is version 3.2.6
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 441, in run
    self.update_version_from_client(shard_conn)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 334, in update_version_from_client
    is_master = client.admin.command("isMaster")
  File "/usr/local/lib/python2.7/site-packages/pymongo/database.py", line 491, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 859, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/local/lib/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: 192.168.0.103:27019: timed out,192.168.0.101:27018: timed out
command：
mongo-connector -m remote:27017 -t localhost:30000 --logfile=mongo_status.log -n test.status    -d mongo_doc_manager

**Comment by thephysicsriot** [comment]
Hi, did you ever reach a resolution for this? I am running into the same problem. When I start mongo-connector `ServerSelectionTimeoutError: <host>:<port> timed out` but this host is one that I removed from the mongodb Replica Set at an earlier time.
