### ISSUE TITLE
Solr responded with an error (HTTP 404): [Reason: Error 404 ]

### ISSUE THREAD

**Issue by lucaswxp** [mongodb-labs/mongo-connector#722]
Hey guys.

I'm trying to import my mongodb data to solr. 

When execing `mongo-connector -m localhost:27017 -t http://localhost:8983/ -d solr_doc_manager` I get the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1275, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/config.py", line 120, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1024, in apply_doc_managers
    dm_instances.append(DocManager(target_url, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 80, in __init__
    self._build_fields()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 46, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 96, in _build_fields
    declared_fields = self.solr._send_request('get', ADMIN_URL)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
mongo_connector.errors.OperationFailed: Solr responded with an error (HTTP 404): [Reason: Error 404 ]
```

Any idea? Not sure how to debug further. Seeing the solr logs didn't help either.

**Comment by elyograg** [comment]
User came to solr IRC channel for help.  Problem was incomplete URL for Solr.  Needs to be http://host:/port/solr/corename to work properly.

**Comment by lucaswxp** [comment]
@elyograg Yes, thanks for the help!

Changing the command to this worked:
`mongo-connector -m localhost:27017 -t http://localhost:8983/solr/COREADMIN -d solr_doc_manager`


But now I have another problem. Am I missing some basic understanding of how mongo-connector is supposed to work? I only have ONE collection that should be kept in sync with my solr instance, but connector is trying to dump all my collections from all databases.

I want it to import only the collection specified at my core schema.xml, since the `title` field only exists in one collection, I'm getting this error:

```
2017-07-31 13:20:39,874 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-07-31 13:20:39,892 [ALWAYS] mongo_connector.connector:51 - Python version: 2.7.11 (default, Jan 22 2016, 08:28:37) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
2017-07-31 13:20:39,997 [ALWAYS] mongo_connector.connector:51 - Platform: Darwin-16.4.0-x86_64-i386-64bit
2017-07-31 13:20:39,997 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.4.0
2017-07-31 13:20:40,002 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.2.3
2017-07-31 13:20:40,003 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.solr_doc_manager version: 0.1.0
2017-07-31 13:21:00,258 [ERROR] pysolr:392 - Solr responded with an error (HTTP 400): [Reason: [doc=58d5d64fbf88ea44f3972302] missing required field: title]
2017-07-31 13:21:00,281 [CRITICAL] mongo_connector.oplog_manager:671 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 626, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 612, in upsert_all
    mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 46, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 294, in bulk_upsert
    self.solr.add(batch, **add_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 891, in add
    overwrite=overwrite, handler=handler)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 478, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
OperationFailed: Solr responded with an error (HTTP 400): [Reason: [doc=58d5d64fbf88ea44f3972302] missing required field: title]
2017-07-31 13:21:00,359 [ERROR] mongo_connector.oplog_manager:679 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=u'reduza'), u'local'), u'oplog.rs')
2017-07-31 13:21:01,044 [ERROR] mongo_connector.connector:398 - MongoConnector: OplogThread <OplogThread(Thread-2, started 123145386500096)> unexpectedly stopped! Shutting down
```

**Comment by elyograg** [comment]
I'm a Solr person and know nothing about the mongo connector, which is most likely where the decision about what to insert is being made.

**Comment by lucaswxp** [comment]
I'm understand @elyograg, thanks anyway! I'll wait to see if anyone else knows what is going on.

**Comment by ShaneHarvey** [comment]
@lucaswxp, check out the wiki section for including specific namespaces: https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#including-namespaces
