### ISSUE TITLE
Excluded fields not working for nested field in array

### ISSUE THREAD

**Issue by jrhone** [mongodb-labs/mongo-connector#726]
I have a DBRef field in my mongo data, which is not currently supported by mongo-connector, so I have set it to be excluded in my config, but instead I'm receiving this error.

```
2017-08-08 08:31:51,085 [DEBUG] elasticsearch:86 - < {"took":10,"errors":true,"items":[{"index":{"_index":"drop_1","_type":"drop","_id":"5989741da3388d77e247f807","status":400,"error":{"type":"mapper_parsing_exception","reason":"object mapping for [droplets.origin._ref] tried to parse field [_ref] as object, but found a concrete value"}}},{"index":{"_index":"mongodb_meta","_type":"mongodb_meta","_id":"5989741da3388d77e247f807","_version":4,"result":"updated","_shards":{"total":2,"successful":2,"failed":0},"created":false,"status":200}}]}
2017-08-08 08:31:51,086 [ERROR] mongo_connector.doc_managers.elastic2_doc_manager:491 - Bulk request failed with exception
Traceback (most recent call last):
  File "/home/flask/.pyenv/versions/3.6.1/envs/latest_v3/lib/python3.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 484, in send_buffered_operations
    successes, errors = bulk(self.elastic, action_buffer)
  File "/home/flask/.pyenv/versions/3.6.1/envs/latest_v3/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 195, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/home/flask/.pyenv/versions/3.6.1/envs/latest_v3/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 163, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/home/flask/.pyenv/versions/3.6.1/envs/latest_v3/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 135, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'drop_1', '_type': 'drop', '_id': '5989741da3388d77e247f807', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'object mapping for [droplets.origin._ref] tried to parse field [_ref] as object, but found a concrete value'}}}])
```

My config is 
```
    "namespaces": {
	"melody_app_develop.drop": {
	    "rename": "drop.drop",
	    "excludeFields": ["droplets.origin._ref"]  # I've also tried 'droplets.origin'
	}
    }
```

The data looks like
```
{
  "droplets": [
    {
      "origin": {
        "_ref": ...
      }
    }
  ]
}
```

**Comment by ShaneHarvey** [comment]
Unfortunately, this limitation on the excludeFields option. It is pointed out in the documentation:
> Note: mongo-connector does not support filtering fields inside arrays, you can only include or exclude the entire array field.

https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#filtering-documents-per-namespace
