### ISSUE TITLE
SocketError: timed out

### ISSUE THREAD

**Issue by Mediumwater** [mongodb-labs/mongo-connector#744]
Hello,

iam facing a SocketError: timed out.

mongo-connector  -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager

[ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
[ALWAYS] mongo_connector.connector:51 - Python version: 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2]
mongo_connector.connector:51 - Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
mongo_connector.connector:51 - pymongo version: 3.5.1
mongo_connector.connector:167 - MongoConnector: Can't find /var/www/mongo-connector/oplog.timestamp, attempting to create an empty progress log
mongo_connector.connector:51 - Source MongoDB version: 3.4.9
mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.neo4j_doc_manager version: unknown
httpstream:168 - ! SocketError: timed out
mongo_connector.oplog_manager:670 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 625, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 611, in upsert_all
    mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/neo4j_doc_manager.py", line 89, in bulk_upsert
    tx.commit()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/core.py", line 333, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/core.py", line 275, in post
    rs = resource.post({"statements": self.statements})
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 307, in post
    response = self.__base.post(body, headers, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 984, in post
    return rq.submit(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 433, in submit
    http, rs = submit(self.method, uri, self.body, self.headers)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 362, in submit
    raise SocketError(code, description, host_port=uri.host_port)
SocketError: timed out

- The time out leads to an empty  oplog.timestamp, so if i restart i get tons of exceptions, like 

2017-09-20 23:20:15,869 [CRITICAL] mongo_connector.oplog_manager:670 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 625, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 611, in upsert_all
    mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 46, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/neo4j_doc_manager.py", line 89, in bulk_upsert
    tx.commit()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/core.py", line 333, in commit
    return self.post(self.__commit or self.__begin_commit)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/core.py", line 288, in post
    raise self.error_class.hydrate(error)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/error/core.py", line 54, in hydrate
    error_cls = getattr(error_module, title)
Neo4jOperationFailed: 'module' object has no attribute 'ConstraintValidationFailed'

- right now i think, that because of the restart and the not existing oplog file value, it trys to completly restart and Neo4j cant insert the same content again. Or my mongodb is defect, i already repaired it with mongod --repair. So i would like to have a oplog.timestamp file. 
I thought that i can get that with the parameter: 

--batch-size ( Default: -1 - Number of records processed from the oplog before updating the timestamp file.)

like,  
mongo-connector  --batch-size=100 -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager

but there is no timestamp written at anytime.

The only way i get a timestamp in the file is when i say ---no-dump, which is not realy helpful.

--------------------------------------------------------------------------------------------------------------------

So, how can i write a timestamp into the - oplog.timestamp - while it processes?

Thanks

**Comment by Mediumwater** [comment]
Solved it, after installing the 3.0 Update for the "neo4j_doc_manager" and using py2neo > 3, the Timestamp gets printed.
