### ISSUE TITLE
connector can't parse config file - unhelpful error message

### ISSUE THREAD

**Issue by thejeff77** [mongodb-labs/mongo-connector#747]
when I run mongo-connector with a configuration file, >mongo-connector -c mc.json,

I get this unhelpful error:

```
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1275, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/config.py", line 120, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1026, in apply_doc_managers
    dm_instances.append(DocManager(**kwargs))
TypeError: __init__() takes at least 2 arguments (4 given)
```
Here is my config file.

I could use some help! Thanks for any support.

```
{
   "mainAddress": "<host:port>",
   "authentication": {
     "password": "<pw>",
     "adminUsername": "<username>" 
   },
   "exclude_fields": ["example"],
   "docManagers": [
    {
      "docManager": "elastic2_doc_manager",
      "targetURL": "<es-url>"
    }
   ],
   "logging": {
     "filename": "/home/something/logs"
   },
   "namespaces": {
     "something1.*": false,
     "something2.*": false,
     "something3.specific1": false
   }
}
```

I am however able to run from the commandline, but I don't have any namespaces specified.

**Comment by Athorcis** [comment]
Hi, i'm also facing this issue, how did you resolve it ?
