### ISSUE TITLE
mongo-connector  error Unable to process oplog document 

### ISSUE THREAD

**Issue by jiucai** [mongodb-labs/mongo-connector#761]
I faild to use mongo-connector with elasticsearch  error message:

```
mongo_connector.oplog_manager:288 - Unable to process oplog document 
```

I do not know what wrong with my servers, please help.
Thanks  💯 

```
mongo-connector: 2.5.1
mongodb server: 3.4.10
python version: 3.6.3
elastic2-doc-manager: 0.3.0
elasticsearch server: 5.6.3
```

doc i saved in mongo is:

mongo
> use foo
> db.c.insert({"name": "Mongo Connector test"})

cmd for start  mongo-connector :

mongo-connector -c config.json

The mongo user  in config file is right to read oplogs
config.json file:
```
{
    "__comment__": "Configuration options starting with '__' are disabled",
    "__comment__": "To enable them, remove the preceding '__'",

    "mainAddress": "server1:27017,server2:27017,server3:27017",
    "oplogFile": "logs/oplog.timestamp",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 0,
    "continueOnError": false,

    "logging": {
        "type": "file",
        "filename": "logs/mongo-connector.log",
        "__format": "%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s",
        "__rotationWhen": "D",
        "__rotationInterval": 1,
        "__rotationBackups": 10,
        "__type": "syslog",
        "__host": "localhost:514"
    },

    "authentication": {
        "adminUsername": "opreader",
        "password": "passwordxxx"
    },

    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "server4:9200",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": null
        }
    ]
}
```
es logs:
```
[2017-11-16T16:07:20,243][INFO ][o.w.a.d.Monitor          ] try load config from /data/app/es/config/analysis-ik/IKAnalyzer.cfg.xml
[2017-11-16T16:07:20,358][INFO ][o.w.a.d.Monitor          ] try load config from /data/app/elasticsearch-5.6.3/plugins/elasticsearch-analysis-ik-5.6.3/config/IKAnalyzer.cfg.xml
[2017-11-16T16:07:21,587][INFO ][o.e.c.m.MetaDataCreateIndexService] [node182] [foo] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2017-11-16T16:07:22,675][INFO ][o.e.c.m.MetaDataCreateIndexService] [node182] [mongodb_meta] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2017-11-16T16:07:23,457][INFO ][o.e.c.m.MetaDataMappingService] [node182] [foo/RsHSHoWYToCBaqEJekbInw] create_mapping [c]
[2017-11-16T16:07:23,467][INFO ][o.e.c.m.MetaDataMappingService] [node182] [mongodb_meta/cxVgjiICR7KGTn7j0v5LlA] create_mapping [mongodb_meta]

```

mongo-connector logs: 

```
2017-11-16 16:01:12,821 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2017-11-16 16:01:12,821 [ALWAYS] mongo_connector.connector:51 - Python version: 3.6.3 (default, Nov 14 2017, 19:40:39) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
2017-11-16 16:01:12,822 [ALWAYS] mongo_connector.connector:51 - Platform: Linux-2.6.32-642.13.1.el6.x86_64-x86_64-with-centos-6.8-Final
2017-11-16 16:01:12,822 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.5.1
2017-11-16 16:01:12,850 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.10
2017-11-16 16:01:12,850 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2017-11-16 16:07:18,471 [ERROR] mongo_connector.oplog_manager:288 - Unable to process oplog document {'ts': Timestamp(1510819637, 1), 't': 1, 'h': -8655636986832009628, 'v': 2, 'op': 'c', 'ns': 'foo.$cmd', 'o': {'create': 'c', 'idIndex': {'v': 2, 'key': {'_id': 1}, 'name': '_id_', 'ns': 'foo.c'}}}
Traceback (most recent call last):
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 246, in handle_command
    "_source": {"enabled": True}
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 282, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mongo_connector/oplog_manager.py", line 283, in run
    timestamp)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mongo_connector/util.py", line 46, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mongo_connector/compat.py", line 9, in reraise
    raise exctype(str(value)).with_traceback(trace)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mongo_connector/doc_managers/elastic2_doc_manager.py", line 246, in handle_command
    "_source": {"enabled": True}
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 282, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/data/app/.pyenv/versions/3.6.3/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
mongo_connector.errors.OperationFailed: TransportError(404, 'index_not_found_exception', 'no such index')

```

**Comment by jiucai** [comment]
this error does not effect index data creating . I can search with curl get

$ curl -XGET http://server4:9200/foo/c/_search?pretty

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 6,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "foo",
        "_type" : "c",
        "_id" : "5a0d473532e595136e78c30e",
        "_score" : 1.0,
        "_source" : {
          "name" : "Mongo Connector test"
        }
      },
      {
        "_index" : "foo",
        "_type" : "c",
        "_id" : "5a0d607332e595136e78c313",
        "_score" : 1.0,
        "_source" : {
          "name" : "jiucai"
        }
      }
    ]
  }
}
```

**Comment by kgrvamsi** [comment]
@jiucai what authentication mode are you running the mongo db instance SCRAM-SHA-12 or MONGODB-CR?

```
 "authentication": {
        "adminUsername": "opreader",
        "password": "passwordxxx"
    },
```
