### ISSUE TITLE
TransportError(406, 'Content-Type header [] is not supported')

### ISSUE THREAD

**Issue by joyran** [mongodb-labs/mongo-connector#795]
Log

```
2018-02-13 15:43:48,241 [ALWAYS] mongo_connector.connector:51 - Starting mongo-connector version: 2.5.1
2018-02-13 15:43:48,242 [ALWAYS] mongo_connector.connector:51 - Python version: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
2018-02-13 15:43:48,242 [ALWAYS] mongo_connector.connector:51 - Platform: Windows-10-10.0.15063-SP0
2018-02-13 15:43:48,242 [ALWAYS] mongo_connector.connector:51 - pymongo version: 3.6.0
2018-02-13 15:43:48,270 [ALWAYS] mongo_connector.connector:51 - Source MongoDB version: 3.4.5
2018-02-13 15:43:48,271 [ALWAYS] mongo_connector.connector:51 - Target DocManager: mongo_connector.doc_managers.elastic2_doc_manager version: 0.3.0
2018-02-13 15:43:48,301 [WARNING] elasticsearch:82 - POST /_bulk [status:406 request:0.012s]
2018-02-13 15:43:48,302 [CRITICAL] mongo_connector.oplog_manager:670 - Exception during collection dump
Traceback (most recent call last):
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\mongo_connector\util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\mongo_connector\doc_managers\elastic2_doc_manager.py", line 367, in bulk_upsert
    for ok, resp in responses:
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\helpers\__init__.py", line 160, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\helpers\__init__.py", line 89, in _process_bulk_chunk
    raise e
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\helpers\__init__.py", line 85, in _process_bulk_chunk
    resp = client.bulk('\n'.join(bulk_actions) + '\n', **kwargs)
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\client\utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\client\__init__.py", line 782, in bulk
    doc_type, '_bulk'), params=params, body=self._bulk_body(body))
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "c:\users\xinsh\appdata\local\programs\python\python36\lib\site-packages\elasticsearch\connection\base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(406, 'Content-Type header [] is not supported')
```

**Comment by dbasea** [comment]
I'm having the same issue here - are there any workarounds?

**Comment by peilirui** [comment]
Me too!

**Comment by peilirui** [comment]
I find a available solution:
use `pip install 'elastic2-doc-manager[elastic5]'`
to install a new version of python-elasticsearch operator
