### ISSUE TITLE
Can we use Mongo-connector to index MongoDB Atlas document into Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by GirdhariAtGit** [mongodb-labs/mongo-connector#797]
We have a requirement to connect and index **AWS MongoDB Atlas document** into **Amazon Elasticsearch Service**. 

@llovett 

is it possible using Mongo-connector ?
 

Thanks

**Comment by GirdhariAtGit** [comment]
Its working fine.

**Comment by vishaleclass** [comment]
Hi @GirdhariAtGit 
Can you please help me with steps or any info which can help me? 
I'm trying to use Mongo-connector to index MongoDB Atlas document into Elasticsearch cloud stack. 
However getting below error. 

```
Logging to /root/mongo-connector.log.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 107, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 353, in run
    self.main_conn = self.create_authed_client()
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 337, in create_authed_client
    client["admin"].authenticate(self.auth_username, self.auth_key)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 1274, in authenticate
    connect=True)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 604, in _cache_credentials
    raise OperationFailure('Another user is already authenticated '
OperationFailure: Another user is already authenticated to this database. You must logout first.


```
