### ISSUE TITLE
Oplog thread won't work when the Mongodb Authentication is enabled

### ISSUE THREAD

**Issue by kgrvamsi** [mongodb-labs/mongo-connector#801]
Config used:
```
{
    "__comment__": "Configuration options starting with '__' are disabled",
    "__comment__": "To enable them, remove the preceding '__'",

    "mainAddress": "192.168.0.47:27017",
    "oplogFile": "/home/ubuntu/testing/oplog.timestamp",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 0,
    "continueOnError": false,

    "logging": {
        "type": "file",
        "filename": "mongo-connector.log",
        "format": "%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s",
        "__rotationWhen": "D",
        "__rotationInterval": 1,
        "__rotationBackups": 10,

        "__type": "syslog",
        "__host": "localhost:514"
    },
### I'm using the MONGODB-CR Authentication ######
    "authentication": {
        "adminUsername": "root",
        "password": "password"
    },
    "namespaces": {
    "db.excluded_collection": false,
    "excluded_database.*": false,
    "*.exclude_collection_from_every_database": false
    },

    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "elastic:elasticpassword@192.168.0.46:9200",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": null
        }
    ]
}
```

Error from Logs:

```
2018-03-07 05:25:44,963 [INFO] mongo_connector.oplog_manager:120 - OplogThread: Initializing oplog thread
2018-03-07 05:25:44,965 [ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 387, in run
    self.namespace_config, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 126, in __init__
    if not self.oplog.find_one():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1225, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1169, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1085, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 975, in __send_message
    helpers._check_command_response(first)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: not authorized on local to execute command { find: "oplog.rs", filter: {}, limit: 1, singleBatch: true }
```

**Comment by kgrvamsi** [comment]
@ShaneHarvey need your help :)

**Comment by rickhard22** [comment]
Has this been solved?
