### ISSUE TITLE
mongo_connector.util:106 - Fatal Exception Traceback (most recent call last)

### ISSUE THREAD

**Issue by 678yoyo** [mongodb-labs/mongo-connector#806]
hi , I got a serious problem today，the mongo-connector.log's content is here :
[ERROR] mongo_connector.util:106 - Fatal Exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 274, in run
    ns, timestamp)
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 252, in update
    doc.pop('ns')
KeyError: 'ns'
2018-03-22 15:32:30,234 [ERROR] mongo_connector.connector:398 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 139633480431360)> unexpectedly stopped! Shutting down

**Comment by 678yoyo** [comment]
MongoDB version: 3.4.10
 mongo-connector version: 2.5.1
Python version: 2.7.5 
solr version:5.5.5
