### ISSUE TITLE
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000000000461D198>: Failed to establish a new connection: [WinError 10061] 

### ISSUE THREAD

**Issue by yangjingying1993** [mongodb-labs/mongo-connector#812]
when i ran this command line: mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager,the log showed like this:
2018-04-20 09:24:54,424 [WARNING] elasticsearch:82 - POST http://localhost:9200/_refresh [status:N/A request:1.008s]
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\util\retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\programdata\anaconda3\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\programdata\anaconda3\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\programdata\anaconda3\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\programdata\anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\programdata\anaconda3\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "c:\programdata\anaconda3\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000000049986A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by luckyy199213** [comment]
还没人解决 tmd
